/* ══════════════════════════════════════════════════════════════════════════
   C++ CODE GENERATION — pure string builders for GAS (Gameplay Ability System)
   ══════════════════════════════════════════════════════════════════════════ */

export type AttrCategory = 'meta' | 'vital' | 'primary' | 'combat' | 'progression';

export interface EditorAttribute {
  id: string;
  name: string;
  category: AttrCategory;
  defaultValue: number;
  clampMin?: number;
  clampMax?: string; // string to allow "MaxHealth" references
}

export type EffectDuration = 'instant' | 'duration' | 'infinite';

export interface EditorEffect {
  id: string;
  name: string;
  duration: EffectDuration;
  durationSec: number;
  cooldownSec: number;
  color: string;
  modifiers: { attribute: string; operation: 'add' | 'multiply'; magnitude: number }[];
  grantedTags: string[];
}

export interface TagRule {
  id: string;
  sourceTag: string;
  targetTag: string;
  type: 'blocks' | 'cancels' | 'requires';
}

export interface GASLoadoutSlot {
  id: string;
  slot: number;
  abilityName: string;
  iconColor: string;
  cooldownTag: string;
}

export function generateAttributeSetHeader(attrs: EditorAttribute[]): string {
  const lines: string[] = [
    '// Auto-generated by PoF GAS Blueprint Editor',
    '#pragma once',
    '#include "AttributeSet.h"',
    '#include "AbilitySystemComponent.h"',
    '#include "ARPGAttributeSet.generated.h"',
    '',
    'UCLASS()',
    'class UARPGAttributeSet : public UAttributeSet',
    '{',
    '    GENERATED_BODY()',
    '',
    'public:',
    '    UARPGAttributeSet();',
    '',
  ];

  const grouped = new Map<string, EditorAttribute[]>();
  for (const a of attrs) {
    const arr = grouped.get(a.category) || [];
    arr.push(a);
    grouped.set(a.category, arr);
  }

  for (const [cat, catAttrs] of grouped) {
    lines.push(`    // ── ${cat.charAt(0).toUpperCase() + cat.slice(1)} ──`);
    for (const a of catAttrs) {
      const meta = a.clampMin != null ? `, Meta=(AllowPrivateAccess="true")` : '';
      lines.push(`    UPROPERTY(BlueprintReadOnly, Category="Attributes|${cat}"${meta})`);
      lines.push(`    FGameplayAttributeData ${a.name};`);
      lines.push(`    ATTRIBUTE_ACCESSORS(UARPGAttributeSet, ${a.name})`);
      lines.push('');
    }
  }

  lines.push('    virtual void PreAttributeChange(const FGameplayAttribute& Attribute, float& NewValue) override;');
  lines.push('    virtual void PostGameplayEffectExecute(const FGameplayEffectModCallbackData& Data) override;');
  lines.push('};');

  return lines.join('\n');
}

export function generateTagsHeader(rules: TagRule[], loadout: GASLoadoutSlot[]): string {
  const tags = new Set<string>();
  for (const r of rules) {
    if (!r.sourceTag.includes('*')) tags.add(r.sourceTag);
    if (!r.targetTag.includes('*')) tags.add(r.targetTag);
  }
  for (const s of loadout) {
    if (s.cooldownTag) tags.add(s.cooldownTag);
    tags.add(`Ability.${s.abilityName}`);
  }

  const lines: string[] = [
    '// Auto-generated by PoF GAS Blueprint Editor',
    '#pragma once',
    '#include "GameplayTagContainer.h"',
    '',
    'struct FARPGGameplayTags',
    '{',
    '    static const FARPGGameplayTags& Get() { return GameplayTags; }',
    '',
  ];

  const sorted = [...tags].filter(t => t.length > 0).sort();
  for (const tag of sorted) {
    const varName = tag.replace(/\./g, '_');
    lines.push(`    FGameplayTag ${varName};`);
  }

  lines.push('', 'private:', '    static FARPGGameplayTags GameplayTags;', '};');
  return lines.join('\n');
}
