import type { ProjectRule } from './types';

export const CANON_SEED: ProjectRule[] = [
  // ── GAME ──
  { id: 'game-genre', category: 'game', scope: 'global', title: 'Genre', body: 'PoF is a single-player Action RPG (ARPG) built in UE5.7.' },
  { id: 'game-pillars', category: 'game', scope: 'global', title: 'Pillars', body: 'Disciplined, rhythmic melee (weave light/heavy, never button-mash); power is earned, not gifted; grounded dark fantasy over high fantasy.' },
  { id: 'game-tone', category: 'game', scope: 'global', title: 'Tone', body: "Grim, weathered, earned — a soldier's world, not a hero's fantasy. Restraint over spectacle; items and enemies feel used and real." },
  { id: 'game-setting', category: 'game', scope: 'global', title: 'Setting', body: 'Post-Sundering dark fantasy; militant factions such as the Ashen Order. Magic is dangerous and costly.' },
  // ── ART ──
  { id: 'art-identity', category: 'art', scope: 'global', title: 'Visual identity', body: 'Painterly-realistic, weathered, grounded. Muted earthen palette; saturation reserved for rarity and elemental accents.' },
  { id: 'art-icons', category: 'art', scope: 'global', title: 'Icon style', body: '256px, 3/4 view, strong readable silhouette, rarity-framed; consistent light from the upper-left.' },
  { id: 'art-3d', category: 'art', scope: 'global', title: '3D style', body: 'PBR and Nanite-friendly; respect per-class LOD0 tri budgets; grounded real-world scale.' },
  { id: 'art-material', category: 'art', scope: 'global', title: 'Material style', body: 'Author as master-material instances; expose wear/tint params; Albedo/Normal/ORM are required maps.' },
  { id: 'art-vfx', category: 'art', scope: 'global', title: 'VFX style', body: 'Niagara; restrained and readable; keyed to anim notifies; stay within the per-class GPU budget.' },
  // ── PROJECT ──
  { id: 'proj-naming', category: 'project', scope: 'global', title: 'Asset naming', body: 'UE prefixes: T_ texture, SM_ static mesh, MI_ material instance, A_ anim, NS_ Niagara, SC_ SoundCue, GE_/GA_ GAS, DT_ DataTable. PascalCase, space-free slugs.' },
  { id: 'proj-sot', category: 'project', scope: 'global', title: 'Source of truth', body: 'Attributes come from UARPGAttributeSet; row schemas from the F*Row structs; ability math from ARPGDamageExecution. The app validates against UE and never re-authors schema (schema-down, content-up).' },
  { id: 'proj-balance', category: 'project', scope: 'global', title: 'Balance envelopes', body: 'Tier power target ≈ 100 (±10%). Price/power ratio 0.8–1.2×. Document any intentional outlier.' },
  { id: 'proj-links', category: 'project', scope: 'global', title: 'Cross-catalog links', body: 'bestiary→abilities + loot; loot→items; vendor→items + economy; currency defines caps + sinks. Reference upstream entities via CatalogLink (they may still be deferred).' },
  { id: 'proj-quality', category: 'project', scope: 'global', title: 'Quality bar', body: 'config-complete (the parallel-dev done bar) = every step passes at L0–L2 or is deferred at L3/L4. Brief ≥ 300 chars; all schema fields populated; an icon selected.' },
  { id: 'proj-economy', category: 'project', scope: 'currencies', title: 'Economy laws', body: 'Every currency must define at least one sink; caps prevent runaway inflation; the per-hour faucet and sink should stay balanced within ±15%. Premium and soft currencies never inter-convert freely.' },
  { id: 'art-icon-family', category: 'art', scope: 'icon-sets', title: 'Icon family coherence', body: 'Icons within a set share silhouette weight, line treatment, palette, rarity-frame, and light direction — the set reads as one family across every member.' },
  { id: 'art-icon-a11y', category: 'art', scope: 'global', title: 'Icon accessibility', body: 'Icons must hold AA contrast on the dark HUD, use colorblind-safe hue separation, and remain legible at 32px.' },
  { id: 'game-creature-design', category: 'game', scope: 'bestiary', title: 'Creature design', body: 'Enemies read by archetype (tank / skirmisher / caster / boss); attacks are telegraphed and counterable; difficulty comes from legible, learnable patterns — never stat inflation.' },
  { id: 'game-lore-canon', category: 'game', scope: 'global', title: 'Lore canon', body: 'All lore aligns to the post-Sundering setting and established factions with no contradictions; codex entries keep spoilers behind unlocks.' },
  { id: 'proj-hud-binding', category: 'project', scope: 'global', title: 'HUD binding contract', body: 'Any entity that surfaces in the HUD (currency, status, objective tracker) must declare its widget, a display-format string, and a HUD anchor; bind to a hud-elements presentation entry — never hard-code placement.' },
  // ── Wave 1 (2026-05-26): Quests / Character / Vendor / VFX / Input / Tutorial ──
  { id: 'quest-stage-graph', category: 'game', scope: 'quests', title: 'Quest stage graph', body: 'Every quest declares total stage count, which stage(s) fork on player choice (+ the fork condition), and the terminal stage(s) — both a success AND an explicit failure terminal. A quest with no terminal/fail path can silently block.' },
  { id: 'quest-reward-binding', category: 'project', scope: 'quests', title: 'Quest rewards bind to catalog rows', body: 'Reward tables, currency amounts, and reputation grants are CatalogLinks to loot-tables / currencies / factions — never inline — so balance is tuned centrally. Completion also declares its world-state mutation(s).' },
  { id: 'char-config-not-cpp', category: 'project', scope: 'characters', title: 'Named NPCs are configuration', body: 'A named NPC is a BP child of AARPGNPCActor (identity/role/dialogue/TalkTo live there) + one DT_AttributeDefaults stat row + cross-catalog wiring — NOT a new C++ class. Portrait/VO/footstep are bindings to shared presentation catalogs.' },
  { id: 'char-stat-source', category: 'project', scope: 'characters', title: 'Character/enemy stats live in DT_AttributeDefaults', body: 'Every character AND enemy authors one named FARPGAttributeInitRow in DT_AttributeDefaults (the L2 seed-row gate, via seed_attribute_defaults.py); never hardcode stats in C++ subclasses. Humanoids reuse SKM_Manny/ABP_Manny until a bespoke mesh/anim pipeline exists.' },
  { id: 'vendor-laws', category: 'project', scope: 'vendors', title: 'Vendor economy laws', body: 'Margin within ±20% of the 30% target; declare all three services (buy/sell/repair) explicitly; buyback = 50% of sell by default; reputation discount is linear off the factions repTier (no custom curves); settle only in currency-gold.' },
  { id: 'vfx-budget', category: 'art', scope: 'vfx', title: 'VFX budget & wiring', body: 'A VFX system fires from an AnimNotify (name matches its NS_ asset), never BeginPlay/timer; ships 3 LOD tiers (full / medium-50% / culled); peak GPU stays within the per-class budget (~0.48 ms). Restrained, readable — no gratuitous additive stacking.' },
  { id: 'input-remap-conflict', category: 'project', scope: 'global', title: 'Remap conflict + reserved keys', body: 'Any user-remappable feature calls FindConflictingAction before applying a binding (silent overwrite is a cert failure); platform-reserved system buttons (guide / share / create) are never remappable.' },
  { id: 'input-a11y', category: 'project', scope: 'input-schemes', title: 'Input accessibility', body: 'Every hold-duration action exposes a hold-to-toggle option; no action is chord-only; analog deadzone default 0.1–0.25, user-tunable and saved.' },
  { id: 'tutorial-sandbox', category: 'game', scope: 'tutorial-beats', title: 'Tutorial sandbox', body: 'A tutorial beat locks all inputs outside the taught mechanic within a named, scoped sandbox; linear advance by default — branching requires an explicit flag + a reachability check.' },
  { id: 'tutorial-telemetry', category: 'project', scope: 'tutorial-beats', title: 'Tutorial telemetry', body: 'Every beat fires beat_started / completed / skipped / failed and defines a comprehensionMetric so the onboarding funnel drop-off is measurable per beat.' },
];
