import { ENEMY_ARCHETYPES } from '@/lib/combat/definitions';
import type { PlacedEnemy, WaveDef } from '@/lib/combat/choreography-sim';
import type { TuningOverrides } from '@/types/combat-simulator';

export function generateUE5Export(
  enemies: PlacedEnemy[],
  waves: WaveDef[],
  tuning: TuningOverrides,
): string {
  const lines: string[] = [];
  lines.push('// ══════════════════════════════════════════════════════════════════════');
  lines.push('// Combat Encounter Configuration — generated by PoF Choreography Editor');
  lines.push('// ══════════════════════════════════════════════════════════════════════');
  lines.push('');

  lines.push('// ── FEncounterSpawnEntry (UDataTable rows) ─────────────────────────');
  lines.push('USTRUCT(BlueprintType)');
  lines.push('struct FEncounterSpawnEntry : public FTableRowBase');
  lines.push('{');
  lines.push('    GENERATED_BODY()');
  lines.push('');
  lines.push('    UPROPERTY(EditAnywhere) FName ArchetypeId;');
  lines.push('    UPROPERTY(EditAnywhere) int32 WaveIndex;');
  lines.push('    UPROPERTY(EditAnywhere) float SpawnTimeSec;');
  lines.push('    UPROPERTY(EditAnywhere) FVector2D GridPosition;');
  lines.push('    UPROPERTY(EditAnywhere) int32 Level;');
  lines.push('};');
  lines.push('');

  lines.push('// ── Spawn Data ─────────────────────────────────────────────────────');
  for (const [i, e] of enemies.entries()) {
    const arch = ENEMY_ARCHETYPES.find((a) => a.id === e.archetypeId);
    const wave = waves[e.waveIndex];
    lines.push(`// Row ${i + 1}: ${arch?.name ?? e.archetypeId}`);
    lines.push(`// ArchetypeId: "${e.archetypeId}", Wave: ${e.waveIndex}, SpawnTime: ${wave?.spawnTimeSec ?? 0}s, Grid: (${e.gridX}, ${e.gridY}), Level: ${e.level}`);
  }
  lines.push('');

  lines.push('// ── Wave Configuration ────────────────────────────────────────────');
  for (const [i, w] of waves.entries()) {
    lines.push(`// Wave ${i}: "${w.label}" at ${w.spawnTimeSec}s`);
  }
  lines.push('');

  lines.push('// ── CombatFeedbackComponent Parameter Overrides ───────────────────');
  lines.push(`UPROPERTY(EditAnywhere, Category = "Tuning") float PlayerDamageMul = ${tuning.playerDamageMul.toFixed(2)}f;`);
  lines.push(`UPROPERTY(EditAnywhere, Category = "Tuning") float EnemyHealthMul = ${tuning.enemyHealthMul.toFixed(2)}f;`);
  lines.push(`UPROPERTY(EditAnywhere, Category = "Tuning") float EnemyDamageMul = ${tuning.enemyDamageMul.toFixed(2)}f;`);
  lines.push(`UPROPERTY(EditAnywhere, Category = "Tuning") float ArmorEffectivenessWeight = ${tuning.armorEffectivenessWeight.toFixed(2)}f;`);
  lines.push(`UPROPERTY(EditAnywhere, Category = "Tuning") float CritMultiplierMul = ${tuning.critMultiplierMul.toFixed(2)}f;`);
  lines.push(`UPROPERTY(EditAnywhere, Category = "Tuning") float PlayerHealthMul = ${tuning.playerHealthMul.toFixed(2)}f;`);
  lines.push(`UPROPERTY(EditAnywhere, Category = "Tuning") float PlayerArmorMul = ${tuning.playerArmorMul.toFixed(2)}f;`);
  lines.push(`UPROPERTY(EditAnywhere, Category = "Tuning") float HealingMul = ${tuning.healingMul.toFixed(2)}f;`);

  return lines.join('\n');
}
