/**
 * Guide Generator — produces a reproducible game build guide as a side effect
 * of each successful harness iteration.
 *
 * The guide is the ultimate deliverable: a step-by-step playbook that another
 * LLM CLI session can follow to build a game using PoF.
 */

import * as fs from 'fs';
import * as path from 'path';
import type {
  GameBuildGuide,
  GamePlan,
  GuideStep,
  ModuleArea,
  ProgressEntry,
  VerificationReport,
} from './types';
import type { ParsedAreaResult } from './executor';
import { formatDuration } from '@/lib/format';
import { readJsonFile, writeJsonFile } from './state-io';

// ── Guide Building ──────────────────────────────────────────────────────────

export function createEmptyGuide(plan: GamePlan): GameBuildGuide {
  return {
    title: `How to Build ${plan.game} with PoF + UE5`,
    game: plan.game,
    generatedAt: new Date().toISOString(),
    totalIterations: 0,
    totalDurationMs: 0,
    buildOrder: [],
    steps: [],
    learnings: [],
    prerequisites: [
      `UE5 ${plan.ueVersion}+ installed`,
      'PoF app running (npm run dev)',
      'Project connected via Setup Wizard',
      `Project path: ${plan.projectPath}`,
    ],
  };
}

/**
 * Append a step to the guide after a successful area implementation.
 */
export function appendGuideStep(
  guide: GameBuildGuide,
  area: ModuleArea,
  result: ParsedAreaResult,
  verification: VerificationReport,
  progress: ProgressEntry,
): GuideStep {
  const step: GuideStep = {
    phase: guide.steps.length + 1,
    areaId: area.id,
    moduleId: area.moduleId,
    label: area.label,
    description: area.description,
    pofActions: area.checklistItemIds,
    ue5Files: [...(result.filesCreated ?? []), ...(result.filesModified ?? [])],
    decisions: result.features.map(f => ({
      decision: `Implemented ${f.name}`,
      rationale: f.notes || 'Standard implementation',
    })),
    gotchas: result.learnings ?? [],
    verification: verification.gates
      .map(g => `${g.passed ? 'PASS' : 'FAIL'} ${g.gate}`)
      .join(', '),
    durationMs: progress.durationMs,
  };

  guide.steps.push(step);
  guide.totalIterations++;
  guide.totalDurationMs += progress.durationMs;

  // Update learnings
  if (result.learnings) {
    guide.learnings.push(...result.learnings);
  }

  // Update build order
  const existing = guide.buildOrder.find(b => b.moduleId === area.moduleId);
  if (existing) {
    if (!existing.areas.includes(area.id)) {
      existing.areas.push(area.id);
    }
  } else {
    guide.buildOrder.push({ moduleId: area.moduleId, areas: [area.id] });
  }

  guide.generatedAt = new Date().toISOString();
  return step;
}

// ── Markdown Export ─────────────────────────────────────────────────────────

/**
 * Render the guide as a Markdown document suitable for another LLM CLI session.
 */
export function renderGuideMarkdown(guide: GameBuildGuide): string {
  const sections: string[] = [];

  // Header
  sections.push(`# ${guide.title}

> Generated by PoF Harness | ${guide.generatedAt.split('T')[0]} | ${guide.totalIterations} iterations
> Total build time: ${formatDuration(guide.totalDurationMs)}
`);

  // Prerequisites
  sections.push(`## Prerequisites

${guide.prerequisites.map(p => `- ${p}`).join('\n')}
`);

  // Build Order
  sections.push(`## Build Order (dependency-sorted)

${guide.buildOrder.map((b, i) => `${i + 1}. **${b.moduleId}** — areas: ${b.areas.join(', ')}`).join('\n')}
`);

  // Steps
  for (const step of guide.steps) {
    const gotchaSection = step.gotchas.length > 0
      ? `\n**Gotchas:**\n${step.gotchas.map(g => `- ${g}`).join('\n')}`
      : '';

    const filesSection = step.ue5Files.length > 0
      ? `\n**Files:**\n${step.ue5Files.map(f => `- \`${f}\``).join('\n')}`
      : '';

    sections.push(`---

### Phase ${step.phase}: ${step.label}

**Module:** \`${step.moduleId}\`
**Description:** ${step.description}
**Duration:** ${formatDuration(step.durationMs)}

**PoF Checklist Items to Run:**
${step.pofActions.map(a => `- \`${a}\``).join('\n')}

**What Gets Built:**
${step.decisions.map(d => `- ${d.decision}${d.rationale !== 'Standard implementation' ? ` — ${d.rationale}` : ''}`).join('\n')}
${filesSection}
${gotchaSection}

**Verification:** ${step.verification}
`);
  }

  // Accumulated Learnings
  if (guide.learnings.length > 0) {
    const unique = [...new Set(guide.learnings)];
    sections.push(`---

## Accumulated Learnings

${unique.map(l => `- ${l}`).join('\n')}
`);
  }

  if (guide.cost) {
    const { spentUsd, budgetUsd, sessions, byArea } = guide.cost;
    const pct = budgetUsd ? Math.round((spentUsd / budgetUsd) * 100) : null;
    const remaining = budgetUsd != null ? `$${(budgetUsd - spentUsd).toFixed(2)} remaining` : 'no cap';
    const topAreas = Object.entries(byArea ?? {})
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5)
      .map(([id, usd]) => `- \`${id}\` — $${usd.toFixed(2)}`)
      .join('\n');
    sections.push(`---

## Cost

**Total spend:** $${spentUsd.toFixed(2)}${pct != null ? ` (${pct}% of $${budgetUsd!.toFixed(2)} cap)` : ''} across ${sessions} executor session${sessions === 1 ? '' : 's'} — ${remaining}.

${topAreas ? `**Top spend by area:**\n${topAreas}` : ''}
`);
  }

  return sections.join('\n');
}

// ── File I/O ────────────────────────────────────────────────────────────────

export function loadGuide(statePath: string): GameBuildGuide | null {
  return readJsonFile<GameBuildGuide | null>(path.join(statePath, 'guide.json'), null);
}

export function saveGuide(statePath: string, guide: GameBuildGuide): void {
  writeJsonFile(path.join(statePath, 'guide.json'), guide);

  // Also write the Markdown version (not JSON, so a plain write).
  fs.writeFileSync(path.join(statePath, 'guide.md'), renderGuideMarkdown(guide));
}
