/**
 * /personal-loop walk order — frozen snapshot + cursor over the /status pipelines map.
 *
 *   npx tsx scripts/personal-loop/order.ts snapshot   # freeze the current /status order (only at loop start or on `reorder`)
 *   npx tsx scripts/personal-loop/order.ts next       # the next item to work (JSON)
 *   npx tsx scripts/personal-loop/order.ts status     # progress summary + regenerate order.md
 *
 * The order is column-major (`columnMajorOrder`): every pipeline's step 1 top-to-bottom,
 * then every step 2, … . It is FROZEN in `<vault>/Personal/order.json` because `sortLanes`
 * re-sorts by readiness — without the snapshot, lifting a cell would reshuffle the walk.
 * Progress is not stored here: each item's `status:` lives in its own vault note
 * (`Personal/items/<slug>.md`), so the notes stay the single source of truth.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { columnMajorOrder, itemSlug, type WalkItem } from '@/lib/status/personalLoop';
import { loadLanes, personalDir } from './truth';

type ItemStatus = 'todo' | 'in-progress' | 'done' | 'skipped' | 'parked';
const OPEN: ReadonlySet<ItemStatus> = new Set(['todo', 'in-progress']);

interface Snapshot {
  takenAt: string;
  items: WalkItem[];
}

const dir = personalDir();
const orderPath = join(dir, 'order.json');

function readSnapshot(): Snapshot {
  if (!existsSync(orderPath)) {
    process.stderr.write(`No snapshot at ${orderPath} — run \`order.ts snapshot\` first.\n`);
    process.exit(2);
  }
  return JSON.parse(readFileSync(orderPath, 'utf8')) as Snapshot;
}

/** An item's status from its note frontmatter; no note yet = todo. */
function statusOf(item: WalkItem): ItemStatus {
  const note = join(dir, 'items', `${itemSlug(item.catalogId, item.step)}.md`);
  if (!existsSync(note)) return 'todo';
  const m = /^status:\s*([a-z-]+)\s*$/m.exec(readFileSync(note, 'utf8'));
  return (m?.[1] as ItemStatus) ?? 'todo';
}

function writeOrderMd(snap: Snapshot, statuses: ItemStatus[]): void {
  const glyph: Record<ItemStatus, string> = { todo: '·', 'in-progress': '▶', done: '✓', skipped: '↷', parked: '⏸' };
  const lines = [
    '---',
    'type: personal/order',
    `snapshot: ${snap.takenAt}`,
    '---',
    '# Personal loop — walk order',
    '',
    '> Generated by `scripts/personal-loop/order.ts status`. Do not hand-edit; status lives in each item note.',
    '',
    '| # | col | lane | item | status |',
    '|---|---|---|---|---|',
    ...snap.items.map(
      (it, i) => `| ${it.n} | ${it.column} | ${it.laneRank} | [[items/${itemSlug(it.catalogId, it.step)}\\|${it.catalogId} · ${it.step}]] | ${glyph[statuses[i]]} ${statuses[i]} |`,
    ),
    '',
  ];
  writeFileSync(join(dir, 'order.md'), lines.join('\n'));
}

function main() {
  const cmd = process.argv[2] ?? 'status';
  mkdirSync(join(dir, 'items'), { recursive: true });

  if (cmd === 'snapshot') {
    const snap: Snapshot = { takenAt: new Date().toISOString(), items: columnMajorOrder(loadLanes()) };
    writeFileSync(orderPath, JSON.stringify(snap, null, 2));
    writeOrderMd(snap, snap.items.map(statusOf));
    process.stdout.write(`Snapshot: ${snap.items.length} items across ${Math.max(0, ...snap.items.map((i) => i.laneRank))} pipelines → ${orderPath}\n`);
    return;
  }

  const snap = readSnapshot();
  const statuses = snap.items.map(statusOf);

  if (cmd === 'next') {
    const i = statuses.findIndex((s) => OPEN.has(s));
    const next = i >= 0 ? { ...snap.items[i], status: statuses[i], slug: itemSlug(snap.items[i].catalogId, snap.items[i].step), of: snap.items.length } : null;
    process.stdout.write(JSON.stringify(next, null, 2) + '\n');
    return;
  }

  if (cmd === 'status') {
    writeOrderMd(snap, statuses);
    const count = (s: ItemStatus) => statuses.filter((x) => x === s).length;
    const i = statuses.findIndex((s) => OPEN.has(s));
    process.stdout.write(
      [
        `Snapshot ${snap.takenAt} · ${snap.items.length} items`,
        `  done ${count('done')} · skipped ${count('skipped')} · parked ${count('parked')} · in-progress ${count('in-progress')} · todo ${count('todo')}`,
        i >= 0 ? `  next #${snap.items[i].n} (col ${snap.items[i].column}): ${snap.items[i].catalogId} · ${snap.items[i].step}` : '  walk complete',
      ].join('\n') + '\n',
    );
    return;
  }

  process.stderr.write(`Unknown command "${cmd}" — use snapshot | next | status.\n`);
  process.exit(2);
}

main();
