import { cppFloat } from '@/lib/genome/codegen';
import type { CraftedAffix, ItemBase } from './data';
import { buildAffixName, computePowerBudget } from './data';
import { scaledMagnitude } from './craftingKernel';

/**
 * Generate UE5 C++ code for a pre-rolled item instance at `itemLevel` (the
 * workbench slider, the same level the budget and the inject use). Magnitudes
 * go through the kernel's `scaledMagnitude` and every float literal through the
 * shared `cppFloat`, so the export carries exactly what `/api/ue5-inject-item` sends.
 */
export function generateExportCode(base: ItemBase, affixes: CraftedAffix[], itemLevel: number): string {
  const budget = computePowerBudget(affixes, itemLevel);
  const lines = [
    '// =====================================================',
    '// Pre-rolled ItemInstance -- Generated by PoF Workbench',
    `// ${new Date().toISOString()}`,
    '// =====================================================',
    '',
    `// Base: ${base.name} (${base.type}, ${base.rarity}, Level ${itemLevel})`,
    `// Full Name: "${buildAffixName(base.name, affixes)}"`,
    `// Total Power: ${budget.total.toFixed(1)}`,
    '',
    '// Create item instance in C++:',
    'UARPGItemInstance* Item = NewObject<UARPGItemInstance>(this);',
    `Item->Definition = LoadObject<UARPGItemDefinition>(nullptr, TEXT("/Game/Items/DA_${base.name.replace(/\s+/g, '_')}"));`,
    `Item->ItemLevel = ${Math.round(itemLevel)};`,
    `Item->StackCount = 1;`,
    '',
    '// Pre-roll affixes:',
    `Item->Affixes.Reserve(${affixes.length});`,
    '',
  ];

  for (const a of affixes) {
    lines.push('{');
    lines.push('\tFItemAffix Affix;');
    lines.push(`\tAffix.AffixTag = FGameplayTag::RequestGameplayTag(FName("${a.tag}"));`);
    lines.push(`\tAffix.DisplayName = FText::FromString(TEXT("${a.displayName}"));`);
    lines.push(`\tAffix.Magnitude = ${cppFloat(scaledMagnitude(a, itemLevel))};`);
    lines.push(`\tAffix.bIsPrefix = ${a.bIsPrefix ? 'true' : 'false'};`);
    lines.push(`\t// Effect: GE_${a.stat.replace(/[^a-zA-Z]/g, '')}`);
    lines.push('\tItem->Affixes.Add(Affix);');
    lines.push('}');
    lines.push('');
  }

  lines.push(`// Item power budget: Offense=${budget.offense.toFixed(0)} Defense=${budget.defense.toFixed(0)} Utility=${budget.utility.toFixed(0)}`);

  return lines.join('\n');
}
