// ══════════════════════════════════════════════════════════════════════
// UMG HUD Theme Configuration — generated by PoF HUD Theme Editor
// Copy these values into your UE5 C++ UPROPERTY defaults or Blueprint.
// ══════════════════════════════════════════════════════════════════════

// ── ARPGHUDWidget — Player Health Bar ──────────────────────────────
UPROPERTY(EditAnywhere, Category = "HUD|Health")
FLinearColor HealthBarColor = FLinearColor(0.10f, 0.80f, 0.10f, 1.00f);

UPROPERTY(EditAnywhere, Category = "HUD|Health")
FLinearColor LowHealthColor = FLinearColor(0.90f, 0.10f, 0.10f, 1.00f);

UPROPERTY(EditAnywhere, Category = "HUD|Health")
float LowHealthThreshold = 0.25f;

UPROPERTY(EditAnywhere, Category = "HUD|Health")
float LowHealthPulseSpeed = 2.0f;

// ── ARPGHUDWidget — Mana Bar ──────────────────────────────────────
UPROPERTY(EditAnywhere, Category = "HUD|Mana")
FLinearColor ManaBarColor = FLinearColor(0.20f, 0.30f, 1.00f, 1.00f);

// ── EnemyHealthBarWidget — Enemy HP Bar ────────────────────────────
UPROPERTY(EditAnywhere, Category = "EnemyHP")
FLinearColor BarColor = FLinearColor(0.80f, 0.10f, 0.10f, 1.00f);

UPROPERTY(EditAnywhere, Category = "EnemyHP")
float BarInterpSpeed = 10.0f;

UPROPERTY(EditAnywhere, Category = "EnemyHP|Fade")
float FadeInDuration = 0.20f;

UPROPERTY(EditAnywhere, Category = "EnemyHP|Fade")
float FadeOutDuration = 0.50f;

UPROPERTY(EditAnywhere, Category = "EnemyHP|Fade")
float FadeOutDelay = 3.0f;

// ── DamageNumberWidget — Floating Damage Numbers ───────────────────
UPROPERTY(EditAnywhere, Category = "DamageNumbers|Colors")
FLinearColor PhysicalColor = FLinearColor(1.00f, 1.00f, 1.00f, 1.00f);

UPROPERTY(EditAnywhere, Category = "DamageNumbers|Colors")
FLinearColor FireColor = FLinearColor(1.00f, 0.30f, 0.10f, 1.00f);

UPROPERTY(EditAnywhere, Category = "DamageNumbers|Colors")
FLinearColor IceColor = FLinearColor(0.30f, 0.60f, 1.00f, 1.00f);

UPROPERTY(EditAnywhere, Category = "DamageNumbers|Colors")
FLinearColor LightningColor = FLinearColor(1.00f, 1.00f, 0.20f, 1.00f);

UPROPERTY(EditAnywhere, Category = "DamageNumbers|Colors")
FLinearColor HealColor = FLinearColor(0.20f, 1.00f, 0.30f, 1.00f);

UPROPERTY(EditAnywhere, Category = "DamageNumbers|Font")
float NormalFontSize = 18.0f;

UPROPERTY(EditAnywhere, Category = "DamageNumbers|Font")
float CritFontSize = 26.0f;

UPROPERTY(EditAnywhere, Category = "DamageNumbers|Animation")
float FloatDistance = 80.0f;

UPROPERTY(EditAnywhere, Category = "DamageNumbers|Animation")
float HorizontalSpread = 30.0f;

UPROPERTY(EditAnywhere, Category = "DamageNumbers|Animation")
float DamageLifetime = 1.00f;