import { describe, it, expect, afterEach, beforeEach, vi } from 'vitest';
import { render, cleanup, waitFor } from '@testing-library/react';

vi.mock('@/components/ui/CodeViewer', () => ({
  CodeViewer: ({ code, fileName }: { code: string; fileName: string }) =>
    <pre data-testid="code-viewer" data-filename={fileName}>{code}</pre>,
}));
vi.mock('sonner', () => ({ toast: { success: vi.fn(), error: vi.fn() } }));

import { HarnessGuideViewer } from '@/components/harness/HarnessGuideViewer';

const SAMPLE_MD = `# How to Build Demo

> Generated by Harness | 2026-01-01 | 3 iterations
> Total build time: 12min

## Prerequisites

- UE5 5.7 installed
- PoF app running

---

### Phase 1: Combat
**Module:** \`arpg-combat\`
**Duration:** 4.2min

**What Gets Built:**

- A new GA_ class
- A montage hookup

\`\`\`cpp
UCLASS()
class UGA_Demo : public UARPGGameplayAbility {};
\`\`\`
`;

const originalFetch = global.fetch;

beforeEach(() => {
  global.fetch = vi.fn(async (input: RequestInfo | URL) => {
    const url = typeof input === 'string' ? input : input.toString();
    if (url.includes('/api/harness?action=guide')) {
      return new Response(JSON.stringify({ success: true, data: { guide: { title: 'Demo', totalIterations: 3 }, markdown: SAMPLE_MD } }), { status: 200 });
    }
    return new Response('not found', { status: 404 });
  }) as unknown as typeof fetch;
});
afterEach(() => { global.fetch = originalFetch; cleanup(); });

describe('HarnessGuideViewer', () => {
  it('renders the title, phase header, prerequisites list, and a CodeViewer for fenced code', async () => {
    const { container } = render(<HarnessGuideViewer />);
    await waitFor(() => {
      expect(container.textContent).toContain('How to Build Demo');
    });
    // Phase rail entry uses the phase number.
    expect(container.querySelector('a[href="#phase-1"]')).toBeTruthy();
    // Phase block renders its label + duration chip.
    expect(container.textContent).toContain('Combat');
    expect(container.textContent).toContain('4.2min');
    // List renders the prerequisites.
    expect(container.textContent).toContain('UE5 5.7 installed');
    // Code block delegated to the Shiki CodeViewer mock.
    const cv = container.querySelector('[data-testid="code-viewer"]');
    expect(cv?.textContent).toContain('class UGA_Demo');
  });
});
