import { LEVEL_REWARDS } from '../progression-data';
import type { ProgressionRow } from './types';

/* ── Data Table Generation ─────────────────────────────────────────────────── */

export function generateProgressionTable(
  maxLevel: number,
  baseXp: number,
  exponent: number,
  hpPerLvl: number,
  manaPerLvl: number,
  attrPointsPerLvl: number,
  levelOverrides: Map<number, Partial<{ xpRequired: number; hpBonus: number; manaBonus: number }>>,
): ProgressionRow[] {
  const rows: ProgressionRow[] = [];
  let xpTotal = 0;

  for (let lvl = 1; lvl <= maxLevel; lvl++) {
    const override = levelOverrides.get(lvl);
    const xpRequired = override?.xpRequired ?? Math.floor(baseXp * Math.pow(lvl, exponent));
    xpTotal += xpRequired;
    const hpBonus = override?.hpBonus ?? hpPerLvl;
    const manaBonus = override?.manaBonus ?? manaPerLvl;

    const reward = LEVEL_REWARDS.find(r => r.level === lvl);

    rows.push({
      level: lvl,
      xpRequired,
      xpTotal,
      hpBonus,
      manaBonus,
      attrPoints: attrPointsPerLvl,
      unlockReward: reward ? `${reward.name} (${reward.type})` : '',
    });
  }
  return rows;
}

export function progressionToCSV(rows: ProgressionRow[]): string {
  const header = 'Level,XPRequired,XPTotal,HPBonus,ManaBonus,AttrPoints,UnlockReward';
  const lines = rows.map(r =>
    `${r.level},${r.xpRequired},${r.xpTotal},${r.hpBonus},${r.manaBonus},${r.attrPoints},"${r.unlockReward}"`
  );
  return [header, ...lines].join('\n');
}

export function progressionToUE5Struct(): string {
  return `#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "FProgressionCurveRow.generated.h"

/**
 * Data Table row for level progression.
 * Import the CSV generated by PoF web tool as a UDataTable
 * with this row struct. Replaces hardcoded CalculateXPForLevel().
 *
 * Generated by PoF XP Curve Table Generator.
 */
USTRUCT(BlueprintType)
struct POF_API FProgressionCurveRow : public FTableRowBase
{
\tGENERATED_BODY()

\t/** XP required to reach this level from the previous one. */
\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Progression")
\tint32 XPRequired = 0;

\t/** Cumulative XP needed to reach this level from level 1. */
\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Progression")
\tint32 XPTotal = 0;

\t/** HP bonus granted on reaching this level. */
\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Progression")
\tfloat HPBonus = 10.f;

\t/** Mana bonus granted on reaching this level. */
\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Progression")
\tfloat ManaBonus = 5.f;

\t/** Attribute points awarded at this level. */
\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Progression")
\tint32 AttrPoints = 3;

\t/** Unlock reward name (ability, passive, milestone, etc.). Empty if none. */
\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Progression")
\tFString UnlockReward;
};`;
}

export function progressionToUE5Loader(): string {
  return `// Replace CalculateXPForLevel() in ARPGPlayerCharacter with data table lookup.
// Add to ARPGPlayerCharacter.h:
//
//   UPROPERTY(EditDefaultsOnly, Category = "Progression")
//   TObjectPtr<UDataTable> ProgressionTable;
//
// Then replace the formula-based calculation:

float AARPGPlayerCharacter::GetXPForLevel(int32 Level) const
{
\tif (!ProgressionTable) return 100.f * FMath::Pow(Level, 1.5f); // fallback

\tconst FString RowName = FString::Printf(TEXT("%d"), Level);
\tconst FProgressionCurveRow* Row = ProgressionTable->FindRow<FProgressionCurveRow>(
\t\tFName(*RowName), TEXT("GetXPForLevel"));

\treturn Row ? static_cast<float>(Row->XPRequired) : 100.f * FMath::Pow(Level, 1.5f);
}

void AARPGPlayerCharacter::LevelUp()
{
\tPlayerLevel++;

\tif (ProgressionTable)
\t{
\t\tconst FString RowName = FString::Printf(TEXT("%d"), PlayerLevel);
\t\tif (const FProgressionCurveRow* Row = ProgressionTable->FindRow<FProgressionCurveRow>(
\t\t\tFName(*RowName), TEXT("LevelUp")))
\t\t{
\t\t\tMaxHealth += Row->HPBonus;
\t\t\tHealth = MaxHealth;
\t\t\tMaxMana += Row->ManaBonus;
\t\t\tMana = MaxMana;
\t\t\tUnspentAttributePoints += Row->AttrPoints;
\t\t\tExperienceToNextLevel = Row->XPRequired;
\t\t}
\t}
\telse
\t{
\t\t// Legacy formula fallback
\t\tMaxHealth += HealthPerLevel;
\t\tHealth = MaxHealth;
\t\tMaxMana += ManaPerLevel;
\t\tMana = MaxMana;
\t\tUnspentAttributePoints += AttributePointsPerLevel;
\t\tExperienceToNextLevel = CalculateXPForLevel(PlayerLevel);
\t}

\tExperience = 0.f;
\tOnPlayerLevelUp.Broadcast(PlayerLevel);
\tOnAttributePointsChanged.Broadcast(UnspentAttributePoints);
}`;
}
