// AUTO-GENERATED by scripts/gen-pipeline-registry.mjs — do not edit by hand.
// Importing this barrel triggers each pipeline file's self-registration side-effect.
import './bestiary';
import './currency';
import './icon-sets';
import './status-effect';
export {};
