'use client';

import { Copy } from 'lucide-react';
import { BlueprintPanel, SectionHeader } from '@/components/modules/core-engine/unique-tabs/_design';
import type { ItemGenome } from '@/types/item-genome';
import { ACCENT } from './data';

/* ── UE5 C++ Code Generation Preview ───────────────────────────────────── */

export function CodePreview({ selected }: { selected: ItemGenome }) {
  return (
    <BlueprintPanel color={ACCENT} className="p-3 space-y-3">
      <SectionHeader icon={Copy} label="UE5 DNA Struct Preview" color={ACCENT} />
      <pre className="text-xs font-mono text-text-muted leading-relaxed bg-surface-deep p-2 rounded-md overflow-x-auto custom-scrollbar whitespace-pre">
{`// Auto-generated by PoF Item DNA System
// Genome: ${selected.name} v${selected.version}

USTRUCT(BlueprintType)
struct FItemGenomeDNA
{
\tGENERATED_BODY()

\t/** Trait axis weights (0-1) biasing affix rolls */
\tUPROPERTY(EditAnywhere, BlueprintReadWrite)
\tfloat OffensiveWeight = ${selected.traits.find((t) => t.axis === 'offensive')?.weight.toFixed(2) ?? '0.25'}f;

\tUPROPERTY(EditAnywhere, BlueprintReadWrite)
\tfloat DefensiveWeight = ${selected.traits.find((t) => t.axis === 'defensive')?.weight.toFixed(2) ?? '0.25'}f;

\tUPROPERTY(EditAnywhere, BlueprintReadWrite)
\tfloat UtilityWeight = ${selected.traits.find((t) => t.axis === 'utility')?.weight.toFixed(2) ?? '0.25'}f;

\tUPROPERTY(EditAnywhere, BlueprintReadWrite)
\tfloat EconomicWeight = ${selected.traits.find((t) => t.axis === 'economic')?.weight.toFixed(2) ?? '0.25'}f;

\t/** Mutation rate (0-1) for off-type affix chance */
\tUPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(ClampMin="0", ClampMax="1"))
\tfloat MutationRate = ${selected.mutation.mutationRate.toFixed(2)}f;

\tUPROPERTY(EditAnywhere, BlueprintReadWrite)
\tint32 MaxMutations = ${selected.mutation.maxMutations};

\tUPROPERTY(EditAnywhere, BlueprintReadWrite)
\tbool bWildMutation = ${selected.mutation.wildMutation ? 'true' : 'false'};
};`}
      </pre>
    </BlueprintPanel>
  );
}
