import type { CharacterGenome } from '@/types/character-genome';

/* ── UE5 Code Generation ───────────────────────────────────────────────── */

export function generateSubclassHeader(g: CharacterGenome): string {
  const className = `AARPG${g.name.replace(/\s+/g, '')}Character`;
  return `// Auto-generated by PoF Character Genome System
// Genome: ${g.name} v${g.version} \u2014 ${g.description}
// Author: ${g.author} | ${g.updatedAt}

#pragma once

#include "CoreMinimal.h"
#include "Character/ARPGCharacterBase.h"
#include "${className}.generated.h"

UCLASS()
class POF_API ${className} : public AARPGCharacterBase
{
\tGENERATED_BODY()

public:
\t${className}();

protected:
\tvirtual void BeginPlay() override;
\tvirtual void InitializeAttributes() override;
};`;
}

export function generateSubclassCpp(g: CharacterGenome): string {
  const className = `AARPG${g.name.replace(/\s+/g, '')}Character`;
  return `// Auto-generated by PoF Character Genome System
#include "${className}.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Camera/CameraComponent.h"
#include "GameFramework/SpringArmComponent.h"

${className}::${className}()
{
\t// \u2500\u2500 Movement Profile \u2500\u2500
\tGetCharacterMovement()->MaxWalkSpeed = ${g.movement.maxWalkSpeed}.f;
\tMaxSprintSpeed = ${g.movement.maxSprintSpeed}.f;
\tGetCharacterMovement()->MaxAcceleration = ${g.movement.acceleration}.f;
\tGetCharacterMovement()->BrakingDecelerationWalking = ${g.movement.deceleration}.f;
\tGetCharacterMovement()->RotationRate = FRotator(0.f, ${g.movement.turnRate}.f, 0.f);
\tGetCharacterMovement()->AirControl = ${g.movement.airControl}f;
\tGetCharacterMovement()->JumpZVelocity = ${g.movement.jumpZVelocity}.f;
\tGetCharacterMovement()->GravityScale = ${g.movement.gravityScale}f;

\t// \u2500\u2500 Combat Profile \u2500\u2500
\tBaseDamage = ${g.combat.baseDamage}.f;
\tAttackSpeed = ${g.combat.attackSpeed}f;
\tComboWindowMs = ${g.combat.comboWindowMs}.f;
\tHitReactionDuration = ${g.combat.hitReactionDuration}f;
\tCritChance = ${g.combat.critChance}f;
\tCritMultiplier = ${g.combat.critMultiplier}f;
\tAttackRange = ${g.combat.attackRange}.f;
\tCleaveAngle = ${g.combat.cleaveAngle}.f;

\t// \u2500\u2500 Dodge Profile \u2500\u2500
\tDodgeDistance = ${g.dodge.distance}.f;
\tDodgeDuration = ${g.dodge.duration}f;
\tIFrameStart = ${g.dodge.iFrameStart}f;
\tIFrameDuration = ${g.dodge.iFrameDuration}f;
\tDodgeCooldown = ${g.dodge.cooldown}f;
\tDodgeStaminaCost = ${g.dodge.staminaCost}.f;

\t// \u2500\u2500 Camera Profile \u2500\u2500
\tif (CameraBoom)
\t{
\t\tCameraBoom->TargetArmLength = ${g.camera.armLength}.f;
\t\tCameraBoom->CameraLagSpeed = ${g.camera.lagSpeed}f;
\t\tCameraBoom->SocketOffset = FVector(0.f, 0.f, ${g.camera.socketOffsetZ}.f);
\t}
\tBaseFOV = ${g.camera.fovBase}.f;
\tSprintFOVOffset = ${g.camera.fovSprintOffset}.f;
}

void ${className}::BeginPlay()
{
\tSuper::BeginPlay();
}

void ${className}::InitializeAttributes()
{
\tSuper::InitializeAttributes();
\t// Attribute init values set via DataTable \u2014 see generated AttributeInitTable
}`;
}

export function generateAttributeInitTable(g: CharacterGenome): string {
  const rows = [
    `${g.name}.HP,${g.attributes.baseHP},${g.attributes.hpPerLevel}`,
    `${g.name}.Stamina,${g.attributes.baseStamina},${g.attributes.staminaPerLevel}`,
    `${g.name}.Mana,${g.attributes.baseMana},${g.attributes.manaPerLevel}`,
    `${g.name}.Armor,${g.attributes.baseArmor},${g.attributes.armorPerLevel}`,
    `${g.name}.StaminaRegen,${g.attributes.staminaRegenPerSec},0`,
    `${g.name}.ManaRegen,${g.attributes.manaRegenPerSec},0`,
  ];
  return `RowName,BaseValue,ScalingPerLevel\n${rows.join('\n')}`;
}
