/**
 * The `diablo1` canon profile — Diablo I (1996)'s world and art direction, for the /diablo
 * replication loop (W01, operator decision D5). WORLD + STYLE ONLY: no balance thresholds — every
 * PoF balance law is deliberately NOT inherited (see the vault's W01 note for the full conflict list).
 *
 * Drafted by gpt-6-astra (codex task cx-002, visual/design tier) from public references, reviewed by
 * the overseer and adopted with ONE edit: `d1-world` no longer names PoF's own lore in its exclusion list
 * (an image model cannot know what "post-Sundering symbols" are, and naming what to avoid invites it). Its own uncertainties (exact palettes, Hell's appearance,
 * costume details — it could not visually inspect screenshots) and each rule's CHECKABLE review
 * criterion live in the Obsidian vault (Diablo/Waves/W01-…), not here: they are review material for
 * W02's judge, not text for a producer. Citation URLs are carried as `refs`.
 *
 * This file is part of the reference-replication exercise and is deleted with it.
 */
import type { ProjectRule } from '../types';
import { DIABLO1_LOCATION_LAWS } from '@/lib/catalog/reference/locationSpecsData';
import { DIABLO1_CURRENCY_LAWS } from '@/lib/catalog/reference/currencySpecsData';
import { DIABLO1_ENCOUNTER_LAWS } from '@/lib/catalog/reference/encounterSpecsData';
import { DIABLO1_LOOT_LAWS } from '@/lib/catalog/reference/lootSpecsData';
import { DIABLO1_MOVEMENT_LAWS } from '@/lib/catalog/reference/movementSpecsData';
import { DIABLO1_PORT_LAWS } from '@/lib/catalog/reference/portQualificationsData';
import { DIABLO1_OBJECT_LAWS } from '@/lib/catalog/reference/objectSpecsData';
import { DIABLO1_MISSILE_LAWS } from '@/lib/catalog/reference/missileSpecsData';
import { DIABLO1_SPELL_LAWS } from '@/lib/catalog/reference/spellSpecsData';
import { DIABLO1_STATE_GRAPH_LAWS } from '@/lib/catalog/reference/stateGraphSpecsData';
import { DIABLO1_STATUS_LAWS } from '@/lib/catalog/reference/statusSpecsData';
import { DIABLO1_STORE_LAWS } from '@/lib/catalog/reference/storeSpecsData';

/** PoF rules that are world-neutral ENGINEERING contracts, adopted unchanged under this profile. */
export const DIABLO1_INHERITS_POF: readonly string[] = [
  "proj-naming",
  "proj-sot",
  "proj-links",
  "proj-quality",
  "proj-hud-binding",
  "quest-reward-binding",
  "char-config-not-cpp",
  "input-remap-conflict",
  "input-a11y",
  "tutorial-telemetry",
  "arpg-affix-is-ge",
  "arpg-wiring-contract",
  "screen-flow-nav-contract",
];

export const DIABLO1_CANON: readonly ProjectRule[] = [
  // ── LAWS derived from the reference (W02 onward). Balance numbers come from the engine or the tables,
  //    never from PoF's canon; a checker or seeder PARSES them from these bodies (one statement per law).
  ...DIABLO1_ENCOUNTER_LAWS,
  ...DIABLO1_STATE_GRAPH_LAWS,
  ...DIABLO1_CURRENCY_LAWS,
  ...DIABLO1_MOVEMENT_LAWS,
  ...DIABLO1_PORT_LAWS,
  { id: 'd1-resistance-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Monster resistance law (engine-derived)',
    body: "Monster resistance, derived from the engine: a RESIST flag for an element cuts that element's damage to one quarter, a 75% reduction; an IMMUNE flag means the hit does not land, a 100% reduction. Elements are magic, fire and lightning; the base game has no cold or chaos damage. There is no scale between: a monster is normal (0%), resistant (75%) or immune (100%) to each element.",
    refs: ["https://github.com/diasurgical/devilutionX/blob/4138a82/Source/missiles.cpp (MonsterMHit: resist -> dam >>= 2; isImmune -> no hit)", "https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (Monster::isResistant / isImmune)"] },
  { id: 'd1-timing-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Game time and movement law (engine-derived)',
    body: "Game time, derived from the engine: the simulation advances 20 ticks per second and every monster runs its AI on every tick, except that a SEARCH monster whose path planning starts a step skips its routine that tick. A monster walk moves one tile and lasts the walk animation's frames plus 1 tick; a hero walk starts one frame earlier. An attack lasts its attack animation's frames and lands on its action frame.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/diablo.cpp (gnTickDelay = 50 ms)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (ProcessMonsters -> AiProc every tick; MonsterWalk moves one tile at the last frame; walk anim -1 skipped frame)'] },
  { id: 'd1-hero-attack-timing-law', profile: 'diablo1', category: 'game', scope: 'characters', title: 'Attack timing by class and weapon',
    body: 'Hero attack timing, derived from the engine: usable weapon and shield choose one of nine weapon graphics, then the hero class supplies its frame count and contact marker. Each frame costs one game tick; contact or bow release occurs one frame before the one-based marker. Quick, Fast, Faster and Fastest effects skip frames before contact. Base speed belongs to class and graphic, not the item.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/items.cpp#L2674-L2704', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp#L174-L228', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp#L2234-L2285'] },
  { id: 'd1-hero-casting-timing-law', profile: 'diablo1', category: 'game', scope: 'characters', title: 'Casting timing',
    body: 'Hero casting timing, derived from the engine: fire, lightning and magic casting graphics all use the caster class\'s frame count and release marker. Every frame costs one game tick, no casting frames are skipped, the spell is released at the marker, and the full cast ends on the last frame. Attack-speed effects do not shorten casting.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp#L236-L277', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp#L1007-L1025', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp#L2288-L2290'] },
  { id: 'd1-hero-block-timing-law', profile: 'diablo1', category: 'game', scope: 'characters', title: 'Block timing',
    body: 'Hero block timing, derived from the engine: the class table supplies the frame count and every frame costs three game ticks. The final frame omits the other frames\' two extra delay ticks. Fast Block skips all but the final two frames, retaining a two-frame sequence. The class table has no separate block action marker.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp#L951-L959', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp#L2605-L2623', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/engine/animationinfo.cpp#L139-L157'] },
  { id: 'd1-class-skills-law', profile: 'diablo1', category: 'game', scope: 'characters', title: 'Class skills',
    body: 'Class skills, derived from the engine: Warrior Repair restores durability while permanently shrinking maximum durability; Rogue Disarm tests twice Dexterity minus five times dungeon level against a random roll and clears a successful trap; Sorcerer Recharge restores a spell staff while permanently shrinking maximum charges. These skills consume no mana.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/items.cpp#L4870-L4925', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp#L1071-L1092', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/spells.cpp#L147-L208'] },
  { id: 'd1-hero-speech-trigger-law', profile: 'diablo1', category: 'game', scope: 'characters', title: 'Hero speech triggers',
    body: 'Hero speech triggers, derived from the engine: hits, death, invalid spell attempts, first visits to selected dungeon depths, failed inventory actions, a quest interaction and repeated cow clicks request speech IDs. The hero class resolves each ID through its sounds table. Specific playback rejects missing sounds and suppresses one already playing; delayed playback queues it.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp#L1701-L1725', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp#L2639-L2705', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp#L3133-L3199', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp#L3441-L3482'] },
  { id: 'd1-ai-zombie-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Zombie AI law (engine-derived)',
    body: 'Zombie AI, derived from the engine: while standing on a visible tile it acts on (2 x intelligence + 10)% of decisions; adjacent actions attack, intermediate-range actions walk toward the target, and at long range, (2 x intelligence + 4) tiles or more, actions continue forward except that (2 x intelligence + 20)% choose a random direction.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (ZombieAi)'] },
  { id: 'd1-ai-skeleton-melee-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'SkeletonMelee AI law (engine-derived)',
    body: 'SkeletonMelee AI, derived from the engine: beside its target it attacks on (2 x intelligence + 20)% of decisions and otherwise pauses (10 - 2 x intelligence) plus 0-9 ticks, then attacks; away from its target it steps on (65 + 4 x intelligence)% of decisions and otherwise pauses (15 - 2 x intelligence) plus 0-9 ticks, then steps.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (SkeletonAi, AiDelay)'] },
  { id: 'd1-ai-skeleton-ranged-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'SkeletonRanged AI law (engine-derived)',
    body: 'SkeletonRanged AI, derived from the engine: it never approaches; below 4 tiles it retreats on (2 x intelligence + 13)% after standing over 20 ticks or (2 x intelligence + 63)% immediately after moving, and whenever it did not move it independently shoots on (2 x intelligence + 3)% if its line is clear, at any distance.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (SkeletonBowAi, StartRangedAttack MissileID::Arrow)'] },
  { id: 'd1-ai-fat-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Fat AI law (engine-derived)',
    body: 'Fat AI, derived from the engine: at range it approaches on (4 x intelligence + 20)% after standing over 20 ticks or (4 x intelligence + 70)% immediately after moving; when adjacent, one roll gives a normal attack below (4 x intelligence + 15)% and a special attack in the next 5 percentage points.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (OverlordAi)'] },
  { id: 'd1-ai-scavenger-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Scavenger AI law (engine-derived)',
    body: "Scavenger AI, derived from the engine: below half health it leaves its leash and spends up to ten standing AI calls seeking a corpse within a 4-tile square with a non-solid line, but a coin-flipped reverse scan never iterates, so half the searches find nothing; eating adds 1 health in vanilla until three-quarters health, while Hellfire adds one-eighth maximum health up to full; whenever healing does not act, SkeletonMelee behavior runs.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (ScavengerAi, ScavengerFindCorpse)'] },
  { id: 'd1-ai-rhino-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Rhino AI law (engine-derived)',
    body: 'Rhino AI, derived from the engine: at 5 or more tiles it usually circles and may charge on (2 x intelligence + 43)% when its route is clear; otherwise it approaches using (2 x intelligence + 33)% or the post-move (2 x intelligence + 83)% threshold, pauses 10-19 ticks on failure, and attacks adjacent targets on (2 x intelligence + 28)%.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (RhinoAi)'] },
  { id: 'd1-ai-goat-melee-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'GoatMelee AI law (engine-derived)',
    body: 'GoatMelee AI, derived from the engine: while fully alert and sharing its target\'s room it may circle from 4 or more tiles; otherwise it approaches on (2 x intelligence + 28)% after standing over 20 ticks or (2 x intelligence + 78)% immediately after moving, and attacks adjacent targets on (2 x intelligence + 23)%, using its special strike half the time below half health.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (AiAvoidance)'] },
  { id: 'd1-ai-ranged-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Shared ranged AI law (engine-derived)',
    body: "GoatRanged, Succubus and AcidUnique AI, derived from the engine: at full alert or while targeting a monster, GoatRanged and Succubus pause 0-19 ticks after RangedAttack; AcidUnique uses SpecialRangedAttack and misses that gate. Below 4 tiles they retreat on (10 x intelligence + 70)%, then shoot if still standing and line-clear. Their missiles are Arrow, Blood Star and Acid; partially alert player-targeters approach the last position.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (AiRanged, GetMissileType)'] },
  { id: 'd1-ai-fallen-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Fallen AI law (engine-derived)',
    body: 'Fallen AI, derived from the engine: it normally uses SkeletonMelee behavior; a nearby death makes it retreat for max(8 - level, 2) Stand decisions (blocked steps count), while a one-in-four war cry on the last standing frame heals (2 x intelligence + 2) internal health and orders Fallen within (2 x intelligence + 4) tiles to approach and force adjacent attacks for (30 x intelligence + 105) AI calls (ticks the routine runs), not decisions.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (FallenAi, M_FallenFear)'] },
  { id: 'd1-ai-ranged-avoidance-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Shared ranged-avoidance AI law (engine-derived)',
    body: "Magma, Storm, Acid and Diablo AI, derived from the engine: line-clear ranged chance is (5 x intelligence + 10)% at 3+ and (5 x intelligence + 5)% closer; Acid uses (2.5 x intelligence + 5)% and (2.5 x intelligence + 2.5)%. Line-clear adjacent melee is the next (5 x intelligence + 55)% band, or (7.5 x intelligence + 57.5)% for Acid; line-blocked it is below (10 x intelligence + 60)%. Failure pauses 5-14 ticks. Hellfire BoneDemon also uses it.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (AiRangedAvoidance, GetMissileType)'] },
  { id: 'd1-ai-skeleton-king-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'SkeletonKing AI law (engine-derived)',
    body: "SkeletonKing AI, derived from the engine: at full alert in target room it may circle at 3+ tiles. With multiplayer quests off, a clear-line roll below (4 x intelligence + 35)% there or 6% anywhere attempts a summon ahead; it also needs a free tile, capacity and skeleton type. At range it approaches below (intelligence + 25)% or post-move (intelligence + 75)%, else pauses 10-19 ticks; adjacency attacks below (intelligence + 20)% on the same roll.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (LeoricAi)'] },
  { id: 'd1-ai-bat-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Bat AI law (engine-derived)',
    body: "Bat AI, derived from the engine: it approaches on (intelligence + 13)% after standing over 20 ticks or (intelligence + 63)% immediately after moving, attacks adjacent targets on (4 x intelligence + 8)%, then makes two retreat decisions: RandomWalk first prefers away and then a random side, but either can fall back or fail. Gloom may charge from 5 or more tiles on (4 x intelligence + 33)%, and Familiar adds lightning when starting melee.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (BatAi)'] },
  { id: 'd1-ai-gargoyle-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Gargoyle AI law (engine-derived)',
    body: 'Gargoyle AI, derived from the engine: it remains a statue until an active target is closer than (intelligence + 2) tiles; below half health it retreats until at least that distance, then heals by maximum health divided by (16 x a random integer from 4 through 8), returning to statue form while healing; otherwise it uses GoatMelee behavior.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (GargoyleAi, MonsterHeal)'] },
  { id: 'd1-ai-butcher-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Butcher AI law (engine-derived)',
    body: "Butcher AI, derived from the engine: while alerted and standing it calls RandomWalk toward a non-adjacent target, so blocked routes may choose fallback directions or fail; it always begins a normal melee attack against an adjacent target. ButcherAi makes no decision roll and does not use intelligence, although RandomWalk itself makes fallback-order coin flips.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (ButcherAi)'] },
  { id: 'd1-ai-sneak-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Sneak AI law (engine-derived)',
    body: 'Sneak AI, derived from the engine: it fades in below (5 - intelligence) tiles and out at or beyond (6 - intelligence); after being hit it retreats for at most nine movement decisions, each counted when attempted even if blocked, or until (8 - intelligence) tiles away, while ordinary movement uses (4 x intelligence + 14)% or the post-move (4 x intelligence + 64)% threshold and adjacent attacks use (4 x intelligence + 10)%.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (SneakAi)'] },
  { id: 'd1-ai-fireman-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'FireMan AI law (engine-derived) (Hellfire)',
    body: 'FireMan AI, derived from the engine: this table-used identifier has no callable routine in the pinned engine because its dispatch entry is null, so it defines no movement, attack, pause or intelligence behavior and cannot safely enter ordinary monster processing.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (AiProc, ProcessMonsters)'] },
  { id: 'd1-ai-gharbad-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Gharbad AI law (engine-derived)',
    body: 'Gharbad AI, derived from the engine: quest dialogue keeps it non-combatant until the final conversation completes; once its goal becomes normal or circling it delegates to GoatMelee behavior, including intelligence-scaled movement, circling, melee and the below-half-health special strike.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (GharbadAi, AiAvoidance)'] },
  { id: 'd1-ai-golem-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Golem AI law (engine-derived)',
    body: "Golem AI, derived from the engine: it ignores table intelligence, updates a monster target, and attacks when both coordinate differences from that target's future tile are below 2. On waking an inactive target it alerts positive dMonster occupants in the 5-by-5 area around the golem, not the target. Otherwise it pathfinds, then uses RandomWalk with its owner's facing (including fallbacks), then tries all eight directions.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (GolumAi)'] },
  { id: 'd1-ai-zhar-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Zhar AI law (engine-derived)',
    body: 'Zhar AI, derived from the engine: quest dialogue gates combat until his encounter becomes hostile; while his goal is normal, retreating or circling he delegates to Counselor behavior, so intelligence selects and scales the same ranged spell, fade, retreat, flash and pause decisions.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (ZharAi, CounselorAi)'] },
  { id: 'd1-ai-snotspill-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Snotspill AI law (engine-derived)',
    body: 'Snotspill AI, derived from the engine: quest dialogue and the banner encounter gate combat; after the map-changing quest state is reached, normal or attack goals delegate to Fallen behavior (SkeletonMelee decisions, war cries, forced attacks) only while its tile is visible; it never takes the death-triggered Fallen retreat, which the engine grants to Fallen AI only.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (SnotSpilAi, FallenAi)'] },
  { id: 'd1-ai-snake-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Snake AI law (engine-derived)',
    body: 'Snake AI, derived from the engine: at exactly 2 tiles it charges along a clear route unless the previous action was a charge; otherwise it advances with a right, right, straight, left, left, straight drift on (65 + 2 x intelligence)% or after a pause, pausing (15 - intelligence) plus 0-9 ticks on failure; adjacent attacks use (intelligence + 20)% or are forced after a pause or charge.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (SnakeAi)'] },
  { id: 'd1-ai-counselor-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Counselor AI law (engine-derived)',
    body: "Counselor AI, derived from the engine: at range it casts on (5 x (intelligence + 10))% only with a clear line, selecting Firebolt, Charged Bolt, Lightning or Fireball for intelligence 0-3; failure independently fades into circling on 30%, else pauses (10 - 2 x intelligence) plus 0-9 ticks. Adjacent and wounded it fades for four retreat attempts; otherwise Flash is forced after Delay or rolls (2 x intelligence + 20)%, with that pause on failure.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (CounselorAi)'] },
  { id: 'd1-ai-mega-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Mega AI law (engine-derived)',
    body: "Mega AI, derived from the engine: at 5+ tiles it uses SkeletonMelee; closer, it may circle from 3+ tiles, and leaving that goal attempts Inferno only with a clear line. Inferno chance is 5 x (intelligence + 2)% at 3+ tiles or 5 x (intelligence + 1)% closer, also line-clear. Approach is (10 x intelligence + 50)% or post-move (10 x intelligence + 80)%. Adjacent, 10 x (intelligence + 4)% acts, choosing Inferno/melee equally; idle pauses 5-14 ticks.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (MegaAi)'] },
  { id: 'd1-ai-lazarus-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Lazarus AI law (engine-derived)',
    body: 'Lazarus AI, derived from the engine: single-player and multiplayer quest states gate his encounter differently; once his goal is normal, retreating or circling he delegates to Counselor behavior, except that this identifier ignores requested AI pauses, so failed actions can be reconsidered immediately.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (LazarusAi, CounselorAi, AiDelay)'] },
  { id: 'd1-ai-lazarus-succubus-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'LazarusSuccubus AI law (engine-derived)',
    body: "LazarusSuccubus AI, derived from the engine: single-player quest state prevents combat until its goal becomes normal; multiplayer initializes it normal. It then uses the shared ranged behavior, retreating below 4 tiles on (10 x intelligence + 70)%, firing a Blood Star whenever still standing with a clear line, and pausing 0-19 ticks after a shot.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (LazarusMinionAi, AiRanged)'] },
  { id: 'd1-ai-lachdanan-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Lachdanan AI law (engine-derived)',
    body: 'Lachdanan AI, derived from the engine: the routine only advances dialogue and quest state while standing; after the final speech finishes it marks the quest complete and kills Lachdanan, and it never delegates to a combat routine or makes movement, attack, pause or intelligence rolls.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (LachdananAi)'] },
  { id: 'd1-ai-warlord-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Warlord AI law (engine-derived)',
    body: 'Warlord AI, derived from the engine: quest dialogue keeps it non-combatant until the hostile speech finishes; after its goal becomes normal it delegates to SkeletonMelee behavior, using the same intelligence-scaled approach, adjacent attack and forced post-pause actions.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (WarlordAi, SkeletonAi)'] },
  { id: 'd1-ai-hork-demon-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'HorkDemon AI law (engine-derived) (Hellfire)',
    body: "HorkDemon AI, derived from the engine: from 5 or more tiles it usually circles; from 3 or more tiles a roll below (2 x intelligence + 43)% attempts to spawn ahead, but if space or capacity fails it idles rather than falling through. Otherwise a fresh roll approaches below (2 x intelligence + 33)% or the post-move (2 x intelligence + 83)%, else pauses 10-19 ticks; adjacent attacks use (2 x intelligence + 28)%.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (HorkDemonAi)'] },
  ...DIABLO1_LOCATION_LAWS,
  ...DIABLO1_LOOT_LAWS,
  ...DIABLO1_OBJECT_LAWS,
  ...DIABLO1_MISSILE_LAWS,
  ...DIABLO1_SPELL_LAWS,
  ...DIABLO1_STATUS_LAWS,
  ...DIABLO1_STORE_LAWS,
  { id: 'd1-difficulty-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Difficulty modes (engine-derived)',
    body: 'Difficulty: Normal keeps base stats and resistance. Nightmare adds 15 level, triples post-mode HP + 100, adds 50 armour and 85 to-hit, sets damage to 2 × (base + 2), XP to 2 × (base + 1000), and keeps normal resistance. Hell adds 30 level, quadruples HP + 200, adds 80 armour and 120 to-hit, sets damage to 4 × base + 6, XP to 4 × (base + 1000), and uses resistanceHell. Effective level gates eligible drop bases; affix level stays base.',
    refs: ['.reference/devilutionX/Source/monster.cpp (InitMonster)', '.reference/devilutionX/Source/monster.h (Monster::level, Monster::toHit, Monster::exp)', '.reference/devilutionX/Source/tables/monstdat.cpp (resistance and resistanceHell loaders)', '.reference/devilutionX/Source/items.cpp (SpawnItem, RndUItem)'] },
  { id: 'd1-spell-cast-law', profile: 'diablo1', category: 'game', scope: 'spellbook', title: 'Spell casting law (engine-derived)',
    body: "Spell casting, derived from the engine: ordinary spell missiles hit on clamp(Magic+class magic-to-hit-2*monster level,5,95)%; their distance counter remains 0, and every collision check rerolls. A cast uses one tick per class casting frame, releases on its action frame, and has no cooldown or passive mana regeneration. GetManaAmount handles Firebolt half reduction, both Heals, Resurrect, max-mana rows, zero floor, class adjustment, and minMana.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/missiles.cpp (MonsterMHit: GetMagicToHit - 2 x level - dist, clamp 5-95)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp (getAnimationFramesAndTicksPerFrame: spell 1 tick/frame; DoSpell casts at _pSFNum; ProcessPlayers: no mana regeneration)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/spells.cpp (GetManaAmount)'] },
  { id: 'd1-monster-missile-hit-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Monster missile hit law (engine-derived)',
    body: 'Monster missiles, derived from the engine: non-arrows hit when R(100) is below max(40+2*monster level-2*player level-2*distance,dungeon floor); arrows instead use monster to-hit, player armour, and distance. The floor is 10, or 20/25/30 on dungeon levels 14/15/16. Elemental resistance reduces damage; a standing or attacking player may block eligible missiles.',
    refs: ['.reference/devilutionX/Source/missiles.cpp:1067-1207'] },
  { id: 'd1-combat-melee-to-hit-law', profile: 'diablo1', category: 'game', scope: 'characters', title: 'Player melee to-hit law (engine-derived)',
    body: "Player melee to-hit, derived from the engine: base h=Dexterity/2+level+class melee to-hit+item to-hit. Vanilla uses h+armour-piercing-monster armour; Hellfire reduces armour by piercing, with an extra Barbarian melee reduction. Clamp to 5-95. Adjacent splash subtracts 30 above level 20, otherwise 2*(35-level). An unhittable target cannot be hit, while petrification makes the attack roll zero and therefore succeeds against the positive minimum.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp (PlrHitMonst)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.h (GetMeleeToHit)'] },
  { id: 'd1-combat-ranged-to-hit-law', profile: 'diablo1', category: 'game', scope: 'characters', title: 'Player ranged to-hit law (engine-derived)',
    body: "Player ranged to-hit, derived from the engine: base h=Dexterity+level+class ranged to-hit+item to-hit-distance squared/2. Vanilla uses h+armour-piercing-monster armour; Hellfire reduces armour by piercing. Clamp to 5-95; division truncates. An unhittable or immune target cannot be hit, while petrification makes the attack roll zero.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/missiles.cpp (MonsterMHit)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.h (GetRangedToHit)'] },
  { id: 'd1-combat-monster-melee-to-hit-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Monster melee to-hit law (engine-derived)',
    body: "Monster melee to-hit, derived from the engine: monster to-hit + 2 x (monster level - player level) + 30 - player armour, where armour is equipment + Dexterity / 5 and Hellfire flags can add 40 versus demons or 20 versus undead. Nightmare adds 85 to to-hit and 15 to level; Hell adds 120 and 30. The floor is 15%, rising to 20%, 25%, 30% on dungeon levels 14, 15, 16; there is no upper clamp. Magma/Storm make extra frame-specific attempts at +10/-20.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (MonsterAttackPlayer, PlayerMHit)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.h (Monster::toHit, Monster::level)'] },
  { id: 'd1-combat-monster-ranged-to-hit-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Monster ranged to-hit law (engine-derived)',
    body: "Monster ranged to-hit, derived from the engine: arrows use monster to-hit + 2 x (monster level - player level) + 30 - 2 x distance - player armour; every non-arrow uses 40 + 2 x monster level - 2 x player level - 2 x distance. Without a monster source, arrows use 100 - player armour / 2 - 2 x distance and non-arrows use 40. The floor is 10%, or 20%, 25%, 30% on dungeon levels 14, 15, 16; no upper clamp.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/missiles.cpp (PlayerMHit)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (MonsterRangedAttack)'] },
  { id: 'd1-combat-player-melee-damage-law', profile: 'diablo1', category: 'game', scope: 'characters', title: 'Player melee damage law (engine-derived)',
    body: "Player melee damage, derived from the engine: roll weapon minimum-maximum inclusive; add truncated roll x item damage% / 100, flat item damage, then class/weapon damageMod. A Critical Strike flag gives level% double damage. Swords favour animals and maces favour undead by half; the opposite target halves damage. Triple Demon Damage triples; then multiply by 64. Hellfire Devastation, Jester's, Peril, and adjacent-quarter branches also apply.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp (PlrHitMonst)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/items.cpp (CalcPlrItemVals)'] },
  { id: 'd1-combat-player-ranged-damage-law', profile: 'diablo1', category: 'game', scope: 'characters', title: 'Player ranged damage law (engine-derived)',
    body: 'Player ranged damage, derived from the engine: roll weapon minimum-maximum inclusive; add flat item damage plus truncated roll x item damage% / 100. Add the full class damage for a Rogue and half, truncated, for other classes. Triple Demon Damage triples against demons; arrows never use Critical Strike or sword/mace target modifiers. Multiply whole-point bounds by 64.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/missiles.cpp (MonsterMHit)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/items.cpp (CalcPlrItemVals)'] },
  { id: 'd1-combat-monster-damage-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Monster damage law (engine-derived)',
    body: "Monster damage, derived from the engine: Normal keeps each bound; Nightmare makes each 2 x (bound + 2); Hell makes each 4 x bound + 6. Melee rolls every fixed unit from minimum x 64 through maximum x 64; projectiles first roll whole points inclusively. Unshifted hits add the modifier x 64; shifted hits add it raw; both floor at 64. Special bounds transform likewise. Magma/Storm's -2/+4 affect only their extra frame-specific melee attempts.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (InitMonster, MonsterAttackPlayer, MonsterSpecialAttack)'] },
  { id: 'd1-combat-monster-hp-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Monster hit-point law (engine-derived)',
    body: "Monster hit points, derived from the engine: an ordinary monster rolls its inclusive minimum-maximum, while a unique uses its fixed unique maximum; multiply by 64. Single-player then halves that fixed-point value with a 64 (1 HP) floor, while multiplayer does not. Nightmare next triples HP and adds 100 x 64; Hell quadruples HP and adds 200 x 64, the same in vanilla single- and multiplayer. Hellfire single-player instead adds 50 x 64 or 100 x 64.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (InitMonster, PrepareUniqueMonst)'] },
  { id: 'd1-combat-monster-armour-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Monster armour law (engine-derived)',
    body: "Monster armour, derived from the engine: Normal keeps base armour; Nightmare adds 50 and Hell adds 80. A unique with zero custom armour retains that adjusted base; a nonzero custom armour replaces the base and receives the same difficulty bonus. Player melee and arrow to-hit subtract the result of CalculateArmorPierce, which can reduce that armour for Hellfire piercing and Barbarian melee.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (InitMonster, PrepareUniqueMonst)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp (PlrHitMonst)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/missiles.cpp (MonsterMHit)'] },
  { id: 'd1-combat-block-law', profile: 'diablo1', category: 'game', scope: 'characters', title: 'Block law (engine-derived)',
    body: "Block, derived from the engine: valid setups are a shield, or Monk staff/unarmed/eligible one-hand; only while standing/attacking. Monster melee/missile chance is clamp(Dexterity+class block+2*player level-2*monster level,0,100); traps omit levels. These roll block before hit; PvP missiles hit first. Shifted damage and acid puddles cannot block. Vanilla positive resistance skips monster/trap missile blocks; PvP resistance always does.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (MonsterAttackPlayer)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/missiles.cpp (PlayerMHit)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.h (GetBlockChance)'] },
  { id: 'd1-combat-player-resistance-law', profile: 'diablo1', category: 'game', scope: 'characters', title: 'Player resistance law (engine-derived)',
    body: "Player resistance, derived from the engine: sum item magic, fire and lightning resistance separately, add Natural Resistance's character level, subtract character level during Rage cooldown, then clamp each to 0-75%. Zero Resistance resets all three to 0 after other changes. Fire uses fire, lightning uses lightning, and magic or acid uses magic; physical uses 0. Damage becomes damage - truncated (damage x resistance / 100).",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/items.cpp (CalcPlrItemVals)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/missiles.cpp (PlayerMHit)'] },
  { id: 'd1-combat-hit-recovery-law', profile: 'diablo1', category: 'game', scope: 'characters', title: 'Hit recovery law (engine-derived)',
    body: 'Hit recovery, derived from the engine: a hero uses the class recovery-frame count at one tick per frame and starts when forced or whole-point damage reaches character level. A Barbarian instead requires level plus one quarter of level, rounded down. Fast, Faster and Fastest recovery skip one, two and three initial frames. A petrified monster can play its hit sound without animating.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp#L1833-L1835', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp#L2639-L2676', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp#L4355-L4393'] },
  { id: 'd1-combat-life-mana-law', profile: 'diablo1', category: 'game', scope: 'characters', title: 'Life and mana law (engine-derived)',
    body: "Life and mana, derived from the engine: base life = life adjustment + life per level x level + life per base Vitality x base Vitality; base mana substitutes the mana coefficients and base Magic. Item stats add ((bonus*coefficient)>>6)<<6; direct item life/mana is added. Maximum life clamps to 64..128000 and mana to 0..128000; current life may be 0. Level-up adds both per-level coefficients and refills life; No Mana skips only the mana refill.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp (Player::calculateBaseLife, Player::calculateBaseMana, NextPlrLevel)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/items.cpp (CalcPlrItemVals)'] },
  { id: 'd1-xp-award-law', profile: 'diablo1', category: 'game', scope: 'progression-curves', title: 'Experience award law (engine-derived)',
    body: 'Experience award, derived from the engine: Normal uses base XP; Nightmare uses 2 x (base XP + 1000); Hell uses 4 x (base XP + 1000); uniques double it. Divide by contributing players, then truncate share x (1 + (monster level - player level) / 10), at least 0. Multiplayer caps it at one twentieth of the next threshold and 200 x player level; total XP cannot pass the maximum threshold.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (Monster::exp, M_DoDeath)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp (AddPlrExperience, Player::_addExperience)'] },
  { id: 'd1-xp-curve-law', profile: 'diablo1', category: 'game', scope: 'progression-curves', title: 'Experience curve law (engine-derived)',
    body: 'Experience curve, derived from the engine: each numeric Level row stores its cumulative Experience at index Level - 1; missing levels are filled with 4294967295 and a literal MaxLevel row is skipped. Maximum level is the smaller of threshold count and 255. Level 0 reads 0; a valid positive level reads index min(level - 1, maximum level). Level repeatedly rises while total XP reaches its current threshold.',
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/tables/playerdat.cpp (ExperienceData::reload, setThresholdForLevel, getMaxLevel, getThreshold)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp (Player::_addExperience)'] },
  { id: 'd1-ai-awareness-law', profile: 'diablo1', category: 'game', scope: 'bestiary', title: 'Monster awareness law (engine-derived)',
    body: "Monster awareness, derived from the engine: any player's vision of its tile sets alertness to 255; unseen it decrements each tick except Diablo. Its target tile updates even unseen; its last-seen tile refreshes only while visible, and AIs choose between them. There is no aggro radius beyond sight and no leash to a spawn point. A leashed minion takes a more-alert leader minus 1 without a line check; rejoining within 4 tiles needs a non-solid line.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (ProcessMonsters: IsTileVisible -> activeForTicks = UINT8_MAX, else decrement; MT_DIABLO never decrements)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (GroupUnity / leader alertness sharing; reunite when WalkingDistance < 4 with a clear line)'] },
  { id: 'd1-dialogue-hub-law', profile: 'diablo1', category: 'game', scope: 'dialog-trees', title: 'Town conversation law (engine-derived)',
    body: "Town conversation, derived from the engine: each towner uses its own handler. Core service towners test quest branches in source order; a taken branch returns before their greeting/store menu, but it need not change quest state. Cows, the slain townsman and Hellfire quest towners do not use that menu. The hero never picks a reply; the only choice is which menu entry to open.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/towners.cpp (TalkToTowner; TalkTo* handlers: first match speaks, writes quest state, returns before StartStore)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/stores.cpp (StartStore: per-towner menu)'] },
  { id: 'd1-dialogue-topics-law', profile: 'diablo1', category: 'game', scope: 'dialog-trees', title: 'Talk topics and gossip law (engine-derived)',
    body: "Talk topics, derived from the engine: the Talk menu lists one topic per quest that is active, logged and has a line for this person in the quest-talk table, in quest order, plus one Gossip entry. The gossip line is rolled once from the person's gossip pool when the town is built, not per visit. Each line's own record decides whether it is voiced, scrolled, or both.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/stores.cpp (StartTalk: QUEST_ACTIVE && _qlog && GetTownerQuestDialog != TEXT_NONE, in Quests order; Gossip entry)', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/towners.cpp (InitTownerFromData: gossip = gossipTexts[GenerateRnd(n)])', 'https://github.com/diasurgical/devilutionX/blob/4138a82/Source/minitext.cpp (InitQTextMsg: scrlltxt / sfxnr per speech record)'] },
  { id: 'd1-dialogue-monster-talk-law', profile: 'diablo1', category: 'game', scope: 'dialog-trees', title: 'Talking monster law (engine-derived)',
    body: "Monster talk, derived from the engine: a unique monster with a line to say cannot be hit while it waits to speak or is speaking; talking to it plays the line with no reply menu. Its AI advances or ends talk when its tile leaves the local player's visibility, speech finishes, a quest changes or an item is handed over; the last line turns it hostile or removes it. Lazarus and the Warlord can start talking on their own.",
    refs: ['https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp (PrepareUniqueMonst, CanTalkToMonst, TalktoMonster, MonsterTalk, encounter AI routines)'] },
  { id: "d1-quest-scope-law", profile: 'diablo1', category: 'game', scope: 'quests', title: "Vanilla quest scope law (engine-derived) (engine-derived)",
    body: "Quest scope, derived from the engine: this specification covers the first 16 quests, from The Magic Rock through Archbishop Lazarus; Grave Matters, Farmer's Orchard, Little Girl, Wandering Trader, The Defiler, Na-Krul, Cornerstone of the World, and The Jersey's Jersey are Hellfire entries and are out of scope.",
    refs: ["https://github.com/diasurgical/devilutionX/blob/4138a82/Source/tables/questdat.hpp:74", "https://github.com/diasurgical/devilutionX/blob/4138a82/assets/txtdata/quests/questdat.tsv:2"] },
  { id: "d1-quest-lifecycle-law", profile: 'diablo1', category: 'game', scope: 'quests', title: "Quest lifecycle law (engine-derived) (engine-derived)",
    body: "Quest lifecycle, derived from the engine: every quest starts unavailable with both phase slots zero, its journal entry hidden, and its table metadata loaded; each vanilla single-player row is then initialized as selected, and quest-specific handlers can make it active or completed, while the two phase slots have no shared meaning.",
    refs: ["https://github.com/diasurgical/devilutionX/blob/4138a82/Source/quests.cpp:60", "https://github.com/diasurgical/devilutionX/blob/4138a82/Source/tables/questdat.hpp:62"] },
  { id: "d1-quest-journal-law", profile: 'diablo1', category: 'game', scope: 'quests', title: "Quest journal law (engine-derived) (engine-derived)",
    body: "Quest journal, derived from the engine: an active quest is listed only when its independent journal flag is set; every completed quest is listed whether or not that flag is set. Active entries come first and can replay their current speech, completed entries are nonselectable, and each block is sorted by its table order.",
    refs: ["https://github.com/diasurgical/devilutionX/blob/4138a82/Source/panels/quest_log.cpp:90", "https://github.com/diasurgical/devilutionX/blob/4138a82/Source/panels/quest_log.cpp:167"] },
  { id: "d1-quest-selection-law", profile: 'diablo1', category: 'game', scope: 'quests', title: "Quest pool selection law (engine-derived) (engine-derived)",
    body: "Quest selection, derived from the engine: a randomized single-player game uses the level-15 dungeon seed to disable one member of each pool—King/Poisoned Water; Butcher/Ogden/Gharbad; Blind/Magic Rock/Valor; Mushroom/Zhar/Anvil; Lachdanan/Warlord. The compatibility seed 988045466 disables none in the second pool; the table's random field is unused.",
    refs: ["https://github.com/diasurgical/devilutionX/blob/4138a82/Source/quests.cpp:91", "https://github.com/diasurgical/devilutionX/blob/4138a82/Source/quests.cpp:114", "https://github.com/diasurgical/devilutionX/blob/4138a82/Source/tables/questdat.cpp:45"] },
  { id: "d1-quest-placement-law", profile: 'diablo1', category: 'game', scope: 'quests', title: "Quest placement law (engine-derived) (engine-derived)",
    body: "Quest placement, derived from the engine: selected content is generated only on its configured dungeon floor. The Skeleton King, Chamber of Bone, Poisoned Water, and Lazarus entrances lead to separate maps 1, 2, 4, and 5; other quests remain on the normal floor. Stepping on an entrance enters its map, but Lazarus's entrance stays locked until its portal phase.",
    refs: ["https://github.com/diasurgical/devilutionX/blob/4138a82/Source/tables/questdat.cpp:64", "https://github.com/diasurgical/devilutionX/blob/4138a82/Source/levels/drlg_quests.cpp:89", "https://github.com/diasurgical/devilutionX/blob/4138a82/Source/quests.cpp:188", "https://github.com/diasurgical/devilutionX/blob/4138a82/Source/levels/setmaps.cpp:112"] },
  { id: "d1-quest-failure-law", profile: 'diablo1', category: 'game', scope: 'quests', title: "Quest failure law (engine-derived) (engine-derived)",
    body: "Quest failure, derived from the engine: vanilla quests have no failed or abandoned state and no scripted action changes an accepted quest to unavailable. Quest monsters that must talk cannot be hit while they still have dialogue; their scripts either make them hostile only when combat should begin, complete the quest before hostility, or remove the speaker after completion.",
    refs: ["https://github.com/diasurgical/devilutionX/blob/4138a82/Source/tables/questdat.hpp:62", "https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp:4962", "https://github.com/diasurgical/devilutionX/blob/4138a82/Source/player.cpp:1159"] },
  { id: "d1-quest-completion-law", profile: 'diablo1', category: 'game', scope: 'quests', title: "Quest completion law (engine-derived) (engine-derived)",
    body: "Quest completion, derived from the engine: there is no universal objective check; each quest-specific handler marks completion on its own event—boss death, item hand-in, a held-item conversation or pickup, final book use, the Poisoned Water survivor count, Lachdanan's final speech, or Diablo's death—and some rewards or epilogues are deliberately collected after that mark.",
    refs: ["https://github.com/diasurgical/devilutionX/blob/4138a82/Source/quests.cpp:175", "https://github.com/diasurgical/devilutionX/blob/4138a82/Source/quests.cpp:227", "https://github.com/diasurgical/devilutionX/blob/4138a82/Source/objects.cpp:1881", "https://github.com/diasurgical/devilutionX/blob/4138a82/Source/inv.cpp:993", "https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp:875", "https://github.com/diasurgical/devilutionX/blob/4138a82/Source/monster.cpp:2953"] },
  { id: "d1-world", profile: 'diablo1', category: "game", scope: "global", title: "Tristram and the corruption below",
    body: "Depict the medieval town of Tristram and the demonic corruption beneath its cathedral: church masonry, graves, hand tools, blades, books and occult shrines. Exclude firearms, machinery and later-series locations.",
    refs: ["https://hoffmeister.li/downloads/games/diablo_1/D1_manual_en.pdf"], },
  { id: "d1-tone", profile: 'diablo1', category: "game", scope: "global", title: "Personal-scale religious horror",
    body: "Stage personal-scale religious horror: isolated people, enclosing architecture, corpses, blood and violated sacred spaces. Heroes face danger in guarded working poses. Avoid victory parades, comic expressions, clean heroic pageantry and crowds posed like an army.", },
  { id: "d1-visual-identity", profile: 'diablo1', category: "art", scope: "global", title: "Prerendered volume at sprite resolution",
    body: "Match a 1996 prerendered sprite image: modeled volume reduced to coarse pixels, compact highlight clusters and stepped shadow ramps. Review gameplay at 640x480 before enlargement. No painterly brushwork, cartoon outlines, smooth vector surfaces, photographic pores or cinematic depth of field.", },
  { id: "d1-palette", profile: 'diablo1', category: "art", scope: "global", title: "Dark bases with selective strong color",
    body: "Use charcoal shadows, slate blue-gray stone, dirty brown earth, dull iron and aged bone as the base. Permit strong red, blue, green and gold on referenced creatures, gear, potions and magic; saturation is not reserved for rarity. For dungeon scenes, keep most non-emissive surfaces below middle gray.", },
  { id: "d1-lighting", profile: 'diablo1', category: "art", scope: "global", title: "Local visibility surrounded by darkness",
    body: "In dungeons, surround the hero with a local pool of visibility that falls through darker steps into black; torches, lava and spells create additional local light. Keep sprite volume legible without a universal sun direction. Avoid lifted black levels, broad bloom, cinematic rim lights and sunbeams through every room.", },
  { id: "d1-camera", profile: 'diablo1', category: "art", scope: "global", title: "Fixed diagonal gameplay projection",
    body: "For gameplay assets, use a fixed elevated diagonal view with parallel ground axes and a 2:1 diamond footprint. Show top surfaces and two sides without perspective convergence. Match the same projection for actors, props and floors; no horizon, vanishing point, camera roll or camera-facing portrait pose.", },
  { id: "d1-sprite-read", profile: 'diablo1', category: "art", scope: "global", title: "Directional silhouettes and stable feet",
    body: "Review actors at gameplay size with discrete eight-direction facing coverage, consistent scale and a stable foot pivot. Separate head, torso, weapon and feet through silhouette or value. Use short, distinct action poses; no motion-blur trails, smeared interpolation or dependence on facial microdetail.", },
  { id: "d1-materials", profile: 'diablo1', category: "art", scope: "global", title: "Coarse material cues and selective wear",
    body: "Describe stone with chipped edges and broad cracks, iron with dark faces and small bright edges, wood with coarse grain, and cloth with broad folds. Keep wear readable at sprite scale. Permit polished weapon highlights and jewels; avoid covering every material in identical rust, fine scratches or wet gloss.", },
  { id: "d1-monsters", profile: 'diablo1', category: "game", scope: "bestiary", title: "Anatomically distinct horror families",
    body: "Give each creature a recognizable anatomical family: exposed rib cage for skeletons, heavy slack flesh for zombies, hunched small demons, horned goat-headed humanoids, broad beasts or armored infernal fighters. Exaggerate the identifying mass or appendage. Avoid cute faces, generic armored soldiers and decorative antlers on every species.",
    refs: ["https://hoffmeister.li/downloads/games/diablo_1/D1_manual_en.pdf"], },
  { id: "d1-monster-variants", profile: 'diablo1', category: "art", scope: "bestiary", title: "Variants preserve family identity",
    body: "Within an established monster family, preserve anatomy, silhouette and action poses while varying its referenced color treatment. Named monsters retain their identifiable body plan. Do not invent rarity crowns, floating badges, extra armor tiers or obligatory multiphase boss silhouettes.", },
  { id: "d1-player-heroes", profile: 'diablo1', category: "game", scope: "global", title: "The three original mortal heroes",
    body: "Use the original three hero identities: a broad male Warrior, a lean female Rogue, and a male Sorcerer. Establish sword-and-shield, bow, and staff silhouettes respectively when no equipment override is specified. Keep them human-sized and mortal; exclude later classes, oversized shoulder armor, angel wings and permanent power auras.",
    refs: ["https://hoffmeister.li/downloads/games/diablo_1/D1_manual_en.pdf"], },
  { id: "d1-hero-equipment", profile: 'diablo1', category: "art", scope: "global", title: "Armor changes broad material masses",
    body: "For the requested equipment state, distinguish light clothing or leather, linked metal armor, and solid plate with broad material masses. Keep class stature and pose recognizable after an armor change. Weapons remain separable from the torso. Do not invent a new visible costume attachment for every numerical item modifier.", },
  { id: "d1-env-tristram", profile: 'diablo1', category: "art", scope: "global", title: "Tristram: a surviving, subdued village",
    body: "When depicting Tristram, use a sparsely populated, still-standing village: timber-and-plaster houses, stone walls, pitched roofs, worn paths, grass, a well, smithy and cathedral graveyard. Use subdued outdoor illumination with local hearth warmth. Exclude the sequel's burned ruin, a bustling capital and permanent lava or dungeon-black darkness.", },
  { id: "d1-env-cathedral", profile: 'diablo1', category: "art", scope: "global", title: "Cathedral: levels 1-4",
    body: "For Cathedral levels 1-4, use cool gray-blue masonry, square flagstones, repeated Gothic arches, columns, barred openings and wooden doors. Arrange rectangular rooms and corridors; add braziers, book stands, sarcophagi and isolated blood. Keep built church architecture dominant; no cave walls or bone-built halls.",
    refs: ["https://www.boristhebrave.com/2019/07/14/dungeon-generation-in-diablo-1/", "https://www.ladyofthecake.com/diablo/dungeon.htm"], },
  { id: "d1-env-catacombs", profile: 'diablo1', category: "art", scope: "global", title: "Catacombs: levels 5-8",
    body: "For Catacombs levels 5-8, use darker brown rough masonry, earthen-looking floors, thick piers and broad stone openings. Wrap winding passages around enclosed rooms; use shrines, barrels and funerary debris sparingly. Make the space lower, rougher and more enclosed than Cathedral; no repeated blue Gothic nave or lava-dominated cavern.",
    refs: ["https://www.ladyofthecake.com/diablo/dungeon.htm"], },
  { id: "d1-env-caves", profile: 'diablo1', category: "art", scope: "global", title: "Caves: levels 9-12",
    body: "For Caves levels 9-12, use irregular rock walls, rough earth, open cavern pockets, narrow land connections and orange-red lava pools or channels. Include crude wooden fences, gates and short crossings where appropriate. Preserve dark rock against hot lava; exclude orderly church colonnades, ice caves and luminous crystal gardens.",
    refs: ["https://www.ladyofthecake.com/diablo/dungeon.htm"], },
  { id: "d1-env-hell", profile: 'diablo1', category: "art", scope: "global", title: "Hell: levels 13-16",
    body: "For Hell levels 13-16, use dark tiled floors, skeletal walls, rib-like arches, skull masses, fire and impaled bodies. Compose broad constructed chambers and passages in bone, charcoal and blood-red tones. Keep this infernal architecture distinct from the Caves' natural rock and lava; no clean obsidian palace or abstract cosmic void.",
    refs: ["https://www.ladyofthecake.com/diablo/dungeon.htm"], },
  { id: "d1-props", profile: 'diablo1', category: "art", scope: "props", title: "Readable dungeon objects",
    body: "Make doors, chests, barrels, book stands, shrines and torture fixtures compact objects with a clear base and usable face. Use iron bands, rough boards, carved stone, candles and bone details. Keep blood and debris as discrete readable patches; no quest-marker beams, hovering interaction labels or ornamental clutter hiding the floor.", },
  { id: "d1-inventory-icons", profile: 'diablo1', category: "art", scope: "global", title: "Inventory objects, not framed cards",
    body: "For inventory art, render one object as a compact shaded sprite with a crisp silhouette, dark contour and small material highlights. Use a view that exposes its defining parts; long weapons and armor may occupy several grid cells. Composite over the inventory's dark reddish-brown field. No scenery, baked labels, rarity frame or square-card crop.", },
  { id: "d1-item-color", profile: 'diablo1', category: "art", scope: "items", title: "Material color and original potion cues",
    body: "Use ordinary steel, wood, leather and cloth for equipment, with small jewel or gold accents where appropriate. Potion contents distinguish red life, blue mana and yellow rejuvenation. Do not add socket-gem displays, crafting-orb families, legendary loot beams or glowing rarity borders.",
    refs: ["https://www.purediablo.com/strategy/diablo-1-guide-multiplayer-rogue-guide"], },
  { id: "d1-icon-family", profile: 'diablo1', category: "art", scope: "icon-sets", title: "Coherent object and spell icon families",
    body: "For an icon family, keep pixel density, shadow depth, highlight size and edge treatment consistent. Item icons show objects; spell icons use compact pictorial symbols, not miniature inventory weapons. Check the whole sheet at intended display size. No vector glyph packs, rarity frames or per-icon studio backgrounds.", },
  { id: "d1-spell-identity", profile: 'diablo1', category: "art", scope: "global", title: "Distinct, compact spell imagery",
    body: "Spell identity, derived from the engine: the pinned C++ names missile graphics, damage types, footprints, and durations, but it does not establish the listed palettes, edge treatment, or prohibitions on purple smoke, particles, and glyph circles. Those are art-direction choices, not engine-verifiable laws.",
    refs: ["https://hoffmeister.li/downloads/games/diablo_1/D1_manual_en.pdf"], },
  { id: "d1-ui", profile: 'diablo1', category: "art", scope: "global", title: "Dense stone-framed panels and line automap",
    body: "Use dark stone-framed character, inventory and spell panels, compact Gothic or serif lettering and pixel-shaded inset controls. Inventory must read as a grid plus equipment slots. Show dungeon mapping as thin lines over the playfield. No parchment full-screen atlas, rounded mobile cards, sans-serif dashboard styling or persistent overhead health bars.", },
  { id: "d1-music-town", profile: 'diablo1', category: "art", scope: "music", title: "Tristram's melancholy acoustic foreground",
    body: "For Tristram, foreground a recorded acoustic-guitar timbre with repeating picked figures, resonant strings and a melancholy, unsettled harmonic bed. Leave space between phrases. Compose new music; do not reproduce the original melody. Exclude jaunty tavern dance, heroic brass fanfare and an exclusively chiptune arrangement.",
    refs: ["https://www.shacknews.com/article/60997/from-tristram-to-torchlight-an"], },
  { id: "d1-music-dungeons", profile: 'diablo1', category: "art", scope: "music", title: "Dungeon texture, percussion and unease",
    body: "For dungeons, combine dark sustained textures, dissonant fragments, heavy percussion and processed guitar or metallic sounds. Use repetition and uneasy gaps; deeper tiers may feel harsher without becoming a victory anthem. Compose continuous zone pieces rather than mandatory combat-intensity stems. Do not copy recorded music or themes.",
    refs: ["https://www.shacknews.com/article/60997/from-tristram-to-torchlight-an"], },
  { id: "d1-audio-space", profile: 'diablo1', category: "art", scope: "ambient", title: "Sparse cues that expose nearby threats",
    body: "Use sparse, identifiable cues: footfalls, creaking doors, metal hits, creature cries, fire and occasional distant moans. Leave audible gaps so a nearby threat cuts through the bed. Keep voices close and intelligible, with environmental reverberation where useful. Avoid constant battle crowds, comedy effects and a continuous cinematic sub-bass wash.", },
  { id: "d1-ue-translation", profile: 'diablo1', category: "art", scope: "global", title: "Explicit modern UE presentation translation",
    body: "Explicit modern translation, only for UE deliverables: meshes, materials and Niagara may implement this profile, but judge their output through the fixed gameplay camera at 640x480. Keep stepped shading, compact textures and bounded light; disable depth of field, motion blur and broad bloom. Technical fidelity cannot replace the required sprite-scale silhouette.", },
];
