/**
 * Import Automation's script generator.
 *
 * glTF/GLB — the format every PoF generator writes — renders the EXACT python the
 * `/api/visual-gen/ue-import` route runs, built by the one import plan (`ue-import-plan.ts`).
 * It used to emit a C++ class whose glTF branch was a comment, with a hand-typed `scale: 1.0`
 * and `bAutoGenerateCollision` — a second theory of the import boundary that could disagree
 * with the derived one. FBX keeps the C++ template, but its collision is the plan's (never the
 * importer's one-box fallback) and its scale prints at full precision.
 *
 * Node-free: rendered by a client component, so it imports only the pure plan.
 */
import { buildGlbImportPython, collisionPlan, planUeImport, type CollisionUse, type UeImportPlan } from './ue-import-plan';

export interface ImportConfig {
  /** Asset name (PascalCase) */
  assetName: string;
  /** Source file format */
  format: 'fbx' | 'gltf' | 'glb';
  /** Import as skeletal or static mesh */
  meshType: 'static' | 'skeletal';
  /**
   * FBX-only typed scale (1.0 = no change). glTF/GLB scale is never typed: the import route
   * derives it from the measured mesh against the class / declared target.
   */
  scale: number;
  /** What the asset is FOR — decides collision. `null` until chosen: no default is safe. */
  use: CollisionUse | null;
  /** Declared shell count, used only because this view has no mesh to measure. */
  components?: number;
  /** Source file path written into the glTF/GLB python (a placeholder when blank). */
  sourcePath: string;
  /** Import materials */
  importMaterials: boolean;
  /** LOD count (0 = no LODs) */
  lodCount: number;
  /** Target content directory in UE5 */
  contentPath: string;
}

/** A python/C++ float literal at full precision (`0.05` stays `0.05`; `3` → `3.0`). */
export function formatScale(n: number): string {
  return Number.isInteger(n) ? n.toFixed(1) : String(Math.round(n * 1e4) / 1e4);
}

/**
 * The import plan this config stands for — the same `planUeImport` the route runs, with no
 * critique (this view has no mesh), so collision is `declared`/`assumed` and scale is never
 * derivable here. `null` until a use is chosen.
 */
export function importPlanFor(config: ImportConfig): UeImportPlan | null {
  if (!config.use) return null;
  return planUeImport({ critique: undefined, use: config.use, declaredShells: config.components });
}

function glbImportPython(config: ImportConfig): string {
  const plan = importPlanFor(config);
  const source = config.sourcePath.trim() || `<path to ${config.assetName}.${config.format}>`;
  if (!plan) {
    return [
      `# ${config.assetName}: pick what the asset is FOR (blocking / decorative / character) first.`,
      '# `use` decides collision and no default is safe: a decorative asset wants none, a blocking prop wants hulls.',
    ].join('\n');
  }
  return [
    `# UE python import for ${config.assetName} (run in the editor; the same python POST /api/visual-gen/ue-import runs)`,
    `# collision: ${plan.collision.kind} (${plan.collisionBasis}) - ${plan.collision.reason}`,
    `# scale: not applied here - ${plan.scale.reason}; the import route derives it from the measured mesh (pass assetClass/targetExtentM)`,
    buildGlbImportPython(source, config.contentPath, config.assetName, { collision: plan.collision }),
  ].join('\n');
}

export function generateImportScript(config: ImportConfig): string {
  if (config.format !== 'fbx') return glbImportPython(config);
  const collision = config.use ? collisionPlan({ use: config.use, components: config.components }) : null;
  const collisionNote = collision
    ? `// Collision plan: ${collision.kind} - ${collision.reason}. Ship UCX_ hulls in the FBX or build it post-import.`
    : '// Collision: pick what the asset is FOR first - no default is safe.';

  return `// Auto-generated UE5 Import Script for ${config.assetName}
// Generated by PoF Asset Studio — Import Automation
#pragma once

#include "CoreMinimal.h"
#include "EditorUtilityWidget.h"
#include "AssetImportTask.h"
#include "Factories/FbxFactory.h"
#include "AssetToolsModule.h"
#include "${config.assetName}Importer.generated.h"

/**
 * Editor utility for importing ${config.assetName} assets.
 * Usage: Right-click in Content Browser > Scripted Actions > Import ${config.assetName}
 */
UCLASS(BlueprintType)
class U${config.assetName}Importer : public UEditorUtilityWidget
{
    GENERATED_BODY()

public:
    UFUNCTION(BlueprintCallable, Category = "Asset Import")
    void ImportAsset(const FString& SourceFilePath)
    {
        UAssetImportTask* ImportTask = NewObject<UAssetImportTask>();
        ImportTask->Filename = SourceFilePath;
        ImportTask->DestinationPath = TEXT("${config.contentPath}");
        ImportTask->DestinationName = TEXT("${config.assetName}");
        ImportTask->bReplaceExisting = true;
        ImportTask->bAutomated = true;
        ImportTask->bSave = true;

        // Configure FBX import settings
        UFbxFactory* Factory = NewObject<UFbxFactory>();
        Factory->ImportUI->bImportMesh = true;
        Factory->ImportUI->bImportAsSkeletal = ${config.meshType === 'skeletal' ? 'true' : 'false'};
        Factory->ImportUI->bImportMaterials = ${config.importMaterials ? 'true' : 'false'};
        // The importer's auto collision is a coarse one-box fallback, NOT a substitute.
        ${collisionNote}
        Factory->ImportUI->bAutoGenerateCollision = false;
        Factory->ImportUI->StaticMeshImportData->ImportUniformScale = ${formatScale(config.scale)}f;
        ${config.lodCount > 0 ? `Factory->ImportUI->StaticMeshImportData->bAutoComputeLodDistances = true;` : '// No LOD generation'}
        ImportTask->Factory = Factory;

        // Execute import
        IAssetTools& AssetTools = FModuleManager::LoadModuleChecked<FAssetToolsModule>("AssetTools").Get();
        AssetTools.ImportAssetTasks({ImportTask});

        if (ImportTask->IsAssetImportSuccessful())
        {
            UE_LOG(LogTemp, Log, TEXT("Successfully imported ${config.assetName} to ${config.contentPath}"));
        }
        else
        {
            UE_LOG(LogTemp, Error, TEXT("Failed to import ${config.assetName}"));
        }
    }
};
`;
}

export function generateDataAsset(config: ImportConfig): string {
  return `// Auto-generated UE5 DataAsset for ${config.assetName}
// Generated by PoF Asset Studio — Import Automation
#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "${config.assetName}Data.generated.h"

/**
 * Data asset cataloging an imported ${config.meshType} mesh.
 */
UCLASS(BlueprintType)
class U${config.assetName}Data : public UPrimaryDataAsset
{
    GENERATED_BODY()

public:
    /** Reference to the imported mesh */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Mesh")
    TSoftObjectPtr<${config.meshType === 'skeletal' ? 'USkeletalMesh' : 'UStaticMesh'}> Mesh;

    /** Material override slots */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Materials")
    TArray<TSoftObjectPtr<UMaterialInterface>> MaterialOverrides;

    /** LOD screen sizes (if applicable) */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "LOD")
    TArray<float> LODScreenSizes;

    /** Asset tags for filtering */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Metadata")
    TArray<FName> Tags;

    /** Source file path (for re-import reference) */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Metadata")
    FString SourceFilePath;

    /** Import scale factor used */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Metadata")
    ${config.format === 'fbx'
      ? `float ImportScale = ${formatScale(config.scale)}f;`
      : "float ImportScale = 0.0f; // not typed: record the ue-import job's derived scale.factor (0 = not recorded)"}

    virtual FPrimaryAssetId GetPrimaryAssetId() const override
    {
        return FPrimaryAssetId("${config.assetName}Data", GetFName());
    }
};
`;
}

export const DEFAULT_IMPORT_CONFIG: ImportConfig = {
  assetName: 'MyAsset',
  format: 'fbx',
  meshType: 'static',
  scale: 1.0,
  use: null,
  sourcePath: '',
  importMaterials: true,
  lodCount: 0,
  contentPath: '/Game/Assets/Imported',
};
