/**
 * UE5 C++ code templates for asset import automation.
 * Templates use placeholder markers that get replaced with user config.
 */

export interface ImportConfig {
  /** Asset name (PascalCase) */
  assetName: string;
  /** Source file format */
  format: 'fbx' | 'gltf' | 'glb';
  /** Import as skeletal or static mesh */
  meshType: 'static' | 'skeletal';
  /** Scale factor (1.0 = no change) */
  scale: number;
  /** Auto-generate collision */
  generateCollision: boolean;
  /** Import materials */
  importMaterials: boolean;
  /** LOD count (0 = no LODs) */
  lodCount: number;
  /** Target content directory in UE5 */
  contentPath: string;
}

export function generateImportScript(config: ImportConfig): string {
  const meshClass = config.meshType === 'skeletal' ? 'USkeletalMesh' : 'UStaticMesh';
  const factoryClass = config.format === 'fbx' ? 'UFbxFactory' : 'UGLTFImporterFactory';

  return `// Auto-generated UE5 Import Script for ${config.assetName}
// Generated by PoF Asset Studio — Import Automation
#pragma once

#include "CoreMinimal.h"
#include "EditorUtilityWidget.h"
#include "AssetImportTask.h"
#include "Factories/FbxFactory.h"
#include "AssetToolsModule.h"
#include "${config.assetName}Importer.generated.h"

/**
 * Editor utility for importing ${config.assetName} assets.
 * Usage: Right-click in Content Browser > Scripted Actions > Import ${config.assetName}
 */
UCLASS(BlueprintType)
class U${config.assetName}Importer : public UEditorUtilityWidget
{
    GENERATED_BODY()

public:
    UFUNCTION(BlueprintCallable, Category = "Asset Import")
    void ImportAsset(const FString& SourceFilePath)
    {
        UAssetImportTask* ImportTask = NewObject<UAssetImportTask>();
        ImportTask->Filename = SourceFilePath;
        ImportTask->DestinationPath = TEXT("${config.contentPath}");
        ImportTask->DestinationName = TEXT("${config.assetName}");
        ImportTask->bReplaceExisting = true;
        ImportTask->bAutomated = true;
        ImportTask->bSave = true;

        // Configure ${config.format.toUpperCase()} import settings
        ${config.format === 'fbx' ? `UFbxFactory* Factory = NewObject<UFbxFactory>();
        Factory->ImportUI->bImportMesh = true;
        Factory->ImportUI->bImportAsSkeletal = ${config.meshType === 'skeletal' ? 'true' : 'false'};
        Factory->ImportUI->bImportMaterials = ${config.importMaterials ? 'true' : 'false'};
        Factory->ImportUI->bAutoGenerateCollision = ${config.generateCollision ? 'true' : 'false'};
        Factory->ImportUI->StaticMeshImportData->ImportUniformScale = ${config.scale.toFixed(1)}f;
        ${config.lodCount > 0 ? `Factory->ImportUI->StaticMeshImportData->bAutoComputeLodDistances = true;` : '// No LOD generation'}
        ImportTask->Factory = Factory;` : `// glTF import via Interchange or glTF plugin
        // Configure via FInterchangeImportSettings`}

        // Execute import
        IAssetTools& AssetTools = FModuleManager::LoadModuleChecked<FAssetToolsModule>("AssetTools").Get();
        AssetTools.ImportAssetTasks({ImportTask});

        if (ImportTask->IsAssetImportSuccessful())
        {
            UE_LOG(LogTemp, Log, TEXT("Successfully imported ${config.assetName} to ${config.contentPath}"));
        }
        else
        {
            UE_LOG(LogTemp, Error, TEXT("Failed to import ${config.assetName}"));
        }
    }
};
`;
}

export function generateDataAsset(config: ImportConfig): string {
  return `// Auto-generated UE5 DataAsset for ${config.assetName}
// Generated by PoF Asset Studio — Import Automation
#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "${config.assetName}Data.generated.h"

/**
 * Data asset cataloging an imported ${config.meshType} mesh.
 */
UCLASS(BlueprintType)
class U${config.assetName}Data : public UPrimaryDataAsset
{
    GENERATED_BODY()

public:
    /** Reference to the imported mesh */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Mesh")
    TSoftObjectPtr<${config.meshType === 'skeletal' ? 'USkeletalMesh' : 'UStaticMesh'}> Mesh;

    /** Material override slots */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Materials")
    TArray<TSoftObjectPtr<UMaterialInterface>> MaterialOverrides;

    /** LOD screen sizes (if applicable) */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "LOD")
    TArray<float> LODScreenSizes;

    /** Asset tags for filtering */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Metadata")
    TArray<FName> Tags;

    /** Source file path (for re-import reference) */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Metadata")
    FString SourceFilePath;

    /** Import scale factor used */
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Metadata")
    float ImportScale = ${config.scale.toFixed(1)}f;

    virtual FPrimaryAssetId GetPrimaryAssetId() const override
    {
        return FPrimaryAssetId("${config.assetName}Data", GetFName());
    }
};
`;
}

export const DEFAULT_IMPORT_CONFIG: ImportConfig = {
  assetName: 'MyAsset',
  format: 'fbx',
  meshType: 'static',
  scale: 1.0,
  generateCollision: true,
  importMaterials: true,
  lodCount: 0,
  contentPath: '/Game/Assets/Imported',
};
