import { CYCLE_DURATION } from './constants';
import type { HudTheme, RGBA, DamageEvent } from './types';

// ── Utility ────────────────────────────────────────────────────────────────

export function rgbaToCSS(c: RGBA): string {
  return `rgba(${Math.round(c.r * 255)},${Math.round(c.g * 255)},${Math.round(c.b * 255)},${c.a})`;
}

export function rgbaToHex(c: RGBA): string {
  const h = (v: number) => Math.round(v * 255).toString(16).padStart(2, '0');
  return `#${h(c.r)}${h(c.g)}${h(c.b)}`;
}

export function hexToRGBA(hex: string): RGBA {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  return { r, g, b, a: 1.0 };
}

export function lerpColor(a: RGBA, b: RGBA, t: number): RGBA {
  return {
    r: a.r + (b.r - a.r) * t,
    g: a.g + (b.g - a.g) * t,
    b: a.b + (b.b - a.b) * t,
    a: a.a + (b.a - a.a) * t,
  };
}

export function lerpNum(a: number, b: number, t: number): number {
  return a + (b - a) * t;
}

export function clamp(v: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, v));
}

export function fmtLinearColor(c: RGBA): string {
  return `FLinearColor(${c.r.toFixed(2)}f, ${c.g.toFixed(2)}f, ${c.b.toFixed(2)}f, ${c.a.toFixed(2)}f)`;
}

// ── Scripted combat sequence ────────────────────────────────────────────────

export function getCombatEvents(time: number, theme: HudTheme): {
  playerHealth: number;
  enemyHealth: number;
  damageEvents: DamageEvent[];
} {
  const t = time % CYCLE_DURATION;
  const events: DamageEvent[] = [];
  let nextId = Math.floor(time / CYCLE_DURATION) * 100;

  // Player health timeline: starts 100%, takes damage, heals, takes more
  let playerHealth: number;
  if (t < 1.0) playerHealth = 1.0;
  else if (t < 2.0) playerHealth = lerpNum(1.0, 0.6, (t - 1.0));
  else if (t < 3.0) playerHealth = 0.6;
  else if (t < 4.0) playerHealth = lerpNum(0.6, 0.15, (t - 3.0));
  else if (t < 5.5) playerHealth = 0.15; // low-health pulse zone
  else if (t < 6.5) playerHealth = lerpNum(0.15, 0.7, (t - 5.5));
  else playerHealth = 0.7;

  // Enemy health timeline: takes hits from player
  let enemyHealth: number;
  if (t < 0.5) enemyHealth = 1.0;
  else if (t < 1.5) enemyHealth = lerpNum(1.0, 0.75, (t - 0.5));
  else if (t < 3.0) enemyHealth = lerpNum(0.75, 0.4, (t - 1.5) / 1.5);
  else if (t < 5.0) enemyHealth = lerpNum(0.4, 0.1, (t - 3.0) / 2.0);
  else if (t < 6.0) enemyHealth = lerpNum(0.1, 0.0, (t - 5.0));
  else enemyHealth = 0;

  // Spawn damage numbers at scripted times
  const hitTimes: Array<{ time: number; amount: number; element: string; isCrit: boolean; isHeal: boolean }> = [
    { time: 0.5, amount: 247, element: 'Physical', isCrit: false, isHeal: false },
    { time: 1.2, amount: 892, element: 'Fire',     isCrit: true,  isHeal: false },
    { time: 2.0, amount: 156, element: 'Ice',      isCrit: false, isHeal: false },
    { time: 2.8, amount: 1203, element: 'Lightning', isCrit: true, isHeal: false },
    { time: 3.5, amount: 310, element: 'Physical', isCrit: false, isHeal: false },
    { time: 4.2, amount: 567, element: 'Fire',     isCrit: false, isHeal: false },
    { time: 5.0, amount: 728, element: 'Ice',      isCrit: true,  isHeal: false },
    { time: 5.6, amount: 200, element: 'Heal',     isCrit: false, isHeal: true },
    { time: 6.2, amount: 350, element: 'Heal',     isCrit: false, isHeal: true },
  ];

  // Seeded pseudo-random for consistent offsets
  const seededRand = (seed: number) => {
    const x = Math.sin(seed * 12.9898 + 78.233) * 43758.5453;
    return x - Math.floor(x);
  };

  for (const hit of hitTimes) {
    const age = t - hit.time;
    if (age >= 0 && age < theme.damageLifetime) {
      events.push({
        id: nextId++,
        amount: hit.amount,
        element: hit.element,
        isCrit: hit.isCrit,
        isHeal: hit.isHeal,
        spawnTime: hit.time,
        offsetX: (seededRand(hit.time * 7.1) - 0.5) * 2 * theme.horizontalSpread,
      });
    }
  }

  return { playerHealth, enemyHealth, damageEvents: events };
}

// ── UE5 Export generator ───────────────────────────────────────────────────

export function generateUE5Config(theme: HudTheme): string {
  const lines: string[] = [];
  lines.push('// ══════════════════════════════════════════════════════════════════════');
  lines.push('// UMG HUD Theme Configuration — generated by PoF HUD Theme Editor');
  lines.push('// Copy these values into your UE5 C++ UPROPERTY defaults or Blueprint.');
  lines.push('// ══════════════════════════════════════════════════════════════════════');
  lines.push('');

  lines.push('// ── ARPGHUDWidget — Player Health Bar ──────────────────────────────');
  lines.push(`UPROPERTY(EditAnywhere, Category = "HUD|Health")`);
  lines.push(`FLinearColor HealthBarColor = ${fmtLinearColor(theme.healthyColor)};`);
  lines.push('');
  lines.push(`UPROPERTY(EditAnywhere, Category = "HUD|Health")`);
  lines.push(`FLinearColor LowHealthColor = ${fmtLinearColor(theme.dangerColor)};`);
  lines.push('');
  lines.push(`UPROPERTY(EditAnywhere, Category = "HUD|Health")`);
  lines.push(`float LowHealthThreshold = ${theme.lowHealthThreshold.toFixed(2)}f;`);
  lines.push('');
  lines.push(`UPROPERTY(EditAnywhere, Category = "HUD|Health")`);
  lines.push(`float LowHealthPulseSpeed = ${theme.lowHealthPulseSpeed.toFixed(1)}f;`);
  lines.push('');

  lines.push('// ── ARPGHUDWidget — Mana Bar ──────────────────────────────────────');
  lines.push(`UPROPERTY(EditAnywhere, Category = "HUD|Mana")`);
  lines.push(`FLinearColor ManaBarColor = ${fmtLinearColor(theme.manaColor)};`);
  lines.push('');

  lines.push('// ── EnemyHealthBarWidget — Enemy HP Bar ────────────────────────────');
  lines.push(`UPROPERTY(EditAnywhere, Category = "EnemyHP")`);
  lines.push(`FLinearColor BarColor = ${fmtLinearColor(theme.enemyBarColor)};`);
  lines.push('');
  lines.push(`UPROPERTY(EditAnywhere, Category = "EnemyHP")`);
  lines.push(`float BarInterpSpeed = ${theme.barInterpSpeed.toFixed(1)}f;`);
  lines.push('');
  lines.push(`UPROPERTY(EditAnywhere, Category = "EnemyHP|Fade")`);
  lines.push(`float FadeInDuration = ${theme.fadeInDuration.toFixed(2)}f;`);
  lines.push('');
  lines.push(`UPROPERTY(EditAnywhere, Category = "EnemyHP|Fade")`);
  lines.push(`float FadeOutDuration = ${theme.fadeOutDuration.toFixed(2)}f;`);
  lines.push('');
  lines.push(`UPROPERTY(EditAnywhere, Category = "EnemyHP|Fade")`);
  lines.push(`float FadeOutDelay = ${theme.fadeOutDelay.toFixed(1)}f;`);
  lines.push('');

  lines.push('// ── DamageNumberWidget — Floating Damage Numbers ───────────────────');
  for (const [name, color] of Object.entries(theme.elementColors)) {
    lines.push(`UPROPERTY(EditAnywhere, Category = "DamageNumbers|Colors")`);
    lines.push(`FLinearColor ${name}Color = ${fmtLinearColor(color)};`);
    lines.push('');
  }
  lines.push(`UPROPERTY(EditAnywhere, Category = "DamageNumbers|Font")`);
  lines.push(`float NormalFontSize = ${theme.normalFontSize.toFixed(0)}.0f;`);
  lines.push('');
  lines.push(`UPROPERTY(EditAnywhere, Category = "DamageNumbers|Font")`);
  lines.push(`float CritFontSize = ${theme.critFontSize.toFixed(0)}.0f;`);
  lines.push('');
  lines.push(`UPROPERTY(EditAnywhere, Category = "DamageNumbers|Animation")`);
  lines.push(`float FloatDistance = ${theme.floatDistance.toFixed(0)}.0f;`);
  lines.push('');
  lines.push(`UPROPERTY(EditAnywhere, Category = "DamageNumbers|Animation")`);
  lines.push(`float HorizontalSpread = ${theme.horizontalSpread.toFixed(0)}.0f;`);
  lines.push('');
  lines.push(`UPROPERTY(EditAnywhere, Category = "DamageNumbers|Animation")`);
  lines.push(`float DamageLifetime = ${theme.damageLifetime.toFixed(2)}f;`);

  return lines.join('\n');
}
