import { compileMachine } from '@/lib/state-machine-compile';
import type { EditorState, EditorTransition } from './types';

// ── Code Generation ──
// Every generator emits FROM compileMachine (src/lib/state-machine-compile.ts):
// the fallback, the priority cascade and the derived flags are the same model
// the linter checks and the canvas marks as Entry.

// Emitted whenever a generator is asked to produce output for an empty state
// list. Every exported generator must tolerate `states = []` — the editor
// allows deleting all states, and both the Export button and the View Code
// memo call straight into this module.
const EMPTY_STATES_STUB = [
  '// =====================================================',
  '// No states defined.',
  '// Add at least one state in the Visual State Machine',
  '// Editor before generating code.',
  '// =====================================================',
].join('\n');

export function generateEnumCode(states: EditorState[]): string {
  if (states.length === 0) return EMPTY_STATES_STUB;
  const lines = [
    'UENUM(BlueprintType)',
    'enum class EARPGAnimState : uint8',
    '{',
  ];
  for (const name of compileMachine(states, []).enumMembers) {
    lines.push(`\t${name},`);
  }
  lines.push('};');
  return lines.join('\n');
}

export function generateComputeAnimState(states: EditorState[]): string {
  // Guard: with no states there is no default to fall back to
  // (`sorted[sorted.length - 1]` would be undefined) — return a stub instead.
  if (states.length === 0) return EMPTY_STATES_STUB;
  // Priority ascending (0 = highest = checked first). The fallback is the
  // compiled one, so a second Default stays in the cascade instead of vanishing.
  const { ordered: sorted, cascade, fallback } = compileMachine(states, []);
  const defaultState = fallback ?? sorted[sorted.length - 1];

  const lines = [
    'EARPGAnimState UARPGAnimInstance::ComputeAnimState() const',
    '{',
    '\t// Priority order: ' + sorted.map((s) => s.name).join(' > '),
    '\t// Highest-priority state always wins.',
    '',
  ];

  for (const s of cascade) {
    lines.push(`\tif (${s.flag})`);
    lines.push('\t{');
    lines.push(`\t\treturn EARPGAnimState::${s.name};`);
    lines.push('\t}');
    lines.push('');
  }

  lines.push(`\treturn EARPGAnimState::${defaultState.name};`);
  lines.push('}');
  return lines.join('\n');
}

function generateNativeUpdateTransitionFlags(states: EditorState[], transitions: EditorTransition[]): string {
  const lines = [
    '// =================================================================',
    '// Transition flags (generated by PoF State Machine Editor)',
    '// Place inside NativeUpdateAnimation() after reading character state.',
    '// =================================================================',
    '',
  ];

  // Compound (or annotated) rules become derived transition flags; every one
  // is declared in the header section (generateDerivedFlagDeclarations).
  const { derivedFlags } = compileMachine(states, transitions);
  if (derivedFlags.length > 0) {
    lines.push('// Derived transition flags');
    for (const f of derivedFlags) {
      lines.push(`${f.name} = ${f.rule}; // ${f.fromName} -> ${f.toName}${f.description ? ` (${f.description})` : ''}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/** Header members for every derived flag the NativeUpdate block assigns. */
function generateDerivedFlagDeclarations(states: EditorState[], transitions: EditorTransition[]): string {
  const { derivedFlags } = compileMachine(states, transitions);
  if (derivedFlags.length === 0) return '// (no derived transition flags)';
  const lines = ['// Add to the AnimInstance class declaration (.h):'];
  for (const f of derivedFlags) {
    lines.push('UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "State Machine|Transitions")');
    lines.push(`bool ${f.name} = false;`);
  }
  return lines.join('\n');
}

function generateTransitionRulesComment(states: EditorState[], transitions: EditorTransition[]): string {
  const lines = [
    '/**',
    ' * State machine transition rules:',
    ' *',
  ];

  for (const t of transitions) {
    const from = states.find((s) => s.id === t.from);
    const to = states.find((s) => s.id === t.to);
    if (!from || !to) continue;
    const desc = t.description ? ` (${t.description})` : '';
    lines.push(` *   ${from.name} -> ${to.name}: ${t.rule}${desc}`);
  }

  lines.push(' */');
  return lines.join('\n');
}

export function generateAnimBPSetup(states: EditorState[], transitions: EditorTransition[]): string {
  if (states.length === 0) return EMPTY_STATES_STUB;
  const { ordered: sorted, entryId } = compileMachine(states, transitions);
  const isFallback = (s: EditorState) => s.id === entryId;
  const lines = [
    '// =====================================================',
    '// Animation Blueprint Setup Instructions',
    '// (Generated by PoF State Machine Editor)',
    '// =====================================================',
    '//',
    '// 1. ENUM SETUP',
    `//    Add ${states.length} states to the EARPGAnimState enum:`,
    ...sorted.map((s) => `//      - ${s.name} (priority ${s.priority}${isFallback(s) ? ', default/fallback' : ', flag: ' + s.flag})`),
    '//',
    '// 2. STATE MACHINE',
    '//    In the AnimBP, create a state machine with the following states:',
    ...sorted.map((s) => `//      [${s.name}]${s.montageRef ? ` → plays ${s.montageRef}` : ''}`),
    '//',
    '// 3. TRANSITIONS',
    '//    Wire the following transitions in the AnimBP:',
  ];

  for (const t of transitions) {
    const from = states.find((s) => s.id === t.from);
    const to = states.find((s) => s.id === t.to);
    if (!from || !to) continue;
    lines.push(`//      ${from.name} → ${to.name} : ${t.rule}${t.description ? ` // ${t.description}` : ''}`);
  }

  lines.push('//');
  lines.push('// 4. PRIORITY CASCADE');
  lines.push('//    ComputeAnimState() checks flags in this order:');
  for (const s of sorted) {
    if (isFallback(s)) {
      lines.push(`//      ${s.priority}. ${s.name} (default fallback)`);
    } else {
      lines.push(`//      ${s.priority}. ${s.name} — ${s.flag}`);
    }
  }

  return lines.join('\n');
}

export function generateFullCppOutput(states: EditorState[], transitions: EditorTransition[]): string {
  if (states.length === 0) return EMPTY_STATES_STUB;
  const sections = [
    '// =====================================================',
    '// Generated by PoF — Visual State Machine Editor',
    `// ${new Date().toISOString()}`,
    '// =====================================================',
    '',
    '// ── EARPGAnimState Enum ──',
    '',
    generateEnumCode(states),
    '',
    '// ── Transition Rules Documentation ──',
    '',
    generateTransitionRulesComment(states, transitions),
    '',
    '// ── ComputeAnimState() Implementation ──',
    '',
    generateComputeAnimState(states),
    '',
    '// ── Header: Derived Transition Flag Declarations ──',
    '',
    generateDerivedFlagDeclarations(states, transitions),
    '',
    '// ── NativeUpdateAnimation() Transition Flags ──',
    '',
    generateNativeUpdateTransitionFlags(states, transitions),
    '',
    '// ── AnimBP Setup Instructions ──',
    '',
    generateAnimBPSetup(states, transitions),
  ];
  return sections.join('\n');
}
