import type { EditorState, EditorTransition } from './types';

// ── Code Generation ──

// Emitted whenever a generator is asked to produce output for an empty state
// list. Every exported generator must tolerate `states = []` — the editor
// allows deleting all states, and both the Export button and the View Code
// memo call straight into this module.
const EMPTY_STATES_STUB = [
  '// =====================================================',
  '// No states defined.',
  '// Add at least one state in the Visual State Machine',
  '// Editor before generating code.',
  '// =====================================================',
].join('\n');

export function generateEnumCode(states: EditorState[]): string {
  if (states.length === 0) return EMPTY_STATES_STUB;
  const sorted = [...states].sort((a, b) => a.priority - b.priority);
  const lines = [
    'UENUM(BlueprintType)',
    'enum class EARPGAnimState : uint8',
    '{',
  ];
  for (const s of sorted) {
    lines.push(`\t${s.name},`);
  }
  lines.push('};');
  return lines.join('\n');
}

export function generateComputeAnimState(states: EditorState[]): string {
  // Guard: with no states there is no default to fall back to
  // (`sorted[sorted.length - 1]` would be undefined) — return a stub instead.
  if (states.length === 0) return EMPTY_STATES_STUB;
  // Sort by priority ascending (0 = highest = checked first)
  const sorted = [...states].sort((a, b) => a.priority - b.priority);
  const nonDefault = sorted.filter((s) => !s.isDefault);
  const defaultState = sorted.find((s) => s.isDefault) ?? sorted[sorted.length - 1];

  const lines = [
    'EARPGAnimState UARPGAnimInstance::ComputeAnimState() const',
    '{',
    '\t// Priority order: ' + sorted.map((s) => s.name).join(' > '),
    '\t// Highest-priority state always wins.',
    '',
  ];

  for (const s of nonDefault) {
    lines.push(`\tif (${s.flag})`);
    lines.push('\t{');
    lines.push(`\t\treturn EARPGAnimState::${s.name};`);
    lines.push('\t}');
    lines.push('');
  }

  lines.push(`\treturn EARPGAnimState::${defaultState.name};`);
  lines.push('}');
  return lines.join('\n');
}

function generateNativeUpdateTransitionFlags(states: EditorState[], transitions: EditorTransition[]): string {
  const lines = [
    '// =================================================================',
    '// Transition flags (generated by PoF State Machine Editor)',
    '// Place inside NativeUpdateAnimation() after reading character state.',
    '// =================================================================',
    '',
  ];

  // Group useful derivative flags
  const derivedFlags = new Map<string, string>();

  for (const t of transitions) {
    const fromState = states.find((s) => s.id === t.from);
    const toState = states.find((s) => s.id === t.to);
    if (!fromState || !toState) continue;

    // Check for compound rules that imply derived transition flags
    if (t.rule.includes('&&') || t.description) {
      const flagName = `bCan${fromState.name}To${toState.name}`;
      if (!derivedFlags.has(flagName)) {
        derivedFlags.set(flagName, `${t.rule}; // ${fromState.name} -> ${toState.name}${t.description ? ` (${t.description})` : ''}`);
      }
    }
  }

  if (derivedFlags.size > 0) {
    lines.push('// Derived transition flags');
    for (const [flag, expr] of derivedFlags) {
      lines.push(`${flag} = ${expr}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateTransitionRulesComment(states: EditorState[], transitions: EditorTransition[]): string {
  const lines = [
    '/**',
    ' * State machine transition rules:',
    ' *',
  ];

  for (const t of transitions) {
    const from = states.find((s) => s.id === t.from);
    const to = states.find((s) => s.id === t.to);
    if (!from || !to) continue;
    const desc = t.description ? ` (${t.description})` : '';
    lines.push(` *   ${from.name} -> ${to.name}: ${t.rule}${desc}`);
  }

  lines.push(' */');
  return lines.join('\n');
}

export function generateAnimBPSetup(states: EditorState[], transitions: EditorTransition[]): string {
  if (states.length === 0) return EMPTY_STATES_STUB;
  const sorted = [...states].sort((a, b) => a.priority - b.priority);
  const lines = [
    '// =====================================================',
    '// Animation Blueprint Setup Instructions',
    '// (Generated by PoF State Machine Editor)',
    '// =====================================================',
    '//',
    '// 1. ENUM SETUP',
    `//    Add ${states.length} states to the EARPGAnimState enum:`,
    ...sorted.map((s) => `//      - ${s.name} (priority ${s.priority}${s.isDefault ? ', default/fallback' : ', flag: ' + s.flag})`),
    '//',
    '// 2. STATE MACHINE',
    '//    In the AnimBP, create a state machine with the following states:',
    ...sorted.map((s) => `//      [${s.name}]${s.montageRef ? ` → plays ${s.montageRef}` : ''}`),
    '//',
    '// 3. TRANSITIONS',
    '//    Wire the following transitions in the AnimBP:',
  ];

  for (const t of transitions) {
    const from = states.find((s) => s.id === t.from);
    const to = states.find((s) => s.id === t.to);
    if (!from || !to) continue;
    lines.push(`//      ${from.name} → ${to.name} : ${t.rule}${t.description ? ` // ${t.description}` : ''}`);
  }

  lines.push('//');
  lines.push('// 4. PRIORITY CASCADE');
  lines.push('//    ComputeAnimState() checks flags in this order:');
  for (const s of sorted) {
    if (s.isDefault) {
      lines.push(`//      ${s.priority}. ${s.name} (default fallback)`);
    } else {
      lines.push(`//      ${s.priority}. ${s.name} — ${s.flag}`);
    }
  }

  return lines.join('\n');
}

export function generateFullCppOutput(states: EditorState[], transitions: EditorTransition[]): string {
  if (states.length === 0) return EMPTY_STATES_STUB;
  const sections = [
    '// =====================================================',
    '// Generated by PoF — Visual State Machine Editor',
    `// ${new Date().toISOString()}`,
    '// =====================================================',
    '',
    '// ── EARPGAnimState Enum ──',
    '',
    generateEnumCode(states),
    '',
    '// ── Transition Rules Documentation ──',
    '',
    generateTransitionRulesComment(states, transitions),
    '',
    '// ── ComputeAnimState() Implementation ──',
    '',
    generateComputeAnimState(states),
    '',
    '// ── NativeUpdateAnimation() Transition Flags ──',
    '',
    generateNativeUpdateTransitionFlags(states, transitions),
    '',
    '// ── AnimBP Setup Instructions ──',
    '',
    generateAnimBPSetup(states, transitions),
  ];
  return sections.join('\n');
}
