import type { WeeklyDigest } from '@/types/weekly-digest';
import { roundRect } from '@/lib/canvas-poster';
import { formatDuration } from '@/lib/format';
import { MODULE_COLORS, ACCENT_VIOLET, STATUS_INFO, ACCENT_RED, ACCENT_ORANGE, OVERLAY_WHITE, OPACITY_5, OPACITY_8, OPACITY_10 } from '@/lib/chart-colors';

// ── Format helpers ───────────────────────────────────────────────────────────

export function formatDateRange(start: string, end: string): string {
  const s = new Date(start + 'T12:00:00');
  const e = new Date(end + 'T12:00:00');
  e.setDate(e.getDate() - 1); // end is exclusive
  const opts: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric' };
  return `${s.toLocaleDateString('en', opts)} — ${e.toLocaleDateString('en', opts)}, ${s.getFullYear()}`;
}

// ── Markdown export ──────────────────────────────────────────────────────────

export function formatDigestMarkdown(d: WeeklyDigest): string {
  const lines: string[] = [];
  lines.push(`# POF Weekly Digest`);
  lines.push(`**${formatDateRange(d.periodStart, d.periodEnd)}**`);
  lines.push('');
  lines.push(`## Stats`);
  lines.push(`- **Sessions:** ${d.totalSessions} (${d.totalSessions - d.prevWeekSessions >= 0 ? '+' : ''}${d.totalSessions - d.prevWeekSessions} vs last week)`);
  lines.push(`- **Success Rate:** ${Math.round(d.successRate * 100)}%`);
  lines.push(`- **Checklist:** ${d.checklistCompleted}/${d.checklistTotal}`);
  lines.push(`- **Time Invested:** ${formatDuration(d.totalTimeMs)}`);
  lines.push(`- **Current Streak:** ${d.currentStreak} | **Best:** ${d.longestStreak}`);
  lines.push('');

  if (d.mostActiveModule) {
    lines.push(`## Most Active`);
    lines.push(`**${d.mostActiveModule.label}** — ${d.mostActiveModule.sessions} sessions`);
    lines.push('');
  }

  if (d.moduleActivity.length > 0) {
    lines.push(`## Module Activity`);
    for (const m of d.moduleActivity.slice(0, 8)) {
      lines.push(`- ${m.label}: ${m.sessions} sessions (${Math.round(m.successRate * 100)}% success)`);
    }
    lines.push('');
  }

  if (d.achievements.length > 0) {
    lines.push(`## Achievements`);
    for (const a of d.achievements) {
      lines.push(`- ${a.icon} **${a.title}** — ${a.description}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by POF*');

  return lines.join('\n');
}

// ── Canvas PNG rendering ─────────────────────────────────────────────────────

export function renderDigestToCanvas(canvas: HTMLCanvasElement, d: WeeklyDigest): void {
  const W = 800;
  const H = 600;
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext('2d')!;

  // Background
  ctx.fillStyle = '#0a0a0f';
  ctx.fillRect(0, 0, W, H);

  // Subtle gradient overlay
  const grad = ctx.createLinearGradient(0, 0, W, H);
  grad.addColorStop(0, `${ACCENT_VIOLET}${OPACITY_5}`);
  grad.addColorStop(1, `${MODULE_COLORS.setup}${OPACITY_5}`);
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, W, H);

  // Border
  ctx.strokeStyle = `${OVERLAY_WHITE}${OPACITY_8}`;
  ctx.lineWidth = 1;
  ctx.strokeRect(0.5, 0.5, W - 1, H - 1);

  let y = 40;

  // Title
  ctx.font = 'bold 22px system-ui, -apple-system, sans-serif';
  ctx.fillStyle = OVERLAY_WHITE;
  ctx.fillText('POF Weekly Digest', 40, y);
  y += 28;

  ctx.font = '13px system-ui, -apple-system, sans-serif';
  ctx.fillStyle = '#888888';
  ctx.fillText(formatDateRange(d.periodStart, d.periodEnd), 40, y);
  y += 40;

  // Stat boxes
  const stats = [
    { label: 'Sessions', value: d.totalSessions.toString(), color: STATUS_INFO },
    { label: 'Success Rate', value: `${Math.round(d.successRate * 100)}%`, color: MODULE_COLORS.setup },
    { label: 'Checklist', value: `${d.checklistCompleted}/${d.checklistTotal}`, color: ACCENT_VIOLET },
    { label: 'Time', value: formatDuration(d.totalTimeMs), color: MODULE_COLORS.content },
  ];

  const boxW = (W - 80 - 30) / 4;
  for (let i = 0; i < stats.length; i++) {
    const x = 40 + i * (boxW + 10);
    // Box bg
    ctx.fillStyle = `${OVERLAY_WHITE}${OPACITY_5}`;
    roundRect(ctx, x, y, boxW, 60, 8);
    ctx.fill();

    // Label
    ctx.font = '11px system-ui, -apple-system, sans-serif';
    ctx.fillStyle = '#888888';
    ctx.fillText(stats[i].label, x + 12, y + 20);

    // Value
    ctx.font = 'bold 20px system-ui, -apple-system, sans-serif';
    ctx.fillStyle = stats[i].color;
    ctx.fillText(stats[i].value, x + 12, y + 46);
  }
  y += 80;

  // Streak
  ctx.font = '13px system-ui, -apple-system, sans-serif';
  ctx.fillStyle = ACCENT_ORANGE;
  ctx.fillText(`\u{1F525} Streak: ${d.currentStreak}`, 40, y);
  ctx.fillStyle = '#888888';
  ctx.fillText(`  |  Best: ${d.longestStreak}`, 40 + ctx.measureText(`\u{1F525} Streak: ${d.currentStreak}`).width, y);
  y += 30;

  // Daily bars
  ctx.font = '11px system-ui, -apple-system, sans-serif';
  ctx.fillStyle = '#888888';
  ctx.fillText('Daily activity', 40, y);
  y += 16;

  const barAreaWidth = W - 80;
  const barW = (barAreaWidth - (d.dailySessions.length - 1) * 6) / d.dailySessions.length;
  const maxD = Math.max(...d.dailySessions.map((x) => x.total), 1);
  const barMaxH = 40;

  for (let i = 0; i < d.dailySessions.length; i++) {
    const dd = d.dailySessions[i];
    const x = 40 + i * (barW + 6);
    const h = dd.total > 0 ? Math.max(4, (dd.total / maxD) * barMaxH) : 2;
    const rate = dd.total > 0 ? dd.success / dd.total : 0;
    const color = dd.total === 0 ? `${OVERLAY_WHITE}${OPACITY_10}` : rate >= 0.75 ? MODULE_COLORS.setup : rate >= 0.5 ? MODULE_COLORS.content : ACCENT_RED;

    ctx.fillStyle = color;
    roundRect(ctx, x, y + barMaxH - h, barW, h, 2);
    ctx.fill();

    // Percentage label above bar
    if (dd.total > 0) {
      const pctLabel = `${Math.round((dd.success / dd.total) * 100)}%`;
      ctx.font = '9px system-ui, -apple-system, sans-serif';
      ctx.fillStyle = '#999999';
      const pctW = ctx.measureText(pctLabel).width;
      ctx.fillText(pctLabel, x + (barW - pctW) / 2, y + barMaxH - h - 3);
    }

    // Day label
    const dayLabel = new Date(dd.date + 'T12:00:00').toLocaleDateString('en', { weekday: 'narrow' });
    ctx.font = '10px system-ui, -apple-system, sans-serif';
    ctx.fillStyle = '#666666';
    const labelW = ctx.measureText(dayLabel).width;
    ctx.fillText(dayLabel, x + (barW - labelW) / 2, y + barMaxH + 14);
  }
  y += barMaxH + 30;

  // Module leaderboard
  if (d.moduleActivity.length > 0) {
    ctx.font = '11px system-ui, -apple-system, sans-serif';
    ctx.fillStyle = '#888888';
    ctx.fillText('Module activity', 40, y);
    y += 16;

    const maxSessions = d.moduleActivity[0].sessions;
    for (const m of d.moduleActivity.slice(0, 5)) {
      const barW2 = maxSessions > 0 ? (m.sessions / maxSessions) * (W - 280) : 0;
      const color = m.successRate >= 0.75 ? MODULE_COLORS.setup : m.successRate >= 0.5 ? MODULE_COLORS.content : ACCENT_RED;

      ctx.font = '12px system-ui, -apple-system, sans-serif';
      ctx.fillStyle = '#cccccc';
      ctx.fillText(m.label, 40, y + 12);

      ctx.fillStyle = color;
      roundRect(ctx, 200, y + 2, barW2, 12, 3);
      ctx.fill();

      ctx.font = '11px system-ui, -apple-system, sans-serif';
      ctx.fillStyle = '#888888';
      ctx.fillText(`${m.sessions}`, 200 + barW2 + 8, y + 12);
      const statusLabel = m.successRate >= 0.75 ? '✓' : m.successRate >= 0.5 ? '~' : '✗';
      ctx.fillStyle = color;
      ctx.fillText(`${statusLabel} ${Math.round(m.successRate * 100)}%`, W - 90, y + 12);

      y += 22;
    }
    y += 10;
  }

  // Achievements
  if (d.achievements.length > 0) {
    ctx.font = '11px system-ui, -apple-system, sans-serif';
    ctx.fillStyle = '#888888';
    ctx.fillText('Achievements', 40, y);
    y += 18;

    let ax = 40;
    for (const a of d.achievements) {
      const text = `${a.icon} ${a.title}`;
      ctx.font = '12px system-ui, -apple-system, sans-serif';
      const tw = ctx.measureText(text).width + 20;

      ctx.fillStyle = `${OVERLAY_WHITE}${OPACITY_5}`;
      roundRect(ctx, ax, y - 2, tw, 24, 12);
      ctx.fill();

      ctx.fillStyle = '#cccccc';
      ctx.fillText(text, ax + 10, y + 13);

      ax += tw + 8;
      if (ax > W - 100) { ax = 40; y += 30; }
    }
    y += 30;
  }

  // Footer
  ctx.font = '10px system-ui, -apple-system, sans-serif';
  ctx.fillStyle = '#444444';
  ctx.fillText('Generated by POF', W - 130, H - 16);
}
