import { formatDuration } from '@/lib/format';
import type { ProjectWrapped } from '@/types/project-wrapped';
import { formatLongDate, spanCaption } from './helpers';

// ── Markdown export ────────────────────────────────────────────────────────────

export function formatWrappedMarkdown(w: ProjectWrapped): string {
  const lines: string[] = [];
  lines.push('# POF Project Wrapped');
  lines.push(`**${spanCaption(w)}**`);
  lines.push('');
  lines.push('## Lifetime');
  lines.push(`- **Time invested:** ${formatDuration(w.totalTimeMs)}`);
  lines.push(`- **Sessions:** ${w.totalSessions.toLocaleString()} across ${w.activeDays} active days`);
  lines.push(`- **Success rate:** ${Math.round(w.successRate * 100)}%`);
  lines.push(`- **Modules conquered:** ${w.modulesConquered} (of ${w.modulesTouched} explored)`);
  lines.push(`- **Best streak:** ${w.longestStreak} consecutive successes`);
  if (w.biggestWeek) {
    lines.push(`- **Biggest week:** ${w.biggestWeek.sessions} sessions (week of ${formatLongDate(w.biggestWeek.weekStart)})`);
  }
  lines.push('');

  if (w.milestones.length > 0) {
    lines.push('## Milestones');
    for (const m of w.milestones) {
      lines.push(`- ${m.icon} **${m.title}** — ${m.description} _(${formatLongDate(m.date)})_`);
    }
    lines.push('');
  }

  if (w.topModules.length > 0) {
    lines.push('## Modules');
    for (const m of w.topModules) {
      lines.push(`- ${m.label}: ${m.sessions} sessions (${Math.round(m.successRate * 100)}% success)`);
    }
    lines.push('');
  }

  if (w.achievements.length > 0) {
    lines.push('## Achievements');
    for (const a of w.achievements) {
      lines.push(`- ${a.icon} **${a.title}** — ${a.description}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by POF*');
  return lines.join('\n');
}
