import type { CraftedAffix, ItemBase } from './data';
import { buildAffixName, computePowerBudget, getItemLevelScaling } from './data';

/** Generate UE5 C++ code for a pre-rolled item instance. */
export function generateExportCode(base: ItemBase, affixes: CraftedAffix[]): string {
  const lines = [
    '// =====================================================',
    '// Pre-rolled ItemInstance -- Generated by PoF Workbench',
    `// ${new Date().toISOString()}`,
    '// =====================================================',
    '',
    `// Base: ${base.name} (${base.type}, ${base.rarity}, Level ${base.itemLevel})`,
    `// Full Name: "${buildAffixName(base.name, affixes)}"`,
    `// Total Power: ${computePowerBudget(affixes, base.itemLevel).total.toFixed(1)}`,
    '',
    '// Create item instance in C++:',
    'UARPGItemInstance* Item = NewObject<UARPGItemInstance>(this);',
    `Item->Definition = LoadObject<UARPGItemDefinition>(nullptr, TEXT("/Game/Items/DA_${base.name.replace(/\s+/g, '_')}"));`,
    `Item->ItemLevel = ${base.itemLevel};`,
    `Item->StackCount = 1;`,
    '',
    '// Pre-roll affixes:',
    `Item->Affixes.Reserve(${affixes.length});`,
    '',
  ];

  for (const a of affixes) {
    const scaledMag = (a.magnitude * getItemLevelScaling(base.itemLevel)).toFixed(1);
    lines.push('{');
    lines.push('\tFItemAffix Affix;');
    lines.push(`\tAffix.AffixTag = FGameplayTag::RequestGameplayTag(FName("${a.tag}"));`);
    lines.push(`\tAffix.DisplayName = FText::FromString(TEXT("${a.displayName}"));`);
    lines.push(`\tAffix.Magnitude = ${scaledMag}f;`);
    lines.push(`\tAffix.bIsPrefix = ${a.bIsPrefix ? 'true' : 'false'};`);
    lines.push(`\t// Effect: GE_${a.stat.replace(/[^a-zA-Z]/g, '')}`);
    lines.push('\tItem->Affixes.Add(Affix);');
    lines.push('}');
    lines.push('');
  }

  const budget = computePowerBudget(affixes, base.itemLevel);
  lines.push(`// Item power budget: Offense=${budget.offense.toFixed(0)} Defense=${budget.defense.toFixed(0)} Utility=${budget.utility.toFixed(0)}`);

  return lines.join('\n');
}
