import { Skull, Crosshair, Shield, Swords } from 'lucide-react';
import {
  ACCENT_RED, ACCENT_CYAN, ACCENT_PURPLE, ACCENT_EMERALD,
  STATUS_WARNING, STATUS_INFO, ACCENT_ORANGE, ACCENT_PINK,
  STATUS_SUCCESS, STATUS_NEUTRAL, STATUS_SUBDUED,
  MODULE_COLORS, ACCENT_PURPLE_BOLD,
} from '@/lib/chart-colors';
import type { ArchetypeConfig, EnemyRole, EnemyCategory, EnemyTier } from './data';

/* ── Compact builder ──────────────────────────────────────────────────── */

interface CompactEnemy {
  id: string; label: string; icon: typeof Skull; color: string;
  cls: string; role: EnemyRole; cat: EnemyCategory; tier: EnemyTier; area: string;
  hp: number; atk: number; def: number; spd: number; int: number;
  abilities: string[]; bt: Record<string, string>;
}

function e(c: CompactEnemy): ArchetypeConfig {
  return {
    id: c.id, label: c.label, icon: c.icon, color: c.color,
    class: c.cls, role: c.role, category: c.cat, tier: c.tier, area: c.area,
    stats: [
      { label: 'HP', value: c.hp }, { label: 'ATK', value: c.atk },
      { label: 'DEF', value: c.def }, { label: 'SPD', value: c.spd }, { label: 'INT', value: c.int },
    ],
    abilities: c.abilities, btSummary: c.bt,
    featureName: `${c.label} Enemy`,
  };
}

/* ── Humanoid (20) ────────────────────────────────────────────────────── */

const HUMANOID: ArchetypeConfig[] = [
  e({ id: 'taris-thug', label: 'Taris Street Thug', icon: Skull, color: STATUS_SUBDUED,
    cls: 'Ruffian', role: 'swarm', cat: 'Humanoid', tier: 'minion', area: 'Taris',
    hp: 15, atk: 18, def: 12, spd: 60, int: 5,
    abilities: ['Shiv Stab', 'Throw Rock'],
    bt: { Sense: 'Visual 8m', Attack: 'Rush and stab', Special: 'Flees below 20% HP' } }),
  e({ id: 'gamorrean-guard', label: 'Gamorrean Guard', icon: Shield, color: ACCENT_EMERALD,
    cls: 'Enforcer', role: 'tank', cat: 'Humanoid', tier: 'standard', area: 'Taris',
    hp: 50, atk: 35, def: 45, spd: 30, int: 8,
    abilities: ['Vibro-Axe Swing', 'Roar', 'Shield Block'],
    bt: { Sense: 'Visual 10m', Attack: 'Heavy swing combo', Special: 'Roar taunts 3s' } }),
  e({ id: 'sith-trooper', label: 'Sith Trooper', icon: Crosshair, color: ACCENT_RED,
    cls: 'Soldier', role: 'ranged', cat: 'Humanoid', tier: 'standard', area: 'Taris',
    hp: 35, atk: 40, def: 30, spd: 45, int: 25,
    abilities: ['Blaster Rifle', 'Frag Grenade', 'Take Cover'],
    bt: { Sense: 'Visual 18m', Attack: 'Burst fire from cover', Special: 'Tosses grenade at clusters' } }),
  e({ id: 'dantooine-militia', label: 'Dantooine Militia', icon: Crosshair, color: STATUS_NEUTRAL,
    cls: 'Militia', role: 'ranged', cat: 'Humanoid', tier: 'minion', area: 'Dantooine',
    hp: 22, atk: 20, def: 15, spd: 50, int: 15,
    abilities: ['Blaster Pistol', 'Warning Shot'],
    bt: { Sense: 'Visual 14m', Attack: 'Fire and retreat', Special: 'Calls reinforcements' } }),
  e({ id: 'mandalorian-scout', label: 'Mandalorian Scout', icon: Crosshair, color: ACCENT_CYAN,
    cls: 'Scout', role: 'ranged', cat: 'Humanoid', tier: 'elite', area: 'Dantooine',
    hp: 55, atk: 50, def: 40, spd: 55, int: 45,
    abilities: ['Sniper Shot', 'Stealth Field', 'Thermal Detonator'],
    bt: { Sense: 'Visual 25m', Attack: 'Snipe from distance', Special: 'Cloaks after 2 hits taken' } }),
  e({ id: 'czerka-slaver', label: 'Czerka Slaver', icon: Crosshair, color: STATUS_WARNING,
    cls: 'Slaver', role: 'ranged', cat: 'Humanoid', tier: 'standard', area: 'Kashyyyk',
    hp: 38, atk: 35, def: 25, spd: 40, int: 30,
    abilities: ['Stun Baton', 'Neural Disruptor', 'Sonic Grenade'],
    bt: { Sense: 'Visual 15m', Attack: 'Stun then restrain', Special: 'Neural disruptor silences 3s' } }),
  e({ id: 'exchange-thug', label: 'Exchange Thug', icon: Skull, color: STATUS_SUBDUED,
    cls: 'Criminal', role: 'melee', cat: 'Humanoid', tier: 'minion', area: 'Nar Shaddaa',
    hp: 18, atk: 22, def: 10, spd: 55, int: 8,
    abilities: ['Vibroblade Slash', 'Dirty Kick'],
    bt: { Sense: 'Visual 10m', Attack: 'Aggressive rush', Special: 'Dirty kick stuns 1s' } }),
  e({ id: 'bounty-hunter', label: 'Bounty Hunter', icon: Crosshair, color: ACCENT_ORANGE,
    cls: 'Hunter', role: 'ranged', cat: 'Humanoid', tier: 'elite', area: 'Nar Shaddaa',
    hp: 58, atk: 60, def: 45, spd: 50, int: 55,
    abilities: ['Dual Blasters', 'Wrist Flamethrower', 'Jetpack Escape', 'Carbonite Trap'],
    bt: { Sense: 'Multi-sensor 20m', Attack: 'Dual blaster kiting', Special: 'Jetpack reposition every 8s' } }),
  e({ id: 'selkath-guard', label: 'Selkath Guard', icon: Shield, color: STATUS_INFO,
    cls: 'Guard', role: 'melee', cat: 'Humanoid', tier: 'standard', area: 'Manaan',
    hp: 40, atk: 30, def: 40, spd: 40, int: 30,
    abilities: ['Electro-Staff', 'Stasis Net', 'Call Backup'],
    bt: { Sense: 'Sonar 12m', Attack: 'Defensive stance', Special: 'Stasis net immobilizes 2s' } }),
  e({ id: 'republic-soldier', label: 'Republic Soldier', icon: Crosshair, color: STATUS_SUCCESS,
    cls: 'Soldier', role: 'ranged', cat: 'Humanoid', tier: 'standard', area: 'Manaan',
    hp: 40, atk: 38, def: 35, spd: 45, int: 30,
    abilities: ['Blaster Rifle', 'Ion Grenade', 'Squad Formation'],
    bt: { Sense: 'Visual 16m', Attack: 'Disciplined fire', Special: 'Formation buff when near allies' } }),
  e({ id: 'onderon-soldier', label: 'Onderon Soldier', icon: Crosshair, color: MODULE_COLORS.core,
    cls: 'Soldier', role: 'ranged', cat: 'Humanoid', tier: 'standard', area: 'Onderon',
    hp: 42, atk: 38, def: 35, spd: 42, int: 28,
    abilities: ['Blaster Carbine', 'Stun Grenade', 'Bayonet Charge'],
    bt: { Sense: 'Visual 15m', Attack: 'Suppressive fire', Special: 'Bayonet charge at close range' } }),
  e({ id: 'royalist-guard', label: 'Royalist Guard', icon: Shield, color: ACCENT_PURPLE,
    cls: 'Guard', role: 'tank', cat: 'Humanoid', tier: 'elite', area: 'Onderon',
    hp: 65, atk: 45, def: 60, spd: 35, int: 35,
    abilities: ['Force Pike', 'Shield Wall', 'Rally Cry'],
    bt: { Sense: 'Visual 12m', Attack: 'Defensive pike thrust', Special: 'Shield wall reduces incoming 40%' } }),
  e({ id: 'mandalorian-heavy', label: 'Mandalorian Heavy', icon: Shield, color: ACCENT_CYAN,
    cls: 'Heavy', role: 'tank', cat: 'Humanoid', tier: 'elite', area: 'Dxun',
    hp: 70, atk: 50, def: 65, spd: 25, int: 40,
    abilities: ['Repeating Blaster', 'Missile Launcher', 'Beskar Armor'],
    bt: { Sense: 'Visual 18m', Attack: 'Sustained heavy fire', Special: 'Missile every 12s' } }),
  e({ id: 'mandalorian-captain', label: 'Mandalorian Captain', icon: Swords, color: ACCENT_CYAN,
    cls: 'Captain', role: 'melee', cat: 'Humanoid', tier: 'boss', area: 'Dxun',
    hp: 80, atk: 70, def: 65, spd: 45, int: 55,
    abilities: ['Vibrosword Flurry', 'Rally Mandalorians', 'Power Shield', 'Jet Charge'],
    bt: { Sense: 'Multi-sensor 22m', Attack: 'Jet charge then flurry', Special: 'Rally buffs all nearby Mandalorians' } }),
  e({ id: 'trandoshan-slaver', label: 'Trandoshan Slaver', icon: Skull, color: ACCENT_EMERALD,
    cls: 'Slaver', role: 'melee', cat: 'Humanoid', tier: 'standard', area: 'Kashyyyk',
    hp: 45, atk: 42, def: 30, spd: 40, int: 18,
    abilities: ['Hunting Claw', 'Net Throw', 'Regeneration'],
    bt: { Sense: 'Thermal 12m', Attack: 'Net then claw', Special: 'Regenerates 2% HP per 5s' } }),
  e({ id: 'czerka-enforcer', label: 'Czerka Enforcer', icon: Shield, color: STATUS_WARNING,
    cls: 'Enforcer', role: 'tank', cat: 'Humanoid', tier: 'standard', area: 'Citadel Station',
    hp: 48, atk: 30, def: 45, spd: 35, int: 22,
    abilities: ['Shock Baton', 'Riot Shield', 'Gas Grenade'],
    bt: { Sense: 'Visual 12m', Attack: 'Shield bash then baton', Special: 'Gas grenade disorients 3s' } }),
  e({ id: 'twilek-medic', label: "Twi'lek Medic", icon: Crosshair, color: ACCENT_EMERALD,
    cls: 'Medic', role: 'healer', cat: 'Humanoid', tier: 'standard', area: 'Nar Shaddaa',
    hp: 30, atk: 15, def: 20, spd: 50, int: 45,
    abilities: ['Medpac Injection', 'Kolto Spray', 'Stimulant Boost'],
    bt: { Sense: 'Visual 14m', Attack: 'Heals lowest ally', Special: 'Stimulant boosts ally ATK 20%' } }),
  e({ id: 'peragus-miner', label: 'Peragus Miner', icon: Skull, color: STATUS_NEUTRAL,
    cls: 'Miner', role: 'melee', cat: 'Humanoid', tier: 'minion', area: 'Peragus',
    hp: 16, atk: 15, def: 10, spd: 45, int: 5,
    abilities: ['Mining Laser', 'Pickaxe Swing'],
    bt: { Sense: 'Visual 8m', Attack: 'Erratic swings', Special: 'Deranged — attacks anything' } }),
  e({ id: 'zhug-assassin', label: 'Zhug Assassin', icon: Swords, color: ACCENT_PURPLE_BOLD,
    cls: 'Assassin', role: 'melee', cat: 'Humanoid', tier: 'elite', area: 'Nar Shaddaa',
    hp: 50, atk: 62, def: 30, spd: 65, int: 40,
    abilities: ['Vibroblade Flurry', 'Cloaking Device', 'Poison Dart'],
    bt: { Sense: 'Thermal 15m', Attack: 'Cloak, approach, burst', Special: 'Poison dart DoT 8s' } }),
  e({ id: 'sith-officer', label: 'Sith Officer', icon: Crosshair, color: ACCENT_RED,
    cls: 'Officer', role: 'ranged', cat: 'Humanoid', tier: 'standard', area: 'Star Forge',
    hp: 38, atk: 35, def: 30, spd: 40, int: 35,
    abilities: ['Blaster Pistol', 'Rally Troops', 'Tactical Retreat'],
    bt: { Sense: 'Visual 16m', Attack: 'Fire from rear', Special: 'Rally buffs nearby troopers 15%' } }),
];

/* ── Beast (18) ───────────────────────────────────────────────────────── */

const BEAST: ArchetypeConfig[] = [
  e({ id: 'mutant-rakghoul', label: 'Mutant Rakghoul', icon: Skull, color: STATUS_SUCCESS,
    cls: 'Mutant', role: 'melee', cat: 'Beast', tier: 'standard', area: 'Taris',
    hp: 40, atk: 38, def: 30, spd: 55, int: 12,
    abilities: ['Frenzy Claws', 'Plague Spit', 'Berserker Leap'],
    bt: { Sense: 'Proximity 10m', Attack: 'Leap then frenzy', Special: 'Plague spit ranged 8m' } }),
  e({ id: 'kinrath-queen', label: 'Kinrath Queen', icon: Skull, color: ACCENT_EMERALD,
    cls: 'Brood Queen', role: 'tank', cat: 'Beast', tier: 'boss', area: 'Kashyyyk',
    hp: 85, atk: 60, def: 70, spd: 25, int: 20,
    abilities: ['Venomous Barrage', 'Summon Hatchlings', 'Burrow Strike', 'Acid Spray'],
    bt: { Sense: 'Vibration 15m', Attack: 'AoE venom spray', Special: 'Summons 3 hatchlings every 20s' } }),
  e({ id: 'horned-kath', label: 'Horned Kath Hound', icon: Skull, color: STATUS_WARNING,
    cls: 'Alpha', role: 'melee', cat: 'Beast', tier: 'standard', area: 'Dantooine',
    hp: 38, atk: 35, def: 28, spd: 60, int: 8,
    abilities: ['Gore', 'Charge', 'Rallying Howl'],
    bt: { Sense: 'Scent 14m', Attack: 'Charge then gore', Special: 'Rallying howl summons pack' } }),
  e({ id: 'shyrack', label: 'Shyrack', icon: Skull, color: STATUS_SUBDUED,
    cls: 'Flyer', role: 'swarm', cat: 'Beast', tier: 'minion', area: 'Korriban',
    hp: 12, atk: 15, def: 5, spd: 80, int: 3,
    abilities: ['Sonic Screech', 'Dive Attack'],
    bt: { Sense: 'Echolocation 20m', Attack: 'Dive in swarms', Special: 'Sonic screech disorients 1s' } }),
  e({ id: 'tukata', label: "Tuk'ata", icon: Skull, color: ACCENT_RED,
    cls: 'Sithspawn', role: 'melee', cat: 'Beast', tier: 'standard', area: 'Korriban',
    hp: 45, atk: 42, def: 35, spd: 50, int: 15,
    abilities: ['Savage Bite', 'Dark Side Howl', 'Pack Hunt'],
    bt: { Sense: 'Dark Side sense 12m', Attack: 'Coordinated pack', Special: 'Dark howl fears targets 2s' } }),
  e({ id: 'mykal', label: 'Mykal', icon: Skull, color: STATUS_NEUTRAL,
    cls: 'Flyer', role: 'swarm', cat: 'Beast', tier: 'minion', area: 'Kashyyyk',
    hp: 10, atk: 12, def: 5, spd: 85, int: 3,
    abilities: ['Peck', 'Swarm Dive'],
    bt: { Sense: 'Visual 15m', Attack: 'Dive in formation', Special: 'Swarm bonus: +5% ATK per ally' } }),
  e({ id: 'tacach', label: 'Tacach', icon: Skull, color: ACCENT_EMERALD,
    cls: 'Predator', role: 'melee', cat: 'Beast', tier: 'standard', area: 'Kashyyyk',
    hp: 42, atk: 38, def: 30, spd: 55, int: 10,
    abilities: ['Claw Rend', 'Pounce', 'Intimidate'],
    bt: { Sense: 'Scent 14m', Attack: 'Pounce from ambush', Special: 'Intimidate reduces target DEF 15%' } }),
  e({ id: 'cannok', label: 'Cannok', icon: Skull, color: MODULE_COLORS.content,
    cls: 'Predator', role: 'melee', cat: 'Beast', tier: 'standard', area: 'Dxun',
    hp: 35, atk: 32, def: 25, spd: 60, int: 8,
    abilities: ['Snap Jaws', 'Tail Whip', 'Camouflage'],
    bt: { Sense: 'Scent 10m', Attack: 'Ambush from brush', Special: 'Camouflage until first strike' } }),
  e({ id: 'zakkeg', label: 'Zakkeg', icon: Skull, color: MODULE_COLORS.content,
    cls: 'Alpha Predator', role: 'tank', cat: 'Beast', tier: 'elite', area: 'Dxun',
    hp: 75, atk: 55, def: 65, spd: 25, int: 10,
    abilities: ['Crushing Charge', 'Tail Slam', 'Thick Hide'],
    bt: { Sense: 'Vibration 15m', Attack: 'Charge and trample', Special: 'Thick hide: 30% damage reduction' } }),
  e({ id: 'boma-beast', label: 'Boma Beast', icon: Skull, color: ACCENT_ORANGE,
    cls: 'Predator', role: 'melee', cat: 'Beast', tier: 'standard', area: 'Dxun',
    hp: 40, atk: 35, def: 30, spd: 45, int: 8,
    abilities: ['Tusked Gore', 'Stampede', 'Territorial Roar'],
    bt: { Sense: 'Scent 12m', Attack: 'Charge and gore', Special: 'Territorial roar aggros player' } }),
  e({ id: 'storm-beast', label: 'Storm Beast', icon: Skull, color: ACCENT_PURPLE,
    cls: 'Apex', role: 'melee', cat: 'Beast', tier: 'elite', area: 'Malachor V',
    hp: 70, atk: 62, def: 50, spd: 45, int: 18,
    abilities: ['Lightning Claw', 'Storm Roar', 'Force Drain Bite'],
    bt: { Sense: 'Force sense 18m', Attack: 'Lightning-charged strikes', Special: 'Force Drain heals on bite' } }),
  e({ id: 'greater-storm-beast', label: 'Greater Storm Beast', icon: Skull, color: ACCENT_PURPLE,
    cls: 'Apex', role: 'tank', cat: 'Beast', tier: 'boss', area: 'Malachor V',
    hp: 88, atk: 72, def: 75, spd: 30, int: 22,
    abilities: ['Storm Breath', 'Thunder Slam', 'Lightning Aura', 'Summon Storm Beasts'],
    bt: { Sense: 'Force sense 25m', Attack: 'AoE thunder slam', Special: 'Lightning aura damages nearby 5/s' } }),
  e({ id: 'firaxan-shark', label: 'Firaxan Shark', icon: Skull, color: STATUS_INFO,
    cls: 'Leviathan', role: 'tank', cat: 'Beast', tier: 'boss', area: 'Manaan',
    hp: 92, atk: 78, def: 70, spd: 40, int: 12,
    abilities: ['Crushing Bite', 'Tail Sweep', 'Sonic Pulse', 'Deep Dive'],
    bt: { Sense: 'Sonar 30m', Attack: 'Charge from depth', Special: 'Sonic pulse stuns all 2s' } }),
  e({ id: 'drexl', label: 'Drexl', icon: Skull, color: ACCENT_ORANGE,
    cls: 'Flyer', role: 'melee', cat: 'Beast', tier: 'elite', area: 'Dxun',
    hp: 65, atk: 58, def: 45, spd: 55, int: 12,
    abilities: ['Dive Bomb', 'Talon Rend', 'Screech'],
    bt: { Sense: 'Visual 25m', Attack: 'Dive bomb from air', Special: 'Screech fears targets 2s' } }),
  e({ id: 'krayt-dragon', label: 'Krayt Dragon', icon: Skull, color: ACCENT_ORANGE,
    cls: 'Ancient', role: 'tank', cat: 'Beast', tier: 'raid-boss', area: 'Tatooine',
    hp: 100, atk: 90, def: 90, spd: 20, int: 15,
    abilities: ['Tail Sweep', 'Acid Spit', 'Burrow', 'Earthquake Stomp', 'Devour'],
    bt: { Sense: 'Vibration 35m', Attack: 'Multi-phase rotation', Special: 'Burrows underground phase 2' } }),
  e({ id: 'sith-hound', label: 'Sith War Hound', icon: Skull, color: ACCENT_RED,
    cls: 'War Beast', role: 'melee', cat: 'Beast', tier: 'standard', area: 'Korriban',
    hp: 38, atk: 40, def: 25, spd: 65, int: 12,
    abilities: ['Savage Lunge', 'Dark Bite', 'Pack Tactics'],
    bt: { Sense: 'Dark Side sense 10m', Attack: 'Lunge then retreat', Special: 'Pack tactics: +10% ATK per ally' } }),
  e({ id: 'sand-people-banthas', label: 'War Bantha', icon: Shield, color: STATUS_NEUTRAL,
    cls: 'Mount', role: 'tank', cat: 'Beast', tier: 'standard', area: 'Tatooine',
    hp: 55, atk: 25, def: 55, spd: 25, int: 5,
    abilities: ['Trample', 'Tusk Gore', 'Thick Hide'],
    bt: { Sense: 'Scent 10m', Attack: 'Charge and trample', Special: 'Thick hide: 25% damage reduction' } }),
  e({ id: 'gizka-swarm', label: 'Gizka Swarm', icon: Skull, color: STATUS_SUCCESS,
    cls: 'Pest', role: 'swarm', cat: 'Beast', tier: 'minion', area: 'Taris',
    hp: 5, atk: 5, def: 2, spd: 90, int: 2,
    abilities: ['Nibble', 'Overwhelm'],
    bt: { Sense: 'Proximity 5m', Attack: 'Swarm overwhelm', Special: 'Spawns endlessly until nest destroyed' } }),
];

/* ── Droid (14) ───────────────────────────────────────────────────────── */

const DROID: ArchetypeConfig[] = [
  e({ id: 'patrol-droid', label: 'Patrol Droid', icon: Shield, color: STATUS_INFO,
    cls: 'Security', role: 'ranged', cat: 'Droid', tier: 'minion', area: 'Taris',
    hp: 20, atk: 22, def: 18, spd: 45, int: 15,
    abilities: ['Blaster Pistol', 'Alarm Beacon'],
    bt: { Sense: 'Sensor 12m', Attack: 'Fire and alert', Special: 'Alarm beacon summons backup' } }),
  e({ id: 'assault-droid', label: 'Assault Droid', icon: Shield, color: STATUS_INFO,
    cls: 'Military', role: 'ranged', cat: 'Droid', tier: 'standard', area: 'Taris',
    hp: 42, atk: 40, def: 38, spd: 40, int: 25,
    abilities: ['Heavy Blaster', 'Concussion Rocket', 'Shield Matrix'],
    bt: { Sense: 'Sensor 16m', Attack: 'Suppressive fire', Special: 'Shield matrix absorbs 50 damage' } }),
  e({ id: 'hk-assassin', label: 'HK Assassin Droid', icon: Crosshair, color: ACCENT_RED,
    cls: 'Assassin', role: 'ranged', cat: 'Droid', tier: 'elite', area: 'Nar Shaddaa',
    hp: 55, atk: 65, def: 40, spd: 50, int: 60,
    abilities: ['Sniper Protocol', 'Cloaking Device', 'Assassination Protocol', 'Self-Destruct'],
    bt: { Sense: 'Multi-spectrum 22m', Attack: 'Snipe from cloak', Special: 'Self-destruct at 10% HP' } }),
  e({ id: 'security-droid', label: 'Security Droid', icon: Shield, color: STATUS_NEUTRAL,
    cls: 'Security', role: 'ranged', cat: 'Droid', tier: 'standard', area: 'Nar Shaddaa',
    hp: 40, atk: 32, def: 35, spd: 38, int: 20,
    abilities: ['Stun Ray', 'Blaster Arm', 'Lockdown Protocol'],
    bt: { Sense: 'Sensor 14m', Attack: 'Stun then restrain', Special: 'Lockdown seals doors 5s' } }),
  e({ id: 'probe-droid', label: 'Probe Droid', icon: Crosshair, color: STATUS_SUBDUED,
    cls: 'Recon', role: 'ranged', cat: 'Droid', tier: 'minion', area: 'Nar Shaddaa',
    hp: 15, atk: 18, def: 10, spd: 70, int: 30,
    abilities: ['Laser Beam', 'Scan', 'Self-Destruct'],
    bt: { Sense: 'Sensor 20m', Attack: 'Scan then laser', Special: 'Reveals cloaked targets' } }),
  e({ id: 'mining-droid', label: 'Mining Droid', icon: Shield, color: STATUS_NEUTRAL,
    cls: 'Industrial', role: 'melee', cat: 'Droid', tier: 'minion', area: 'Peragus',
    hp: 22, atk: 25, def: 20, spd: 35, int: 8,
    abilities: ['Mining Laser', 'Drill Arm'],
    bt: { Sense: 'Sensor 8m', Attack: 'Drill arm strike', Special: 'Mining laser ignores 20% armor' } }),
  e({ id: 'protocol-droid-combat', label: 'Reprogrammed Protocol Droid', icon: Shield, color: STATUS_SUCCESS,
    cls: 'Support', role: 'healer', cat: 'Droid', tier: 'minion', area: 'Peragus',
    hp: 18, atk: 8, def: 12, spd: 40, int: 35,
    abilities: ['Repair Beam', 'Shield Boost', 'Distress Signal'],
    bt: { Sense: 'Sensor 10m', Attack: 'Repair nearest ally', Special: 'Shield boost absorbs 20 damage' } }),
  e({ id: 'sith-war-droid', label: 'Sith War Droid', icon: Shield, color: ACCENT_RED,
    cls: 'Military', role: 'ranged', cat: 'Droid', tier: 'elite', area: 'Star Forge',
    hp: 60, atk: 55, def: 50, spd: 40, int: 30,
    abilities: ['Dual Heavy Blasters', 'Rocket Salvo', 'Energy Shield', 'Overload'],
    bt: { Sense: 'Sensor 18m', Attack: 'Dual blaster barrage', Special: 'Overload: AoE 6m on death' } }),
  e({ id: 'star-forge-drone', label: 'Star Forge Drone', icon: Shield, color: ACCENT_PINK,
    cls: 'Drone', role: 'swarm', cat: 'Droid', tier: 'minion', area: 'Star Forge',
    hp: 12, atk: 15, def: 8, spd: 65, int: 5,
    abilities: ['Laser Pulse', 'Swarm Protocol'],
    bt: { Sense: 'Sensor 10m', Attack: 'Swarm in formation', Special: 'Respawns from forge every 30s' } }),
  e({ id: 'assault-sentinel', label: 'Assault Sentinel', icon: Shield, color: ACCENT_PINK,
    cls: 'Guardian', role: 'tank', cat: 'Droid', tier: 'boss', area: 'Star Forge',
    hp: 85, atk: 60, def: 75, spd: 30, int: 40,
    abilities: ['Plasma Cannon', 'Shield Overcharge', 'Gravity Well', 'Repair Swarm'],
    bt: { Sense: 'Sensor 20m', Attack: 'Plasma cannon barrage', Special: 'Gravity well pulls targets in' } }),
  e({ id: 'czerka-defense-droid', label: 'Czerka Defense Droid', icon: Shield, color: STATUS_WARNING,
    cls: 'Security', role: 'ranged', cat: 'Droid', tier: 'standard', area: 'Citadel Station',
    hp: 38, atk: 35, def: 35, spd: 40, int: 22,
    abilities: ['Blaster Array', 'Stasis Field', 'Overcharge'],
    bt: { Sense: 'Sensor 15m', Attack: 'Blaster array sweep', Special: 'Stasis field immobilizes 2s' } }),
  e({ id: 'military-walker', label: 'Military Walker', icon: Shield, color: MODULE_COLORS.core,
    cls: 'Walker', role: 'tank', cat: 'Droid', tier: 'elite', area: 'Onderon',
    hp: 72, atk: 55, def: 68, spd: 20, int: 25,
    abilities: ['Cannon Blast', 'Stomp', 'Missile Pod', 'Armor Plating'],
    bt: { Sense: 'Sensor 22m', Attack: 'Cannon at range, stomp at melee', Special: 'Armor plating: 40% ranged reduction' } }),
  e({ id: 'maintenance-droid', label: 'Maintenance Droid', icon: Shield, color: STATUS_NEUTRAL,
    cls: 'Utility', role: 'healer', cat: 'Droid', tier: 'minion', area: 'Peragus',
    hp: 15, atk: 5, def: 10, spd: 45, int: 25,
    abilities: ['Repair Torch', 'Patch Up'],
    bt: { Sense: 'Sensor 8m', Attack: 'Repairs nearest droid', Special: 'Heals 5% HP per tick' } }),
  e({ id: 'basilisk-droid', label: 'Basilisk War Droid', icon: Shield, color: ACCENT_CYAN,
    cls: 'War Mount', role: 'tank', cat: 'Droid', tier: 'boss', area: 'Dxun',
    hp: 88, atk: 70, def: 78, spd: 35, int: 30,
    abilities: ['Blaster Cannons', 'Dive Bomb', 'Shrapnel Burst', 'Shield Matrix'],
    bt: { Sense: 'Multi-spectrum 25m', Attack: 'Aerial strafing run', Special: 'Dive bomb 12m AoE' } }),
];

/* ── Force-sensitive (16) ─────────────────────────────────────────────── */

const FORCE_SENSITIVE: ArchetypeConfig[] = [
  e({ id: 'sith-acolyte', label: 'Sith Acolyte', icon: Swords, color: ACCENT_RED,
    cls: 'Acolyte', role: 'caster', cat: 'Force-sensitive', tier: 'standard', area: 'Korriban',
    hp: 35, atk: 30, def: 25, spd: 45, int: 42,
    abilities: ['Force Lightning', 'Lightsaber Slash', 'Force Push'],
    bt: { Sense: 'Force sense 12m', Attack: 'Force lightning then melee', Special: 'Force push knockback 5m' } }),
  e({ id: 'sith-lord', label: 'Sith Lord', icon: Swords, color: ACCENT_RED,
    cls: 'Sith Lord', role: 'caster', cat: 'Force-sensitive', tier: 'boss', area: 'Korriban',
    hp: 82, atk: 70, def: 60, spd: 40, int: 80,
    abilities: ['Force Storm', 'Lightsaber Mastery', 'Force Drain', 'Death Field'],
    bt: { Sense: 'Force omniscience 20m', Attack: 'Force storm opener', Special: 'Death field AoE heal on hit' } }),
  e({ id: 'sith-sorcerer', label: 'Sith Sorcerer', icon: Crosshair, color: ACCENT_PURPLE_BOLD,
    cls: 'Sorcerer', role: 'caster', cat: 'Force-sensitive', tier: 'elite', area: 'Korriban',
    hp: 48, atk: 25, def: 30, spd: 35, int: 70,
    abilities: ['Force Lightning', 'Force Horror', 'Dark Healing', 'Sith Alchemy'],
    bt: { Sense: 'Force sense 18m', Attack: 'Ranged Force attacks', Special: 'Force horror fears all 3s' } }),
  e({ id: 'darth-bandon', label: 'Darth Bandon', icon: Swords, color: ACCENT_PINK,
    cls: 'Sith Apprentice', role: 'melee', cat: 'Force-sensitive', tier: 'boss', area: 'Star Forge',
    hp: 78, atk: 72, def: 55, spd: 50, int: 65,
    abilities: ['Double-Bladed Saber', 'Force Wave', 'Force Choke', 'Dark Rage'],
    bt: { Sense: 'Force sense 20m', Attack: 'Aggressive saber combos', Special: 'Dark Rage: +30% ATK below 40% HP' } }),
  e({ id: 'darth-sion', label: 'Darth Sion', icon: Swords, color: ACCENT_PINK,
    cls: 'Lord of Pain', role: 'melee', cat: 'Force-sensitive', tier: 'raid-boss', area: 'Malachor V',
    hp: 98, atk: 88, def: 80, spd: 40, int: 70,
    abilities: ['Pain Empowerment', 'Force Crush', 'Lightsaber Mastery', 'Undying Rage', 'Force Scream'],
    bt: { Sense: 'Force omniscience 25m', Attack: 'Relentless saber assault', Special: 'Revives 3 times before final defeat' } }),
  e({ id: 'darth-nihilus', label: 'Darth Nihilus', icon: Swords, color: ACCENT_PURPLE,
    cls: 'Lord of Hunger', role: 'caster', cat: 'Force-sensitive', tier: 'raid-boss', area: 'Malachor V',
    hp: 95, atk: 70, def: 75, spd: 35, int: 100,
    abilities: ['Force Drain', 'Mass Force Drain', 'Lightsaber Mastery', 'Void Aura', 'Consume Force'],
    bt: { Sense: 'Force hunger 40m', Attack: 'Mass Force drain opener', Special: 'Void aura: constant damage in 8m' } }),
  e({ id: 'fallen-jedi', label: 'Fallen Jedi', icon: Swords, color: MODULE_COLORS.core,
    cls: 'Dark Jedi', role: 'melee', cat: 'Force-sensitive', tier: 'elite', area: 'Dantooine',
    hp: 55, atk: 55, def: 45, spd: 50, int: 50,
    abilities: ['Lightsaber Form III', 'Force Stasis', 'Throw Lightsaber'],
    bt: { Sense: 'Force sense 15m', Attack: 'Defensive then counter', Special: 'Force stasis immobilizes 3s' } }),
  e({ id: 'jedi-guardian', label: 'Jedi Guardian', icon: Swords, color: STATUS_INFO,
    cls: 'Guardian', role: 'melee', cat: 'Force-sensitive', tier: 'elite', area: 'Dantooine',
    hp: 60, atk: 55, def: 55, spd: 45, int: 45,
    abilities: ['Lightsaber Form V', 'Force Leap', 'Force Valor'],
    bt: { Sense: 'Force sense 15m', Attack: 'Force leap opener', Special: 'Force valor buffs allies 20%' } }),
  e({ id: 'jedi-sentinel', label: 'Jedi Sentinel', icon: Swords, color: STATUS_SUCCESS,
    cls: 'Sentinel', role: 'caster', cat: 'Force-sensitive', tier: 'elite', area: 'Dantooine',
    hp: 50, atk: 45, def: 40, spd: 50, int: 58,
    abilities: ['Force Speed', 'Force Stun', 'Lightsaber Throw', 'Battle Meditation'],
    bt: { Sense: 'Force sense 15m', Attack: 'Speed-enhanced strikes', Special: 'Battle meditation buffs party' } }),
  e({ id: 'sith-adept', label: 'Sith Adept', icon: Swords, color: ACCENT_RED,
    cls: 'Adept', role: 'caster', cat: 'Force-sensitive', tier: 'standard', area: 'Onderon',
    hp: 32, atk: 28, def: 22, spd: 45, int: 40,
    abilities: ['Force Lightning', 'Force Push', 'Dark Side Burst'],
    bt: { Sense: 'Force sense 12m', Attack: 'Force lightning spam', Special: 'Dark side burst AoE 4m' } }),
  e({ id: 'dark-marauder', label: 'Dark Side Marauder', icon: Swords, color: ACCENT_PINK,
    cls: 'Marauder', role: 'melee', cat: 'Force-sensitive', tier: 'elite', area: 'Onderon',
    hp: 58, atk: 65, def: 35, spd: 55, int: 40,
    abilities: ['Dual Saber Fury', 'Force Rage', 'Whirlwind Strike'],
    bt: { Sense: 'Force sense 14m', Attack: 'Rage-fueled dual saber', Special: 'Whirlwind strike hits all in 3m' } }),
  e({ id: 'sith-phantom', label: 'Sith Phantom', icon: Skull, color: ACCENT_PURPLE,
    cls: 'Phantom', role: 'caster', cat: 'Force-sensitive', tier: 'elite', area: 'Malachor V',
    hp: 45, atk: 40, def: 30, spd: 55, int: 65,
    abilities: ['Phantom Strike', 'Phase Walk', 'Force Horror', 'Dark Side Bolt'],
    bt: { Sense: 'Force sense 18m', Attack: 'Phase in, strike, phase out', Special: 'Phase walk: immune for 2s' } }),
  e({ id: 'void-spawn', label: 'Void Spawn', icon: Skull, color: ACCENT_PURPLE_BOLD,
    cls: 'Aberration', role: 'caster', cat: 'Force-sensitive', tier: 'standard', area: 'Malachor V',
    hp: 30, atk: 35, def: 20, spd: 50, int: 45,
    abilities: ['Void Bolt', 'Entropy Field', 'Warp'],
    bt: { Sense: 'Void sense 12m', Attack: 'Void bolt barrage', Special: 'Entropy field slows all in 5m' } }),
  e({ id: 'dark-jedi-master', label: 'Dark Jedi Master', icon: Swords, color: ACCENT_RED,
    cls: 'Master', role: 'caster', cat: 'Force-sensitive', tier: 'boss', area: 'Star Forge',
    hp: 80, atk: 68, def: 60, spd: 42, int: 78,
    abilities: ['Force Storm', 'Lightsaber Mastery', 'Force Barrier', 'Dominate Mind'],
    bt: { Sense: 'Force omniscience 22m', Attack: 'Force storm then saber rush', Special: 'Force barrier: immune 5s, 30s CD' } }),
  e({ id: 'force-witch', label: 'Nightsister Force Witch', icon: Crosshair, color: ACCENT_EMERALD,
    cls: 'Witch', role: 'healer', cat: 'Force-sensitive', tier: 'elite', area: 'Dathomir',
    hp: 45, atk: 20, def: 30, spd: 40, int: 65,
    abilities: ['Force Heal', 'Plague of Insects', 'Dark Side Barrier', 'Resurrect'],
    bt: { Sense: 'Force sense 15m', Attack: 'Heals and curses', Special: 'Resurrect: revives fallen ally once' } }),
  e({ id: 'inquisitor', label: 'Sith Inquisitor', icon: Crosshair, color: ACCENT_PURPLE_BOLD,
    cls: 'Inquisitor', role: 'caster', cat: 'Force-sensitive', tier: 'elite', area: 'Star Forge',
    hp: 50, atk: 30, def: 35, spd: 40, int: 68,
    abilities: ['Force Drain', 'Mind Probe', 'Lightning Barrage', 'Sith Barrier'],
    bt: { Sense: 'Force sense 18m', Attack: 'Drain then lightning', Special: 'Mind probe: confused 3s' } }),
];

/* ── Undead (12) ──────────────────────────────────────────────────────── */

const UNDEAD: ArchetypeConfig[] = [
  e({ id: 'sith-zombie', label: 'Sith Zombie', icon: Skull, color: STATUS_SUBDUED,
    cls: 'Zombie', role: 'swarm', cat: 'Undead', tier: 'minion', area: 'Korriban',
    hp: 18, atk: 20, def: 8, spd: 30, int: 2,
    abilities: ['Claw Swipe', 'Infectious Bite'],
    bt: { Sense: 'Proximity 6m', Attack: 'Shamble and swipe', Special: 'Infectious bite: 15% plague' } }),
  e({ id: 'risen-warrior', label: 'Risen Sith Warrior', icon: Swords, color: ACCENT_RED,
    cls: 'Risen', role: 'melee', cat: 'Undead', tier: 'standard', area: 'Korriban',
    hp: 42, atk: 40, def: 35, spd: 30, int: 15,
    abilities: ['Ancient Blade', 'Undying Will', 'Sith Fury'],
    bt: { Sense: 'Dark Side sense 10m', Attack: 'Relentless blade strikes', Special: 'Undying will: revives once at 30% HP' } }),
  e({ id: 'spectral-guardian', label: 'Spectral Guardian', icon: Shield, color: ACCENT_PURPLE,
    cls: 'Guardian', role: 'tank', cat: 'Undead', tier: 'elite', area: 'Korriban',
    hp: 65, atk: 40, def: 60, spd: 25, int: 40,
    abilities: ['Spectral Shield', 'Phase Strike', 'Soul Drain'],
    bt: { Sense: 'Dark Side sense 15m', Attack: 'Phase through attacks', Special: 'Spectral: 50% physical resist' } }),
  e({ id: 'force-ghost', label: 'Malevolent Force Ghost', icon: Skull, color: ACCENT_PURPLE_BOLD,
    cls: 'Spirit', role: 'caster', cat: 'Undead', tier: 'elite', area: 'Malachor V',
    hp: 50, atk: 35, def: 25, spd: 50, int: 70,
    abilities: ['Force Drain', 'Spectral Lightning', 'Possess', 'Phase Shift'],
    bt: { Sense: 'Force sense 20m', Attack: 'Ranged spectral attacks', Special: 'Possess: controls target 4s' } }),
  e({ id: 'corrupted-specter', label: 'Corrupted Specter', icon: Skull, color: ACCENT_PURPLE,
    cls: 'Specter', role: 'caster', cat: 'Undead', tier: 'standard', area: 'Malachor V',
    hp: 30, atk: 32, def: 15, spd: 55, int: 45,
    abilities: ['Shadow Bolt', 'Wail of Anguish', 'Fade'],
    bt: { Sense: 'Dark Side sense 14m', Attack: 'Shadow bolt spam', Special: 'Fade: untargetable 2s' } }),
  e({ id: 'revenant', label: 'Sith Revenant', icon: Swords, color: ACCENT_PINK,
    cls: 'Revenant', role: 'melee', cat: 'Undead', tier: 'elite', area: 'Malachor V',
    hp: 60, atk: 58, def: 45, spd: 40, int: 35,
    abilities: ['Soul Blade', 'Death Grip', 'Unholy Resilience'],
    bt: { Sense: 'Dark Side sense 12m', Attack: 'Soul blade combos', Special: 'Unholy resilience: heals 3% per kill' } }),
  e({ id: 'reanimated-trooper', label: 'Reanimated Trooper', icon: Skull, color: STATUS_SUBDUED,
    cls: 'Undead', role: 'swarm', cat: 'Undead', tier: 'minion', area: 'Star Forge',
    hp: 15, atk: 18, def: 10, spd: 35, int: 3,
    abilities: ['Rusty Blade', 'Grab'],
    bt: { Sense: 'Proximity 6m', Attack: 'Shamble and grab', Special: 'Grab immobilizes 1s' } }),
  e({ id: 'dark-wraith', label: 'Dark Side Wraith', icon: Skull, color: ACCENT_PURPLE_BOLD,
    cls: 'Wraith', role: 'caster', cat: 'Undead', tier: 'standard', area: 'Star Forge',
    hp: 32, atk: 35, def: 18, spd: 50, int: 48,
    abilities: ['Life Drain', 'Dark Screech', 'Shadow Walk'],
    bt: { Sense: 'Dark Side sense 16m', Attack: 'Life drain at range', Special: 'Shadow walk: invisible 3s' } }),
  e({ id: 'shadow-stalker', label: 'Shadow Stalker', icon: Skull, color: STATUS_SUBDUED,
    cls: 'Stalker', role: 'melee', cat: 'Undead', tier: 'standard', area: 'Kashyyyk',
    hp: 38, atk: 42, def: 22, spd: 55, int: 20,
    abilities: ['Shadow Strike', 'Vanish', 'Creeping Dread'],
    bt: { Sense: 'Dark Side sense 14m', Attack: 'Vanish then backstab', Special: 'Creeping dread: -20% SPD' } }),
  e({ id: 'wookiee-revenant', label: 'Wookiee Revenant', icon: Shield, color: ACCENT_ORANGE,
    cls: 'Revenant', role: 'tank', cat: 'Undead', tier: 'elite', area: 'Kashyyyk',
    hp: 68, atk: 52, def: 55, spd: 30, int: 12,
    abilities: ['Cursed Grip', 'Undead Roar', 'Soul Rend'],
    bt: { Sense: 'Proximity 10m', Attack: 'Grab and crush', Special: 'Undead roar fears targets 3s' } }),
  e({ id: 'ancient-guardian', label: 'Ancient Guardian Spirit', icon: Skull, color: STATUS_INFO,
    cls: 'Ancient', role: 'caster', cat: 'Undead', tier: 'boss', area: 'Dantooine',
    hp: 78, atk: 55, def: 60, spd: 30, int: 75,
    abilities: ['Force Storm', 'Guardian Barrier', 'Soul Judgment', 'Summon Spirits'],
    bt: { Sense: 'Force omniscience 25m', Attack: 'Force storm + summons', Special: 'Guardian barrier: immune 6s' } }),
  e({ id: 'crystal-phantom', label: 'Crystal Cave Phantom', icon: Skull, color: ACCENT_CYAN,
    cls: 'Phantom', role: 'caster', cat: 'Undead', tier: 'standard', area: 'Dantooine',
    hp: 28, atk: 30, def: 20, spd: 50, int: 42,
    abilities: ['Crystal Shard', 'Phase Shift', 'Cold Aura'],
    bt: { Sense: 'Crystal resonance 12m', Attack: 'Crystal shard barrage', Special: 'Cold aura slows 15% in 5m' } }),
];

/* ── All expanded archetypes ─────────────────────────────────────────── */

export const EXPANDED_ARCHETYPES: ArchetypeConfig[] = [
  ...HUMANOID,
  ...BEAST,
  ...DROID,
  ...FORCE_SENSITIVE,
  ...UNDEAD,
];

/* ── Expanded BT Tree (50+ nodes) ────────────────────────────────────── */

export interface BtTreeNode {
  id: string;
  label: string;
  shape: 'diamond' | 'rect' | 'rounded' | 'hexagon';
  active: boolean;
  details: string;
  children: string[];
}

export const BT_TREE: BtTreeNode[] = [
  /* Root */
  { id: 'root', label: 'Root', shape: 'diamond', active: true, details: 'Root Selector: evaluates children left-to-right. First success wins.', children: ['emergency', 'combat', 'patrol', 'investigate'] },
  /* Emergency subtree */
  { id: 'emergency', label: 'Emergency', shape: 'rect', active: false, details: 'Self-preservation sequence: triggers when HP is critically low.', children: ['dec-low-hp', 'find-cover', 'use-heal', 'flee'] },
  { id: 'dec-low-hp', label: 'LowHP?', shape: 'hexagon', active: false, details: 'Decorator: checks if HP < 20%. Returns failure if healthy.', children: [] },
  { id: 'find-cover', label: 'FindCover', shape: 'rounded', active: false, details: 'Task: EQS query for nearest cover point within 600cm.', children: [] },
  { id: 'use-heal', label: 'UseHeal', shape: 'rounded', active: false, details: 'Task: activate healing ability if available. Cooldown: 15s.', children: [] },
  { id: 'flee', label: 'Flee', shape: 'rounded', active: false, details: 'Task: run away from threat. Target: max distance point via EQS.', children: [] },
  /* Combat subtree */
  { id: 'combat', label: 'Combat', shape: 'rect', active: true, details: 'Main combat sequence: target → engage → position → teamwork.', children: ['target-acq', 'engagement', 'positioning', 'teamwork'] },
  /* Target acquisition */
  { id: 'target-acq', label: 'TargetAcq', shape: 'diamond', active: true, details: 'Target acquisition selector: find and validate a combat target.', children: ['dec-has-target', 'scan-target', 'req-squad-target'] },
  { id: 'dec-has-target', label: 'HasTarget?', shape: 'hexagon', active: true, details: 'Decorator: checks blackboard for valid target (not null, alive, in range).', children: [] },
  { id: 'scan-target', label: 'ScanTarget', shape: 'rounded', active: false, details: 'Task: use perception to scan for nearest hostile. Scan radius: 1200cm.', children: [] },
  { id: 'req-squad-target', label: 'AskSquad', shape: 'rounded', active: false, details: 'Task: request target from squad leader AI. Fallback when alone.', children: [] },
  /* Engagement */
  { id: 'engagement', label: 'Engagement', shape: 'diamond', active: true, details: 'Engagement selector: choose melee, ranged, or force combat style.', children: ['melee-engage', 'ranged-engage', 'force-engage'] },
  /* Melee engagement */
  { id: 'melee-engage', label: 'MeleeSeq', shape: 'rect', active: true, details: 'Melee engagement sequence: close distance then attack.', children: ['dec-melee-range', 'attack-choice', 'close-melee'] },
  { id: 'dec-melee-range', label: 'InMelee?', shape: 'hexagon', active: true, details: 'Decorator: checks distance < MeleeRange (200cm default).', children: [] },
  { id: 'attack-choice', label: 'AttackSel', shape: 'diamond', active: true, details: 'Attack choice selector: combo > heavy > light priority.', children: ['dec-can-combo', 'exec-combo', 'heavy-attack', 'light-attack'] },
  { id: 'dec-can-combo', label: 'CanCombo?', shape: 'hexagon', active: true, details: 'Decorator: checks combo meter >= 3 and all abilities off cooldown.', children: [] },
  { id: 'exec-combo', label: 'ExecCombo', shape: 'rounded', active: true, details: 'Task: execute 3-hit combo chain. Damage: 2.5x base. Animation: AM_Combo_01.', children: [] },
  { id: 'heavy-attack', label: 'HeavyATK', shape: 'rounded', active: false, details: 'Task: charged heavy attack. Damage: 1.8x base. Cooldown: 3s.', children: [] },
  { id: 'light-attack', label: 'LightATK', shape: 'rounded', active: false, details: 'Task: quick light attack. Damage: 1.0x base. Cooldown: 0.8s.', children: [] },
  { id: 'close-melee', label: 'CloseDist', shape: 'rounded', active: false, details: 'Task: sprint toward target using NavMesh. Speed: 1.5x base.', children: [] },
  /* Ranged engagement */
  { id: 'ranged-engage', label: 'RangedSeq', shape: 'rect', active: false, details: 'Ranged engagement sequence: maintain distance and fire.', children: ['dec-ranged-range', 'dec-los', 'ranged-attack-sel', 'find-fire-pos'] },
  { id: 'dec-ranged-range', label: 'InRange?', shape: 'hexagon', active: false, details: 'Decorator: checks distance < MaxRange (1500cm) and > MinRange (400cm).', children: [] },
  { id: 'dec-los', label: 'HasLOS?', shape: 'hexagon', active: false, details: 'Decorator: line-of-sight trace check to target. Fails if behind cover.', children: [] },
  { id: 'ranged-attack-sel', label: 'RangedSel', shape: 'diamond', active: false, details: 'Ranged attack choice selector: AoE > single-target.', children: ['dec-can-aoe', 'cast-aoe', 'fire-projectile'] },
  { id: 'dec-can-aoe', label: 'CanAoE?', shape: 'hexagon', active: false, details: 'Decorator: checks if 3+ enemies in 5m cluster. Cooldown: 8s.', children: [] },
  { id: 'cast-aoe', label: 'CastAoE', shape: 'rounded', active: false, details: 'Task: cast area-of-effect ability. Radius: 500cm. Damage: 0.6x to all.', children: [] },
  { id: 'fire-projectile', label: 'FireProj', shape: 'rounded', active: false, details: 'Task: fire single projectile. Speed: 2000cm/s. Damage: 1.2x base.', children: [] },
  { id: 'find-fire-pos', label: 'FindFire', shape: 'rounded', active: false, details: 'Task: EQS query for firing position with LOS and cover.', children: [] },
  /* Force engagement */
  { id: 'force-engage', label: 'ForceSeq', shape: 'rect', active: false, details: 'Force abilities sequence: use Force pool for devastating attacks.', children: ['dec-force-pool', 'force-push', 'force-lightning', 'force-heal'] },
  { id: 'dec-force-pool', label: 'HasForce?', shape: 'hexagon', active: false, details: 'Decorator: checks Force pool >= 20%. Regenerates 5% per second.', children: [] },
  { id: 'force-push', label: 'ForcePush', shape: 'rounded', active: false, details: 'Task: Force Push. Cost: 15%. Knockback: 8m. Cooldown: 6s.', children: [] },
  { id: 'force-lightning', label: 'Lightning', shape: 'rounded', active: false, details: 'Task: Force Lightning. Cost: 25%. Channeled 2s. DPS: 2x base.', children: [] },
  { id: 'force-heal', label: 'ForceHeal', shape: 'rounded', active: false, details: 'Task: Force Heal. Cost: 30%. Heals 25% max HP. Cooldown: 20s.', children: [] },
  /* Positioning */
  { id: 'positioning', label: 'Positioning', shape: 'diamond', active: false, details: 'Positioning selector: flank, maintain distance, or circle strafe.', children: ['flank', 'maintain-dist', 'circle-strafe'] },
  { id: 'flank', label: 'Flank', shape: 'rounded', active: false, details: 'Task: move to flanking position via EQS. Bonus: +30% crit from behind.', children: [] },
  { id: 'maintain-dist', label: 'KeepDist', shape: 'rounded', active: false, details: 'Task: maintain optimal range. Kite if too close, advance if too far.', children: [] },
  { id: 'circle-strafe', label: 'Strafe', shape: 'rounded', active: false, details: 'Task: circle around target while attacking. Evades 20% more.', children: [] },
  /* Teamwork */
  { id: 'teamwork', label: 'Teamwork', shape: 'diamond', active: false, details: 'Teamwork selector: coordinate with allies for group tactics.', children: ['dec-has-allies', 'coord-attack', 'support-ally', 'call-reinforcements'] },
  { id: 'dec-has-allies', label: 'HasAllies?', shape: 'hexagon', active: false, details: 'Decorator: checks if 2+ allies within 1000cm. Returns failure if solo.', children: [] },
  { id: 'coord-attack', label: 'CoordATK', shape: 'rounded', active: false, details: 'Task: coordinate attack timing with allies. Simultaneous strike: +50% damage.', children: [] },
  { id: 'support-ally', label: 'Support', shape: 'rounded', active: false, details: 'Task: heal or buff nearest ally below 50% HP. Priority: healers > DPS.', children: [] },
  { id: 'call-reinforcements', label: 'CallHelp', shape: 'rounded', active: false, details: 'Task: signal for reinforcements. Spawns 2 minions after 5s delay.', children: [] },
  /* Patrol subtree */
  { id: 'patrol', label: 'Patrol', shape: 'rect', active: false, details: 'Patrol sequence: follow waypoints or wander, with lookout pauses.', children: ['patrol-choice', 'look-around', 'idle-anim'] },
  { id: 'patrol-choice', label: 'PatrolSel', shape: 'diamond', active: false, details: 'Patrol choice selector: waypoints if available, else random wander.', children: ['dec-has-waypoints', 'follow-waypoints', 'random-wander'] },
  { id: 'dec-has-waypoints', label: 'Waypts?', shape: 'hexagon', active: false, details: 'Decorator: checks if patrol waypoint spline is assigned in blackboard.', children: [] },
  { id: 'follow-waypoints', label: 'Waypoints', shape: 'rounded', active: false, details: 'Task: follow waypoint spline loop. Speed: 0.5x base. Pause: 2-4s each.', children: [] },
  { id: 'random-wander', label: 'Wander', shape: 'rounded', active: false, details: 'Task: random point in 600cm radius via EQS. Idle 2-4s between moves.', children: [] },
  { id: 'look-around', label: 'LookAround', shape: 'rounded', active: false, details: 'Task: rotate head/body to scan surroundings. Duration: 1-3s.', children: [] },
  { id: 'idle-anim', label: 'Idle', shape: 'rounded', active: false, details: 'Task: play idle animation variant. Random: scratch, stretch, yawn.', children: [] },
  /* Investigation subtree */
  { id: 'investigate', label: 'Investigate', shape: 'rect', active: false, details: 'Investigation sequence: respond to suspicious stimuli.', children: ['dec-heard-noise', 'move-investigate', 'search-area', 'return-patrol'] },
  { id: 'dec-heard-noise', label: 'Noise?', shape: 'hexagon', active: false, details: 'Decorator: checks if hearing stimulus registered in last 5s.', children: [] },
  { id: 'move-investigate', label: 'GoToNoise', shape: 'rounded', active: false, details: 'Task: move to last known stimulus location. Speed: 0.8x base. Alert stance.', children: [] },
  { id: 'search-area', label: 'Search', shape: 'rounded', active: false, details: 'Task: search 400cm radius around stimulus point. Duration: 8s.', children: [] },
  { id: 'return-patrol', label: 'Return', shape: 'rounded', active: false, details: 'Task: return to last patrol waypoint. Speed: normal. Lower alert.', children: [] },
];

/* ── Expanded Wave Timeline (24 waves) ───────────────────────────────── */

export interface ExpandedWaveConfig {
  id: number;
  delay: string;
  count: number;
  archetype: string;
  tier: string;
  area: string;
}

export const EXPANDED_WAVES: ExpandedWaveConfig[] = [
  { id: 1, delay: '0s', count: 4, archetype: 'Rakghoul', tier: 'minion', area: 'Taris' },
  { id: 2, delay: '30s', count: 3, archetype: 'Sith Trooper', tier: 'standard', area: 'Taris' },
  { id: 3, delay: '60s', count: 6, archetype: 'Kath Hound', tier: 'minion', area: 'Dantooine' },
  { id: 4, delay: '90s', count: 2, archetype: 'Gamorrean Guard', tier: 'standard', area: 'Taris' },
  { id: 5, delay: '120s', count: 5, archetype: 'Shyrack', tier: 'minion', area: 'Korriban' },
  { id: 6, delay: '150s', count: 3, archetype: 'Kinrath', tier: 'standard', area: 'Kashyyyk' },
  { id: 7, delay: '180s', count: 2, archetype: 'Sith Acolyte', tier: 'standard', area: 'Korriban' },
  { id: 8, delay: '210s', count: 4, archetype: 'Exchange Thug', tier: 'minion', area: 'Nar Shaddaa' },
  { id: 9, delay: '240s', count: 1, archetype: 'Bounty Hunter', tier: 'elite', area: 'Nar Shaddaa' },
  { id: 10, delay: '270s', count: 3, archetype: 'Mandalorian Scout', tier: 'elite', area: 'Dantooine' },
  { id: 11, delay: '300s', count: 5, archetype: 'Sith Zombie', tier: 'minion', area: 'Korriban' },
  { id: 12, delay: '330s', count: 2, archetype: 'HK Assassin Droid', tier: 'elite', area: 'Nar Shaddaa' },
  { id: 13, delay: '360s', count: 6, archetype: 'Star Forge Drone', tier: 'minion', area: 'Star Forge' },
  { id: 14, delay: '390s', count: 2, archetype: 'Sith Sorcerer', tier: 'elite', area: 'Korriban' },
  { id: 15, delay: '420s', count: 1, archetype: 'Mandalorian Captain', tier: 'boss', area: 'Dxun' },
  { id: 16, delay: '450s', count: 3, archetype: 'Fallen Jedi', tier: 'elite', area: 'Dantooine' },
  { id: 17, delay: '480s', count: 4, archetype: 'Reanimated Trooper', tier: 'minion', area: 'Star Forge' },
  { id: 18, delay: '510s', count: 2, archetype: 'Sith War Droid', tier: 'elite', area: 'Star Forge' },
  { id: 19, delay: '540s', count: 1, archetype: 'Terentatek', tier: 'boss', area: 'Korriban' },
  { id: 20, delay: '570s', count: 2, archetype: 'Dark Marauder', tier: 'elite', area: 'Onderon' },
  { id: 21, delay: '600s', count: 1, archetype: 'Dark Jedi Master', tier: 'boss', area: 'Star Forge' },
  { id: 22, delay: '630s', count: 8, archetype: 'Gizka Swarm', tier: 'minion', area: 'Taris' },
  { id: 23, delay: '660s', count: 1, archetype: 'Assault Sentinel', tier: 'boss', area: 'Star Forge' },
  { id: 24, delay: '700s', count: 1, archetype: 'Darth Malak', tier: 'raid-boss', area: 'Star Forge' },
];
