import {
  drCurveTableCSV, drCurveTableName, DR_CURVE_TABLE_DIR, type DRConfig,
} from '@/components/modules/core-engine/sub_progression/_shared/diminishingReturns';

/** One UCurveTable CSV for every attribute (see drCurveTableCSV). */
export function generateCurveTableCSV(configs: DRConfig[]): string {
  return drCurveTableCSV(configs);
}

export function generateGEHeader(configs: DRConfig[]): string {
  return `#pragma once

#include "CoreMinimal.h"
#include "GameplayEffect.h"
#include "GE_AttributeScaling.generated.h"

class UCurveTable;

/**
 * Gameplay Effect that applies diminishing returns to attribute scaling.
 *
 * Reads the current allocated points for each attribute and applies
 * a curve-table multiplier to the per-point bonus. Below the soft cap,
 * scaling is 1:1. Above the soft cap, returns diminish according to
 * the AttributeName row of the referenced UCurveTable; a missing table
 * or row falls back to the same linear falloff the curve was sampled from.
 *
 * Generated by PoF Diminishing Returns Code Generator.
 */
UCLASS()
class POF_API UGE_AttributeScaling : public UGameplayEffect
{
\tGENERATED_BODY()

public:
\tUGE_AttributeScaling();
};

/**
 * Static helper for computing diminished attribute values at runtime.
 * Used by UI previews and the GE magnitude calculation.
 */
USTRUCT(BlueprintType)
struct POF_API FDiminishingReturnsConfig
{
\tGENERATED_BODY()

\tUPROPERTY(EditAnywhere, BlueprintReadWrite)
\tFName AttributeName;

\tUPROPERTY(EditAnywhere, BlueprintReadWrite, meta = (ClampMin = "1"))
\tint32 SoftCap = 50;

\tUPROPERTY(EditAnywhere, BlueprintReadWrite)
\tfloat BaseValuePerPoint = 1.f;

\tUPROPERTY(EditAnywhere, BlueprintReadWrite, meta = (ClampMin = "0.0", ClampMax = "1.0"))
\tfloat PostCapMultiplier = 0.4f;

\tUPROPERTY(EditAnywhere, BlueprintReadWrite)
\tTObjectPtr<UCurveTable> ScalingCurve;

\t/** Compute effective bonus for the given number of allocated points. */
\tfloat GetEffectiveBonus(int32 AllocatedPoints) const;
};`;
}

export function generateGESource(configs: DRConfig[]): string {
  const modifierBlocks = configs.map((c, i) => {
    const attrMap: Record<string, string> = {
      Strength: 'UARPGAttributeSet::GetAttackPowerAttribute()',
      Dexterity: 'UARPGAttributeSet::GetCriticalChanceAttribute()',
      Intelligence: 'UARPGAttributeSet::GetMaxManaAttribute()',
    };
    return `\t// ${c.attribute}: base ${c.baseValuePerPoint} per point, soft cap ${c.softCap}
\t{
\t\tFGameplayModifierInfo& Mod = Modifiers[${i}];
\t\tMod.Attribute = ${attrMap[c.attribute] ?? `UARPGAttributeSet::Get${c.attribute}Attribute()`};
\t\tMod.ModifierOp = EGameplayModOp::Additive;
\t\tMod.ModifierMagnitude = FGameplayEffectModifierMagnitude(
\t\t\tFSetByCallerFloat(ARPGGameplayTags::Data_${c.attribute}_Bonus));
\t}`;
  }).join('\n\n');

  return `#include "AbilitySystem/Effects/GE_AttributeScaling.h"
#include "AbilitySystem/ARPGAttributeSet.h"
#include "ARPGGameplayTags.h"

UGE_AttributeScaling::UGE_AttributeScaling()
{
\tDurationPolicy = EGameplayEffectDurationType::Infinite;
\tStackingType = EGameplayEffectStackingType::AggregateByTarget;

\tModifiers.SetNum(${configs.length});

${modifierBlocks}
}

float FDiminishingReturnsConfig::GetEffectiveBonus(int32 AllocatedPoints) const
{
\tif (AllocatedPoints <= 0) return 0.f;

\tfloat TotalBonus = 0.f;

\t// Points up to soft cap: full value
\tconst int32 PreCapPoints = FMath::Min(AllocatedPoints, SoftCap);
\tTotalBonus += PreCapPoints * BaseValuePerPoint;

\t// Points beyond soft cap: the AttributeName row of ScalingCurve, or - when the
\t// table or the row is missing - the same linear falloff the curve samples.
\tif (AllocatedPoints > SoftCap)
\t{
\t\tconst int32 PostCapPoints = AllocatedPoints - SoftCap;
\t\tconst float MaxOverCap = 100.f - SoftCap;
\t\tconst FRealCurve* Curve = ScalingCurve ? ScalingCurve->FindCurve(AttributeName, TEXT("GetEffectiveBonus"), false) : nullptr;
\t\tfor (int32 i = 1; i <= PostCapPoints; ++i)
\t\t{
\t\t\tconst float LookupKey = static_cast<float>(SoftCap + i);
\t\t\tconst float T = MaxOverCap > 0.f ? FMath::Min(static_cast<float>(i) / MaxOverCap, 1.f) : 1.f;
\t\t\tconst float Falloff = FMath::Lerp(1.f, PostCapMultiplier, T);
\t\t\tconst float Mult = Curve ? Curve->Eval(LookupKey) : Falloff;
\t\t\tTotalBonus += BaseValuePerPoint * Mult;
\t\t}
\t}

\treturn TotalBonus;
}`;
}

/**
 * DataTable rows for FDiminishingReturnsConfig. Field names match the struct's
 * UPROPERTYs, AttributeName names the CSV row FindCurve looks up, and every row
 * references the one curve table the CSV is imported as.
 */
export function generateDataTableJSON(configs: DRConfig[]): string {
  const table = drCurveTableName(configs);
  const entries = configs.map(c => ({
    Name: c.attribute,
    AttributeName: c.attribute,
    SoftCap: c.softCap,
    BaseValuePerPoint: c.baseValuePerPoint,
    PostCapMultiplier: c.postCapMultiplier,
    ScalingCurve: `${DR_CURVE_TABLE_DIR}/${table}.${table}`,
  }));
  return JSON.stringify(entries, null, 2);
}
