import type { DRConfig } from './constants';

export function generateCurveTableCSV(config: DRConfig): string {
  const rows: string[] = ['Points,Multiplier'];
  for (let pts = 0; pts <= 100; pts += 5) {
    let mult: number;
    if (pts <= config.softCap) {
      mult = 1.0;
    } else {
      const over = pts - config.softCap;
      const maxOver = 100 - config.softCap;
      const t = over / maxOver;
      mult = 1.0 - (1.0 - config.postCapMultiplier) * t;
    }
    rows.push(`${pts},${mult.toFixed(4)}`);
  }
  return rows.join('\n');
}

export function generateGEHeader(configs: DRConfig[]): string {
  return `#pragma once

#include "CoreMinimal.h"
#include "GameplayEffect.h"
#include "GE_AttributeScaling.generated.h"

class UCurveTable;

/**
 * Gameplay Effect that applies diminishing returns to attribute scaling.
 *
 * Reads the current allocated points for each attribute and applies
 * a curve-table multiplier to the per-point bonus. Below the soft cap,
 * scaling is 1:1. Above the soft cap, returns diminish according to
 * the referenced UCurveTable.
 *
 * Generated by PoF Diminishing Returns Code Generator.
 */
UCLASS()
class POF_API UGE_AttributeScaling : public UGameplayEffect
{
\tGENERATED_BODY()

public:
\tUGE_AttributeScaling();
};

/**
 * Static helper for computing diminished attribute values at runtime.
 * Used by UI previews and the GE magnitude calculation.
 */
USTRUCT(BlueprintType)
struct POF_API FDiminishingReturnsConfig
{
\tGENERATED_BODY()

\tUPROPERTY(EditAnywhere, BlueprintReadWrite)
\tFName AttributeName;

\tUPROPERTY(EditAnywhere, BlueprintReadWrite, meta = (ClampMin = "1"))
\tint32 SoftCap = 50;

\tUPROPERTY(EditAnywhere, BlueprintReadWrite)
\tfloat BaseValuePerPoint = 1.f;

\tUPROPERTY(EditAnywhere, BlueprintReadWrite, meta = (ClampMin = "0.0", ClampMax = "1.0"))
\tfloat PostCapMultiplier = 0.4f;

\tUPROPERTY(EditAnywhere, BlueprintReadWrite)
\tTObjectPtr<UCurveTable> ScalingCurve;

\t/** Compute effective bonus for the given number of allocated points. */
\tfloat GetEffectiveBonus(int32 AllocatedPoints) const;
};`;
}

export function generateGESource(configs: DRConfig[]): string {
  const modifierBlocks = configs.map((c, i) => {
    const attrMap: Record<string, string> = {
      Strength: 'UARPGAttributeSet::GetAttackPowerAttribute()',
      Dexterity: 'UARPGAttributeSet::GetCriticalChanceAttribute()',
      Intelligence: 'UARPGAttributeSet::GetMaxManaAttribute()',
    };
    return `\t// ${c.attribute}: base ${c.baseValuePerPoint} per point, soft cap ${c.softCap}
\t{
\t\tFGameplayModifierInfo& Mod = Modifiers[${i}];
\t\tMod.Attribute = ${attrMap[c.attribute] ?? `UARPGAttributeSet::Get${c.attribute}Attribute()`};
\t\tMod.ModifierOp = EGameplayModOp::Additive;
\t\tMod.ModifierMagnitude = FGameplayEffectModifierMagnitude(
\t\t\tFSetByCallerFloat(ARPGGameplayTags::Data_${c.attribute}_Bonus));
\t}`;
  }).join('\n\n');

  return `#include "AbilitySystem/Effects/GE_AttributeScaling.h"
#include "AbilitySystem/ARPGAttributeSet.h"
#include "ARPGGameplayTags.h"

UGE_AttributeScaling::UGE_AttributeScaling()
{
\tDurationPolicy = EGameplayEffectDurationType::Infinite;
\tStackingType = EGameplayEffectStackingType::AggregateByTarget;

\tModifiers.SetNum(${configs.length});

${modifierBlocks}
}

float FDiminishingReturnsConfig::GetEffectiveBonus(int32 AllocatedPoints) const
{
\tif (AllocatedPoints <= 0) return 0.f;

\tfloat TotalBonus = 0.f;

\t// Points up to soft cap: full value
\tconst int32 PreCapPoints = FMath::Min(AllocatedPoints, SoftCap);
\tTotalBonus += PreCapPoints * BaseValuePerPoint;

\t// Points beyond soft cap: diminished value
\tif (AllocatedPoints > SoftCap)
\t{
\t\tconst int32 PostCapPoints = AllocatedPoints - SoftCap;
\t\t// If we have a curve table, sample it; otherwise use linear falloff
\t\tif (ScalingCurve)
\t\t{
\t\t\tfor (int32 i = 1; i <= PostCapPoints; ++i)
\t\t\t{
\t\t\t\tconst float LookupKey = static_cast<float>(SoftCap + i);
\t\t\t\tconst FRealCurve* Curve = ScalingCurve->FindCurve(AttributeName, TEXT("DR"));
\t\t\t\tconst float Mult = Curve ? Curve->Eval(LookupKey) : PostCapMultiplier;
\t\t\t\tTotalBonus += BaseValuePerPoint * Mult;
\t\t\t}
\t\t}
\t\telse
\t\t{
\t\t\t// Linear falloff from 1.0 to PostCapMultiplier
\t\t\tconst float MaxOverCap = 100.f - SoftCap;
\t\t\tfor (int32 i = 1; i <= PostCapPoints; ++i)
\t\t\t{
\t\t\t\tconst float T = static_cast<float>(i) / MaxOverCap;
\t\t\t\tconst float Mult = FMath::Lerp(1.f, PostCapMultiplier, T);
\t\t\t\tTotalBonus += BaseValuePerPoint * Mult;
\t\t\t}
\t\t}
\t}

\treturn TotalBonus;
}`;
}

export function generateDataTableJSON(configs: DRConfig[]): string {
  const entries = configs.map(c => ({
    Name: c.attribute,
    SoftCap: c.softCap,
    BaseValuePerPoint: c.baseValuePerPoint,
    PostCapMultiplier: c.postCapMultiplier,
    CurveTable: `/Game/Data/CurveTables/${c.curveTableName}`,
  }));
  return JSON.stringify(entries, null, 2);
}
