import type { MarketplaceAsset } from '@/types/marketplace';

/**
 * Curated catalog of high-quality UE Marketplace / Fab.com assets
 * organized by the feature gaps they address.
 *
 * In production this would query a live API — for now we use a
 * hand-curated catalog of well-known, highly-rated assets.
 */
export const ASSET_CATALOG: MarketplaceAsset[] = [
  // ── Character & Movement ────────────────────────────────────────────────
  {
    id: 'als-v4',
    name: 'Advanced Locomotion System V4',
    publisher: 'LongmireLocomotion',
    source: 'ue-marketplace',
    category: 'character',
    description: 'Complete third-person locomotion system with overlay states, mantling, ragdoll, and camera modes.',
    rating: 4.8,
    ratingCount: 2400,
    price: 0,
    ueVersions: ['5.3', '5.4', '5.5'],
    hasSource: true,
    gasCompatible: false,
    tags: ['locomotion', 'movement', 'animation', 'mantling', 'ragdoll', 'camera'],
    difficulty: 'adapter',
    integrationTimeMinutes: 90,
  },
  {
    id: 'gmc-movement',
    name: 'General Movement Component',
    publisher: 'Guildmaster Studios',
    source: 'ue-marketplace',
    category: 'character',
    description: 'Modular movement with climbing, swimming, flying, dashing — built for GAS compatibility.',
    rating: 4.9,
    ratingCount: 350,
    price: 49.99,
    ueVersions: ['5.4', '5.5'],
    hasSource: true,
    gasCompatible: true,
    tags: ['movement', 'climbing', 'swimming', 'dash', 'modular', 'gas'],
    difficulty: 'adapter',
    integrationTimeMinutes: 60,
  },

  // ── Animation ───────────────────────────────────────────────────────────
  {
    id: 'motion-symphony',
    name: 'Motion Symphony',
    publisher: 'Motiondynam',
    source: 'ue-marketplace',
    category: 'animation',
    description: 'Motion matching system for fluid, responsive character animation without state machines.',
    rating: 4.7,
    ratingCount: 180,
    price: 79.99,
    ueVersions: ['5.4', '5.5'],
    hasSource: true,
    gasCompatible: false,
    tags: ['motion-matching', 'animation', 'locomotion', 'procedural', 'responsive'],
    difficulty: 'deep-rewrite',
    integrationTimeMinutes: 180,
  },
  {
    id: 'kwl-anim-bp',
    name: 'KawaiiPhysics',
    publisher: 'pafuhana1213',
    source: 'fab',
    category: 'animation',
    description: 'Lightweight physics-based bone animation for hair, tails, cloaks, and accessories.',
    rating: 4.9,
    ratingCount: 600,
    price: 0,
    ueVersions: ['5.3', '5.4', '5.5'],
    hasSource: true,
    gasCompatible: false,
    tags: ['physics', 'bone', 'hair', 'cloth', 'secondary-motion', 'jiggle'],
    difficulty: 'drop-in',
    integrationTimeMinutes: 15,
  },

  // ── GAS / Combat ────────────────────────────────────────────────────────
  {
    id: 'gas-companion',
    name: 'GAS Companion',
    publisher: 'Music Everywhere',
    source: 'ue-marketplace',
    category: 'combat',
    description: 'Bootstrap plugin for GAS: auto-creates ASC, grants abilities, handles attribute init. Saves weeks of boilerplate.',
    rating: 4.8,
    ratingCount: 480,
    price: 39.99,
    ueVersions: ['5.3', '5.4', '5.5'],
    hasSource: true,
    gasCompatible: true,
    tags: ['gas', 'gameplay-abilities', 'attributes', 'bootstrap', 'combat', 'setup'],
    difficulty: 'drop-in',
    integrationTimeMinutes: 30,
  },
  {
    id: 'combo-graph',
    name: 'Combo Graph',
    publisher: 'Music Everywhere',
    source: 'ue-marketplace',
    category: 'combat',
    description: 'Node-based combo editor for GAS. Visual designer for combo trees with input buffering and montage linking.',
    rating: 4.7,
    ratingCount: 200,
    price: 49.99,
    ueVersions: ['5.4', '5.5'],
    hasSource: true,
    gasCompatible: true,
    tags: ['combo', 'combat', 'gas', 'node-graph', 'input-buffer', 'melee'],
    difficulty: 'adapter',
    integrationTimeMinutes: 60,
  },
  {
    id: 'targetlock',
    name: 'Target System',
    publisher: 'Music Everywhere',
    source: 'ue-marketplace',
    category: 'combat',
    description: 'Lock-on target system similar to Dark Souls. Camera-based targeting, widget indicator, auto-switch.',
    rating: 4.6,
    ratingCount: 300,
    price: 0,
    ueVersions: ['5.3', '5.4', '5.5'],
    hasSource: true,
    gasCompatible: true,
    tags: ['targeting', 'lock-on', 'combat', 'camera', 'melee', 'souls-like'],
    difficulty: 'drop-in',
    integrationTimeMinutes: 20,
  },
  {
    id: 'agr-pro',
    name: 'AGR PRO',
    publisher: 'MoLeg Games',
    source: 'ue-marketplace',
    category: 'combat',
    description: 'Anim graph runtime plugin for complex animation layering, blending, and procedural animation.',
    rating: 4.5,
    ratingCount: 250,
    price: 59.99,
    ueVersions: ['5.4', '5.5'],
    hasSource: true,
    gasCompatible: false,
    tags: ['animation', 'combat', 'layering', 'procedural', 'montage'],
    difficulty: 'adapter',
    integrationTimeMinutes: 90,
  },

  // ── Enemy AI ────────────────────────────────────────────────────────────
  {
    id: 'utility-ai',
    name: 'Utility AI Plugin',
    publisher: 'Intrepid Entertainment',
    source: 'fab',
    category: 'ai',
    description: 'Utility-based AI decision system. Replaces behavior trees with scored action selection.',
    rating: 4.6,
    ratingCount: 120,
    price: 0,
    ueVersions: ['5.3', '5.4', '5.5'],
    hasSource: true,
    gasCompatible: false,
    tags: ['ai', 'utility', 'decision-making', 'behavior', 'scoring'],
    difficulty: 'adapter',
    integrationTimeMinutes: 60,
  },
  {
    id: 'smart-ai',
    name: 'Smart AI Plugin',
    publisher: 'Kinetix',
    source: 'ue-marketplace',
    category: 'ai',
    description: 'AI framework with perception, patrol, group coordination, and squad tactics out of the box.',
    rating: 4.4,
    ratingCount: 180,
    price: 44.99,
    ueVersions: ['5.4', '5.5'],
    hasSource: true,
    gasCompatible: false,
    tags: ['ai', 'perception', 'patrol', 'group', 'squad', 'behavior-tree'],
    difficulty: 'adapter',
    integrationTimeMinutes: 90,
  },

  // ── Inventory ───────────────────────────────────────────────────────────
  {
    id: 'lyra-inventory',
    name: 'Common UI + Inventory (Lyra-style)',
    publisher: 'Epic Games',
    source: 'fab',
    category: 'inventory',
    description: 'Epic\'s official Lyra-based modular inventory fragment system with equipment and UI.',
    rating: 4.3,
    ratingCount: 900,
    price: 0,
    ueVersions: ['5.4', '5.5'],
    hasSource: true,
    gasCompatible: true,
    tags: ['inventory', 'equipment', 'modular', 'lyra', 'fragment', 'gas'],
    difficulty: 'deep-rewrite',
    integrationTimeMinutes: 180,
  },
  {
    id: 'ue-inventory-sys',
    name: 'Universal Inventory System',
    publisher: 'Marco Vitale',
    source: 'ue-marketplace',
    category: 'inventory',
    description: 'Complete inventory with grid layout, drag-drop, stacking, splitting, equipment slots, containers, and loot.',
    rating: 4.7,
    ratingCount: 350,
    price: 49.99,
    ueVersions: ['5.3', '5.4', '5.5'],
    hasSource: true,
    gasCompatible: false,
    tags: ['inventory', 'grid', 'drag-drop', 'equipment', 'stacking', 'containers', 'loot'],
    difficulty: 'adapter',
    integrationTimeMinutes: 60,
  },

  // ── UI / HUD ────────────────────────────────────────────────────────────
  {
    id: 'common-ui',
    name: 'CommonUI Plugin',
    publisher: 'Epic Games',
    source: 'fab',
    category: 'ui',
    description: 'Epic\'s official cross-platform UI framework. Input routing, focus navigation, platform-aware widgets.',
    rating: 4.5,
    ratingCount: 500,
    price: 0,
    ueVersions: ['5.3', '5.4', '5.5'],
    hasSource: true,
    gasCompatible: false,
    tags: ['ui', 'hud', 'common-ui', 'gamepad', 'focus', 'platform'],
    difficulty: 'adapter',
    integrationTimeMinutes: 120,
  },
  {
    id: 'flat-nodes-ui',
    name: 'Flat Nodes UI Pack',
    publisher: 'Kinetix',
    source: 'ue-marketplace',
    category: 'ui',
    description: 'RPG-ready UI widget library: health bars, inventory grids, ability bars, minimaps, dialogs.',
    rating: 4.6,
    ratingCount: 220,
    price: 34.99,
    ueVersions: ['5.4', '5.5'],
    hasSource: false,
    gasCompatible: false,
    tags: ['ui', 'hud', 'health-bar', 'minimap', 'inventory-ui', 'ability-bar', 'rpg'],
    difficulty: 'drop-in',
    integrationTimeMinutes: 30,
  },

  // ── Loot ────────────────────────────────────────────────────────────────
  {
    id: 'loot-locker',
    name: 'Loot Locker SDK',
    publisher: 'LootLocker',
    source: 'fab',
    category: 'inventory',
    description: 'Cloud-based loot and item management. Loot tables, virtual currencies, leaderboards.',
    rating: 4.3,
    ratingCount: 90,
    price: 0,
    ueVersions: ['5.3', '5.4', '5.5'],
    hasSource: true,
    gasCompatible: false,
    tags: ['loot', 'cloud', 'items', 'leaderboard', 'virtual-currency'],
    difficulty: 'adapter',
    integrationTimeMinutes: 60,
  },

  // ── Progression / XP ────────────────────────────────────────────────────
  {
    id: 'progression-framework',
    name: 'RPG Progression Framework',
    publisher: 'GameDevUtils',
    source: 'ue-marketplace',
    category: 'framework',
    description: 'XP curves, level-up system, skill trees, talent points with save/load and GAS integration.',
    rating: 4.5,
    ratingCount: 140,
    price: 39.99,
    ueVersions: ['5.4', '5.5'],
    hasSource: true,
    gasCompatible: true,
    tags: ['xp', 'level', 'skill-tree', 'talents', 'progression', 'gas', 'rpg'],
    difficulty: 'adapter',
    integrationTimeMinutes: 45,
  },

  // ── Save System ─────────────────────────────────────────────────────────
  {
    id: 'easy-save',
    name: 'SaveGamePlus',
    publisher: 'CodeSpartan',
    source: 'ue-marketplace',
    category: 'save-system',
    description: 'Enhanced save system with async save/load, slot management, actor serialization, and world persistence.',
    rating: 4.7,
    ratingCount: 280,
    price: 29.99,
    ueVersions: ['5.3', '5.4', '5.5'],
    hasSource: true,
    gasCompatible: false,
    tags: ['save', 'load', 'async', 'slots', 'serialization', 'persistence', 'world-state'],
    difficulty: 'adapter',
    integrationTimeMinutes: 45,
  },

  // ── Dialogue / Quests ───────────────────────────────────────────────────
  {
    id: 'dialogue-plugin',
    name: 'Dialogue Plugin',
    publisher: 'CodeSpartan',
    source: 'ue-marketplace',
    category: 'dialogue',
    description: 'Node-based dialogue editor with conditions, events, branching, speaker configuration, and localization.',
    rating: 4.7,
    ratingCount: 420,
    price: 39.99,
    ueVersions: ['5.3', '5.4', '5.5'],
    hasSource: true,
    gasCompatible: false,
    tags: ['dialogue', 'branching', 'node-editor', 'conversation', 'npc', 'localization'],
    difficulty: 'adapter',
    integrationTimeMinutes: 45,
  },
  {
    id: 'narrative-plugin',
    name: 'Narrative',
    publisher: 'Reubs',
    source: 'fab',
    category: 'dialogue',
    description: 'Complete quest and dialogue system. Visual scripting, quest tracking, branching dialogue, and save integration.',
    rating: 4.8,
    ratingCount: 300,
    price: 0,
    ueVersions: ['5.4', '5.5'],
    hasSource: true,
    gasCompatible: false,
    tags: ['quest', 'dialogue', 'narrative', 'branching', 'quest-tracker', 'save'],
    difficulty: 'adapter',
    integrationTimeMinutes: 60,
  },

  // ── VFX / Polish ────────────────────────────────────────────────────────
  {
    id: 'niagara-vfx-pack',
    name: 'Niagara VFX Essentials',
    publisher: 'Epic Games',
    source: 'fab',
    category: 'vfx',
    description: 'Starter pack of Niagara effects: fire, explosions, sparks, smoke, impact effects.',
    rating: 4.4,
    ratingCount: 700,
    price: 0,
    ueVersions: ['5.3', '5.4', '5.5'],
    hasSource: false,
    gasCompatible: false,
    tags: ['vfx', 'niagara', 'particles', 'fire', 'explosion', 'impact', 'polish'],
    difficulty: 'drop-in',
    integrationTimeMinutes: 10,
  },
  {
    id: 'realtime-vfx',
    name: 'Stylized VFX Pack',
    publisher: 'Crivens',
    source: 'ue-marketplace',
    category: 'vfx',
    description: 'Stylized RPG VFX: sword slashes, magic circles, buff auras, heal effects, hit sparks. GAS event compatible.',
    rating: 4.8,
    ratingCount: 500,
    price: 29.99,
    ueVersions: ['5.4', '5.5'],
    hasSource: false,
    gasCompatible: true,
    tags: ['vfx', 'rpg', 'stylized', 'slash', 'magic', 'aura', 'buff', 'combat'],
    difficulty: 'drop-in',
    integrationTimeMinutes: 20,
  },

  // ── Audio ───────────────────────────────────────────────────────────────
  {
    id: 'metasounds-starter',
    name: 'MetaSounds Starter Pack',
    publisher: 'Epic Games',
    source: 'fab',
    category: 'audio',
    description: 'Procedural audio patches: footsteps, weapon impacts, ambient loops, UI sounds.',
    rating: 4.3,
    ratingCount: 200,
    price: 0,
    ueVersions: ['5.4', '5.5'],
    hasSource: false,
    gasCompatible: false,
    tags: ['audio', 'metasounds', 'procedural', 'footsteps', 'impact', 'ambient'],
    difficulty: 'drop-in',
    integrationTimeMinutes: 15,
  },

  // ── Environment / World ─────────────────────────────────────────────────
  {
    id: 'pcg-framework',
    name: 'PCG Framework Examples',
    publisher: 'Epic Games',
    source: 'fab',
    category: 'environment',
    description: 'Official PCG (Procedural Content Generation) examples: scatter props, generate roads, foliage placement.',
    rating: 4.2,
    ratingCount: 300,
    price: 0,
    ueVersions: ['5.4', '5.5'],
    hasSource: true,
    gasCompatible: false,
    tags: ['pcg', 'procedural', 'environment', 'scatter', 'foliage', 'world'],
    difficulty: 'adapter',
    integrationTimeMinutes: 60,
  },

  // ── Multiplayer ─────────────────────────────────────────────────────────
  {
    id: 'online-subsystem',
    name: 'Online Subsystem EOS',
    publisher: 'Epic Games',
    source: 'fab',
    category: 'multiplayer',
    description: 'Epic Online Services integration: matchmaking, lobbies, P2P, voice chat, anti-cheat.',
    rating: 4.1,
    ratingCount: 400,
    price: 0,
    ueVersions: ['5.3', '5.4', '5.5'],
    hasSource: true,
    gasCompatible: false,
    tags: ['multiplayer', 'eos', 'matchmaking', 'lobby', 'p2p', 'online'],
    difficulty: 'deep-rewrite',
    integrationTimeMinutes: 240,
  },
];
