/**
 * Emit a UE Python script that pushes the FeedbackTab tuner values onto the
 * combat-feel C++ properties added in Phase C (UGA_MeleeAttack CDO). Property
 * names here must match the C++ UPROPERTYs in GA_MeleeAttack.h exactly
 * (HitStopDuration, HitStopTimeDilation, HitCameraShakeScale), set via
 * set_editor_property in snake_case.
 */
export function buildCombatFeelPython(values: Record<string, number>): string {
  const L: string[] = [];
  L.push('# Generated by PoF — combat-feel emitter (folder-03 app §5 -> game §6)');
  L.push('import unreal');
  L.push('');
  L.push('# Targets the GA_MeleeAttack Blueprint CDO (BP_GA_MeleeAttack under /Game).');
  L.push('ability_path = "/Game/Blueprints/Abilities/BP_GA_MeleeAttack.BP_GA_MeleeAttack_C"');
  L.push('cdo = unreal.get_default_object(unreal.load_class(None, ability_path))');
  L.push('');
  // Mapped knobs -> C++ properties (snake_case of the UPROPERTY names).
  L.push(`cdo.set_editor_property("hit_stop_duration", ${num(values.hitstopDuration, 0.05)})`);
  L.push(`cdo.set_editor_property("hit_camera_shake_scale", ${num(values.shakeScale, 1.0)})`);
  L.push('');
  L.push('# Unmapped tuner knobs (no C++ home yet) — surfaced for the operator:');
  L.push(`# screen_flash_alpha = ${num(values.screenFlashAlpha, 0)}`);
  L.push(`# vfx_scale = ${num(values.vfxScale, 1)}, sfx_volume = ${num(values.sfxVolume, 0.7)}, sfx_pitch = ${num(values.sfxPitch, 1)}`);
  L.push(`# shake_decay = ${num(values.shakeDecay, 0.5)}, hitstop_ease = ${num(values.hitstopEase, 0.5)}`);
  L.push('');
  L.push('unreal.EditorAssetLibrary.save_loaded_asset(cdo.get_outer())');
  L.push('unreal.log("Combat-feel values applied to BP_GA_MeleeAttack CDO")');
  return L.join('\n');
}

function num(v: number | undefined, fallback: number): number {
  return typeof v === 'number' && Number.isFinite(v) ? v : fallback;
}
