import type { CharacterGenome } from '@/types/character-genome';

/** Strip to valid C++ identifier chars [A-Za-z0-9_], ensure non-empty */
export function sanitizeCppIdentifier(raw: string): string {
  const cleaned = raw.replace(/[^A-Za-z0-9_]/g, '');
  return cleaned || 'Unnamed';
}

/** Strip newlines and control chars from text embedded in C++ // comments */
export function sanitizeCppComment(raw: string): string {
  return raw.replace(/[\r\n\\\x00-\x1f]/g, ' ').trim();
}

/** Escape a value for CSV: wrap in quotes if it contains comma, quote, or newline */
export function csvEscape(value: string): string {
  if (/[,"\r\n]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

export function generateSubclassHeader(g: CharacterGenome): string {
  const className = `AARPG${sanitizeCppIdentifier(g.name)}Character`;
  return `// Auto-generated by PoF Character Genome System
// Genome: ${sanitizeCppComment(g.name)} v${g.version} — ${sanitizeCppComment(g.description)}
// Author: ${sanitizeCppComment(g.author)} | ${g.updatedAt}

#pragma once

#include "CoreMinimal.h"
#include "Character/ARPGCharacterBase.h"
#include "${className}.generated.h"

UCLASS()
class POF_API ${className} : public AARPGCharacterBase
{
\tGENERATED_BODY()

public:
\t${className}();

protected:
\tvirtual void BeginPlay() override;
\tvirtual void InitializeAttributes() override;
};`;
}

export function generateSubclassCpp(g: CharacterGenome): string {
  const className = `AARPG${sanitizeCppIdentifier(g.name)}Character`;
  return `// Auto-generated by PoF Character Genome System
#include "${className}.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Camera/CameraComponent.h"
#include "GameFramework/SpringArmComponent.h"

${className}::${className}()
{
\t// ── Movement Profile ──
\tGetCharacterMovement()->MaxWalkSpeed = ${g.movement.maxWalkSpeed}.f;
\tMaxSprintSpeed = ${g.movement.maxSprintSpeed}.f;
\tGetCharacterMovement()->MaxAcceleration = ${g.movement.acceleration}.f;
\tGetCharacterMovement()->BrakingDecelerationWalking = ${g.movement.deceleration}.f;
\tGetCharacterMovement()->RotationRate = FRotator(0.f, ${g.movement.turnRate}.f, 0.f);
\tGetCharacterMovement()->AirControl = ${g.movement.airControl}f;
\tGetCharacterMovement()->JumpZVelocity = ${g.movement.jumpZVelocity}.f;
\tGetCharacterMovement()->GravityScale = ${g.movement.gravityScale}f;

\t// ── Combat Profile ──
\tBaseDamage = ${g.combat.baseDamage}.f;
\tAttackSpeed = ${g.combat.attackSpeed}f;
\tComboWindowMs = ${g.combat.comboWindowMs}.f;
\tHitReactionDuration = ${g.combat.hitReactionDuration}f;
\tCritChance = ${g.combat.critChance}f;
\tCritMultiplier = ${g.combat.critMultiplier}f;
\tAttackRange = ${g.combat.attackRange}.f;
\tCleaveAngle = ${g.combat.cleaveAngle}.f;

\t// ── Dodge Profile ──
\tDodgeDistance = ${g.dodge.distance}.f;
\tDodgeDuration = ${g.dodge.duration}f;
\tIFrameStart = ${g.dodge.iFrameStart}f;
\tIFrameDuration = ${g.dodge.iFrameDuration}f;
\tDodgeCooldown = ${g.dodge.cooldown}f;
\tDodgeStaminaCost = ${g.dodge.staminaCost}.f;

\t// ── Camera Profile ──
\tif (CameraBoom)
\t{
\t\tCameraBoom->TargetArmLength = ${g.camera.armLength}.f;
\t\tCameraBoom->CameraLagSpeed = ${g.camera.lagSpeed}f;
\t\tCameraBoom->SocketOffset = FVector(0.f, 0.f, ${g.camera.socketOffsetZ}.f);
\t}
\tBaseFOV = ${g.camera.fovBase}.f;
\tSprintFOVOffset = ${g.camera.fovSprintOffset}.f;
}

void ${className}::BeginPlay()
{
\tSuper::BeginPlay();
}

void ${className}::InitializeAttributes()
{
\tSuper::InitializeAttributes();
\t// Attribute init values set via DataTable — see generated AttributeInitTable
}`;
}

export function generateAttributeInitTable(g: CharacterGenome): string {
  const safeName = sanitizeCppIdentifier(g.name);
  const rows = [
    `${csvEscape(`${safeName}.HP`)},${g.attributes.baseHP},${g.attributes.hpPerLevel}`,
    `${csvEscape(`${safeName}.Stamina`)},${g.attributes.baseStamina},${g.attributes.staminaPerLevel}`,
    `${csvEscape(`${safeName}.Mana`)},${g.attributes.baseMana},${g.attributes.manaPerLevel}`,
    `${csvEscape(`${safeName}.Armor`)},${g.attributes.baseArmor},${g.attributes.armorPerLevel}`,
    `${csvEscape(`${safeName}.StaminaRegen`)},${g.attributes.staminaRegenPerSec},0`,
    `${csvEscape(`${safeName}.ManaRegen`)},${g.attributes.manaRegenPerSec},0`,
  ];
  return `RowName,BaseValue,ScalingPerLevel\n${rows.join('\n')}`;
}
