import type { CharacterGenome } from '@/types/character-genome';

/** Strip to valid C++ identifier chars [A-Za-z0-9_], ensure non-empty */
export function sanitizeCppIdentifier(raw: string): string {
  const cleaned = raw.replace(/[^A-Za-z0-9_]/g, '');
  return cleaned || 'Unnamed';
}

/** Strip newlines and control chars from text embedded in C++ // comments */
export function sanitizeCppComment(raw: string): string {
  return raw.replace(/[\r\n\\\x00-\x1f]/g, ' ').trim();
}

/** Escape a value for CSV: wrap in quotes if it contains comma, quote, or newline */
export function csvEscape(value: string): string {
  if (/[,"\r\n]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

/**
 * Format a JS number as a valid C++ float literal. `String(1.0)` is `"1"`,
 * so a naive `${v}f` yields `1f` ("invalid suffix 'f' on integer constant")
 * and `${v}.f` on a fractional value yields `25.5.f` — both fail to compile.
 * Non-finite input (NaN from a corrupted field) emits `0.f`.
 */
export function cppFloat(v: number): string {
  if (!Number.isFinite(v)) return '0.f';
  return Number.isInteger(v) ? `${v}.f` : `${v}f`;
}

export function generateSubclassHeader(g: CharacterGenome): string {
  const className = `AARPG${sanitizeCppIdentifier(g.name)}Character`;
  return `// Auto-generated by PoF Character Genome System
// Genome: ${sanitizeCppComment(g.name)} v${g.version} — ${sanitizeCppComment(g.description)}
// Author: ${sanitizeCppComment(g.author)} | ${g.updatedAt}

#pragma once

#include "CoreMinimal.h"
#include "Character/ARPGCharacterBase.h"
#include "${className}.generated.h"

UCLASS()
class POF_API ${className} : public AARPGCharacterBase
{
\tGENERATED_BODY()

public:
\t${className}();

protected:
\tvirtual void BeginPlay() override;
\tvirtual void InitializeAttributes() override;
};`;
}

export function generateSubclassCpp(g: CharacterGenome): string {
  const className = `AARPG${sanitizeCppIdentifier(g.name)}Character`;
  return `// Auto-generated by PoF Character Genome System
#include "${className}.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Camera/CameraComponent.h"
#include "GameFramework/SpringArmComponent.h"

${className}::${className}()
{
\t// ── Movement Profile ──
\tGetCharacterMovement()->MaxWalkSpeed = ${cppFloat(g.movement.maxWalkSpeed)};
\tMaxSprintSpeed = ${cppFloat(g.movement.maxSprintSpeed)};
\tGetCharacterMovement()->MaxAcceleration = ${cppFloat(g.movement.acceleration)};
\tGetCharacterMovement()->BrakingDecelerationWalking = ${cppFloat(g.movement.deceleration)};
\tGetCharacterMovement()->RotationRate = FRotator(0.f, ${cppFloat(g.movement.turnRate)}, 0.f);
\tGetCharacterMovement()->AirControl = ${cppFloat(g.movement.airControl)};
\tGetCharacterMovement()->JumpZVelocity = ${cppFloat(g.movement.jumpZVelocity)};
\tGetCharacterMovement()->GravityScale = ${cppFloat(g.movement.gravityScale)};

\t// ── Combat Profile ──
\tBaseDamage = ${cppFloat(g.combat.baseDamage)};
\tAttackSpeed = ${cppFloat(g.combat.attackSpeed)};
\tComboWindowMs = ${cppFloat(g.combat.comboWindowMs)};
\tHitReactionDuration = ${cppFloat(g.combat.hitReactionDuration)};
\tCritChance = ${cppFloat(g.combat.critChance)};
\tCritMultiplier = ${cppFloat(g.combat.critMultiplier)};
\tAttackRange = ${cppFloat(g.combat.attackRange)};
\tCleaveAngle = ${cppFloat(g.combat.cleaveAngle)};

\t// ── Dodge Profile ──
\tDodgeDistance = ${cppFloat(g.dodge.distance)};
\tDodgeDuration = ${cppFloat(g.dodge.duration)};
\tIFrameStart = ${cppFloat(g.dodge.iFrameStart)};
\tIFrameDuration = ${cppFloat(g.dodge.iFrameDuration)};
\tDodgeCooldown = ${cppFloat(g.dodge.cooldown)};
\tDodgeStaminaCost = ${cppFloat(g.dodge.staminaCost)};

\t// ── Camera Profile ──
\tif (CameraBoom)
\t{
\t\tCameraBoom->TargetArmLength = ${cppFloat(g.camera.armLength)};
\t\tCameraBoom->CameraLagSpeed = ${cppFloat(g.camera.lagSpeed)};
\t\tCameraBoom->SocketOffset = FVector(0.f, 0.f, ${cppFloat(g.camera.socketOffsetZ)});
\t}
\tBaseFOV = ${cppFloat(g.camera.fovBase)};
\tSprintFOVOffset = ${cppFloat(g.camera.fovSprintOffset)};
}

void ${className}::BeginPlay()
{
\tSuper::BeginPlay();
}

void ${className}::InitializeAttributes()
{
\tSuper::InitializeAttributes();
\t// Attribute init values set via DataTable — see generated AttributeInitTable
}`;
}

export function generateAttributeInitTable(g: CharacterGenome): string {
  const safeName = sanitizeCppIdentifier(g.name);
  const rows = [
    `${csvEscape(`${safeName}.HP`)},${g.attributes.baseHP},${g.attributes.hpPerLevel}`,
    `${csvEscape(`${safeName}.Stamina`)},${g.attributes.baseStamina},${g.attributes.staminaPerLevel}`,
    `${csvEscape(`${safeName}.Mana`)},${g.attributes.baseMana},${g.attributes.manaPerLevel}`,
    `${csvEscape(`${safeName}.Armor`)},${g.attributes.baseArmor},${g.attributes.armorPerLevel}`,
    `${csvEscape(`${safeName}.StaminaRegen`)},${g.attributes.staminaRegenPerSec},0`,
    `${csvEscape(`${safeName}.ManaRegen`)},${g.attributes.manaRegenPerSec},0`,
  ];
  return `RowName,BaseValue,ScalingPerLevel\n${rows.join('\n')}`;
}
