import { describe, it, expect } from 'vitest';
import { parseGuideMarkdown } from '@/lib/harness/guide-markdown';

describe('parseGuideMarkdown', () => {
  it('extracts an h1 + h2 + paragraph', () => {
    const blocks = parseGuideMarkdown(`# Title\n\n## Section\n\nThe body.`);
    expect(blocks[0]).toEqual({ kind: 'h1', text: 'Title' });
    expect(blocks[1]).toEqual({ kind: 'h2', text: 'Section' });
    expect(blocks[2]).toEqual({ kind: 'paragraph', text: 'The body.' });
  });

  it('parses fenced code with the declared language', () => {
    const md = "```typescript\nconst x = 1;\nconst y = 2;\n```";
    const blocks = parseGuideMarkdown(md);
    expect(blocks).toHaveLength(1);
    expect(blocks[0]).toMatchObject({ kind: 'code', lang: 'typescript', code: 'const x = 1;\nconst y = 2;' });
  });

  it('recognizes `### Phase N: label` as a typed phase block', () => {
    const md = `### Phase 2: Combat Loop\n\nSome body.`;
    const blocks = parseGuideMarkdown(md);
    expect(blocks[0]).toEqual({ kind: 'phase', phase: 2, label: 'Combat Loop' });
  });

  it('attaches a following **Duration:** chip to its phase', () => {
    const md = `### Phase 3: Enemies\n\n**Module:** \`arpg-enemy\`\n**Duration:** 12.4min\n`;
    const blocks = parseGuideMarkdown(md);
    const phase = blocks.find((b) => b.kind === 'phase');
    expect(phase).toMatchObject({ kind: 'phase', phase: 3, label: 'Enemies', duration: '12.4min' });
  });

  it('groups consecutive bullets into one list block', () => {
    const md = `- one\n- two\n- three`;
    const blocks = parseGuideMarkdown(md);
    expect(blocks).toHaveLength(1);
    expect(blocks[0]).toEqual({ kind: 'list', items: ['one', 'two', 'three'] });
  });

  it('treats `---` as a horizontal rule', () => {
    const blocks = parseGuideMarkdown(`paragraph\n\n---\n\nmore`);
    expect(blocks.some((b) => b.kind === 'hr')).toBe(true);
  });

  it('collapses a blockquote run', () => {
    const md = `> generated\n> by the harness`;
    const blocks = parseGuideMarkdown(md);
    expect(blocks[0]).toEqual({ kind: 'blockquote', text: 'generated by the harness' });
  });
});
