/** One archetype row of FARPGAttributeInitRow values. */
export interface AttributeRow {
  rowName: string;
  values: Record<string, number>;
}

/** The FARPGAttributeInitRow fields the editor exposes (subset of the C++ struct). */
export const ATTRIBUTE_FIELDS = [
  'Health', 'MaxHealth', 'Mana', 'MaxMana',
  'Strength', 'Dexterity', 'Intelligence',
  'Armor', 'AttackPower', 'CriticalChance', 'CriticalDamage',
  'FireResistance', 'IceResistance', 'LightningResistance',
  'CharacterLevel',
] as const;

export const DEFAULT_ATTRIBUTE_ROWS: AttributeRow[] = [
  { rowName: 'Player', values: { Health: 100, MaxHealth: 100, Mana: 50, MaxMana: 50, Strength: 10, Dexterity: 10, Intelligence: 10, Armor: 5, AttackPower: 10, CriticalChance: 0.05, CriticalDamage: 0.5, FireResistance: 0, IceResistance: 0, LightningResistance: 0, CharacterLevel: 1 } },
  { rowName: 'Skeleton', values: { Health: 40, MaxHealth: 40, Mana: 0, MaxMana: 0, Strength: 6, Dexterity: 8, Intelligence: 2, Armor: 2, AttackPower: 6, CriticalChance: 0.02, CriticalDamage: 0.5, FireResistance: 0, IceResistance: 0, LightningResistance: 0, CharacterLevel: 1 } },
  { rowName: 'Boss', values: { Health: 600, MaxHealth: 600, Mana: 100, MaxMana: 100, Strength: 20, Dexterity: 12, Intelligence: 14, Armor: 15, AttackPower: 25, CriticalChance: 0.1, CriticalDamage: 1.0, FireResistance: 0.25, IceResistance: 0.25, LightningResistance: 0.25, CharacterLevel: 5 } },
];

/**
 * Emit a UE Python script that creates /Game/Data/DT_AttributeDefaults as a
 * UDataTable whose row struct is FARPGAttributeInitRow, populated with the given
 * rows. Field names match the C++ USTRUCT exactly (no bool props here, so the
 * `b`-prefix-drop gotcha does not apply).
 */
export function buildAttributeDefaultsPython(rows: AttributeRow[]): string {
  const L: string[] = [];
  L.push('# Generated by PoF — DT_AttributeDefaults emitter (folder-03 app §4)');
  L.push('import unreal');
  L.push('');
  L.push('PACKAGE_PATH = "/Game/Data"');
  L.push('ASSET_NAME = "DT_AttributeDefaults"');
  L.push('');
  L.push('tools = unreal.AssetToolsHelpers.get_asset_tools()');
  L.push('# Row struct FARPGAttributeInitRow is exposed to Python as ARPGAttributeInitRow (UE drops the F prefix).');
  L.push('row_struct = unreal.load_object(None, "/Script/PoF.ARPGAttributeInitRow")');
  L.push('factory = unreal.DataTableFactory()');
  L.push('factory.struct = row_struct');
  L.push('dt = tools.create_asset(ASSET_NAME, PACKAGE_PATH, unreal.DataTable, factory)');
  L.push('');
  for (const row of rows) {
    L.push(`# ── ${row.rowName} ──`);
    L.push(`${rowVar(row)} = unreal.ARPGAttributeInitRow()`);
    for (const [field, value] of Object.entries(row.values)) {
      // set_editor_property uses snake_case; field names here are plain (no bool b-prefix)
      L.push(`${rowVar(row)}.set_editor_property("${toSnake(field)}", ${value})`);
    }
    L.push(`unreal.DataTableFunctionLibrary.add_data_table_row(dt, "${row.rowName}", ${rowVar(row)})`);
    L.push('');
  }
  L.push('unreal.EditorAssetLibrary.save_loaded_asset(dt)');
  L.push(`unreal.log("DT_AttributeDefaults written with %d rows" % ${rows.length})`);
  return L.join('\n');
}

function rowVar(row: AttributeRow): string {
  return `row_${row.rowName.toLowerCase()}`;
}

function toSnake(field: string): string {
  return field.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
}
