/** Pin-verified Diablo I group-AI ledger. This data module imports only its public types. */
import type {
  GroupAiEvent,
  GroupAiFinding,
  GroupAiInheritance,
  GroupAiPackConsequence,
  GroupAiRelationState,
  GroupAiRoutineUse,
} from '@/lib/catalog/reference/groupAiLedger';

const monster = (lines: string): string => `.reference/devilutionX/Source/monster.cpp:${lines}`;
const monsterHeader = (lines: string): string => `.reference/devilutionX/Source/monster.h:${lines}`;
const monsterDataHeader = (lines: string): string => `.reference/devilutionX/Source/tables/monstdat.h:${lines}`;
const missiles = (lines: string): string => `.reference/devilutionX/Source/missiles.cpp:${lines}`;
const player = (lines: string): string => `.reference/devilutionX/Source/player.cpp:${lines}`;

export const GROUP_AI_RELATIONS_DATA = [
  {
    state: 'LeaderRelation::None',
    meaning: 'No live leash behavior. This is every monster\'s initialization state, every UniqueMonsterPack::Independent minion remains in it, and released/detached minions return to it.',
    enteredWhen: [
      'InitMonster sets leader=Monster::NoLeader and leaderRelation=LeaderRelation::None.',
      'ReleaseMinions calls setLeader(nullptr) for a dying leader\'s currently Leashed minions; the relation becomes None but the numeric leader index and copied AI are retained.',
      'ScavengerAi changes any non-None relation to None when a wounded scavenger enters Healing.',
    ],
    leavesWhen: [
      'PlaceGroup calls setLeader(leader) only for a UniqueMonsterPack::Leashed pack, entering Leashed.',
    ],
    perTick: [
      'FollowTheLeader and GroupUnity return without leader/minion timer exchange.',
      'A unique leader itself normally has relation None; hasLeashedMinions and packSize can still constrain that leader\'s legal moves until all counted Leashed minions fit around the proposed future tile.',
    ],
    refs: [monster('208-245'), monster('340-378'), monster('1481-1495'), monster('1674-1728'), monster('2202-2213'), monster('4356-4381'), monster('4886-4898')],
  },
  {
    state: 'LeaderRelation::Leashed',
    meaning: 'The monster is a counted minion of a unique leader: activation can flow both ways, movement is kept near the leader, and the leader waits for every counted minion.',
    enteredWhen: [
      'PlaceGroup receives leashed=true and setLeader stores the leader index, changes the relation to Leashed, and copies the leader AI.',
      'GroupUnity re-leashes a Separated minion when the line is non-solid-clear and WalkingDistance to leader.position.future is below 4; leader.packSize is incremented.',
    ],
    leavesWhen: [
      'GroupUnity finds the line from the minion tile to leader.position.future obstructed; it decrements leader.packSize and changes the minion to Separated.',
      'The leader death animation completes and ReleaseMinions changes each still-Leashed child to None.',
      'The minion death animation completes or ScavengerAi detaches for Healing; leader.packSize is decremented before death/detachment.',
    ],
    perTick: [
      'Before AI dispatch, FollowTheLeader copies a strictly larger leader activeForTicks minus one and stores the leader tile in minion.position.last.',
      'Every attempted minion move must leave futurePosition.WalkingDistance(leader.position.future) below 4.',
      'After a completed mode update, GroupUnity checks separation/reunion, then can copy a strictly larger minion activeForTicks minus one back to the leader.',
      'Gargoyle leaders and minions also clear MFLAG_ALLOW_SPECIAL and enter SpecialMeleeAttack in response to the other side leaving its statue state.',
    ],
    refs: [monster('1674-1728'), monster('4257-4330'), monster('4356-4381'), monster('4886-4898')],
  },
  {
    state: 'LeaderRelation::Separated',
    meaning: 'The monster keeps its leader index and copied AI but is removed from leader.packSize and temporarily acts without leash movement or activation sharing.',
    enteredWhen: [
      'GroupUnity finds that IsLineNotSolid from the minion tile to leader.position.future is false while the minion is Leashed.',
    ],
    leavesWhen: [
      'GroupUnity finds a non-solid-clear line and WalkingDistance to leader.position.future below 4, then increments leader.packSize and changes the relation to Leashed.',
      'ScavengerAi can change the relation directly to None when entering Healing.',
    ],
    perTick: [
      'FollowTheLeader does nothing, DirOK applies no minion leash, and GroupUnity performs only the reunion test.',
      'ReleaseMinions filters for Leashed children, so a Separated child is not cleared when its leader finishes dying; it retains the relation and leader index in the pinned implementation.',
    ],
    refs: [monsterHeader('140-154'), monster('1481-1488'), monster('1674-1728'), monster('2202-2213'), monster('4356-4366')],
  },
] as const satisfies readonly GroupAiRelationState[];

export const GROUP_AI_INHERITANCE_DATA = [
  {
    id: 'unique-pack-placement-stats',
    direction: 'placement->minion',
    what: 'hit points and intelligence',
    condition: 'PlaceGroup has a non-null unique leader; applies to both UniqueMonsterPack::Independent and UniqueMonsterPack::Leashed.',
    effect: 'The minion maximum hit points are multiplied by 2, current hit points are refilled to that maximum, and minion.intelligence is assigned leader.intelligence.',
    refs: [monster('308-378'), monster('3402-3404')],
  },
  {
    id: 'leashed-ai-copy',
    direction: 'leader->minion',
    what: 'MonsterAIID ai',
    condition: 'setLeader receives a non-null leader during leashed placement.',
    effect: 'The minion AI identifier becomes newLeader->ai. Detachment does not restore the minion type\'s original AI.',
    refs: [monster('349-358'), monster('4886-4898')],
  },
  {
    id: 'leader-activation-to-minion',
    direction: 'leader->minion',
    what: 'activeForTicks and position.last',
    condition: 'The relation is Leashed and leader.activeForTicks > minion.activeForTicks.',
    effect: 'minion.position.last becomes leader.position.tile and minion.activeForTicks becomes leader.activeForTicks - 1 before AI dispatch.',
    refs: [monster('1674-1686'), monster('4257-4268')],
  },
  {
    id: 'minion-activation-to-leader',
    direction: 'minion->leader',
    what: 'activeForTicks and position.last',
    condition: 'After GroupUnity, the relation is Leashed and minion.activeForTicks > leader.activeForTicks.',
    effect: 'leader.position.last becomes minion.position.tile and leader.activeForTicks becomes minion.activeForTicks - 1.',
    refs: [monster('1696-1727'), monster('4321-4330')],
  },
  {
    id: 'enemy-target-not-shared',
    direction: 'not-shared',
    what: 'enemy, MFLAG_TARGETS_MONSTER, and enemyPosition',
    condition: 'All leader relations, including Leashed.',
    effect: 'No leash helper copies a target. UpdateEnemy chooses each monster\'s own enemy, and ProcessMonsters refreshes enemyPosition from that monster\'s enemy; position.last can be overwritten by the visible target after FollowTheLeader wrote the leader tile.',
    refs: [monster('679-748'), monster('1674-1728'), monster('4278-4317')],
  },
  {
    id: 'gargoyle-statue-state',
    direction: 'leader->minion',
    what: 'Gargoyle MFLAG_ALLOW_SPECIAL/statue exit',
    condition: 'A Leashed Gargoyle minion still allows Special while its leader is no longer in SpecialMeleeAttack.',
    effect: 'The minion clears MFLAG_ALLOW_SPECIAL and is put in SpecialMeleeAttack so the pack statue state advances together.',
    refs: [monster('1674-1694')],
  },
  {
    id: 'gargoyle-statue-state-reverse',
    direction: 'minion->leader',
    what: 'Gargoyle MFLAG_ALLOW_SPECIAL/statue exit',
    condition: 'After GroupUnity the child is Leashed and the Gargoyle leader still allows Special.',
    effect: 'The leader clears MFLAG_ALLOW_SPECIAL and is put in SpecialMeleeAttack.',
    refs: [monster('1696-1727')],
  },
  {
    id: 'leashed-membership-count',
    direction: 'minion->leader',
    what: 'leader.packSize',
    condition: 'A Leashed child is placed, separates, reunites, dies, or explicitly detaches.',
    effect: 'packSize counts only currently Leashed children and is the exact count DirOK requires inside the leader\'s proposed movement square.',
    refs: [monster('377-379'), monster('1491-1495'), monster('1696-1717'), monster('4356-4381')],
  },
] as const satisfies readonly GroupAiInheritance[];

export const GROUP_AI_EVENTS_DATA = [
  {
    id: 'unique-pack-placement',
    trigger: 'PrepareUniqueMonst sees uniqueMonsterData.monsterPack != UniqueMonsterPack::None and calls PlaceGroup with the unique monster as leader.',
    effect: 'Independent and Leashed packs both receive the placement stat changes. Only Leashed calls setLeader and initializes leader.packSize; Independent minions keep LeaderRelation::None and their type AI.',
    radiusOrTimer: ['Leashed placement rejects abs(xp-x1) >= 4 or abs(yp-y1) >= 4.', 'PlaceGroup retries placement but the final placed count may be below the requested num.'],
    routines: [],
    expansion: 'diablo',
    refs: [monsterDataHeader('304-320'), monster('308-380'), monster('3325-3404')],
  },
  {
    id: 'leash-separation',
    trigger: 'GroupUnity runs after a mode update and IsLineNotSolid(minion.position.tile, leader.position.future) is false for a Leashed child.',
    effect: 'leader.packSize is decremented and the child becomes LeaderRelation::Separated; timer exchange and leash movement stop.',
    radiusOrTimer: ['The transition is obstruction-based, not distance-based.'],
    routines: [],
    expansion: 'diablo',
    refs: [monster('1696-1728'), monster('4321-4330')],
  },
  {
    id: 'leash-reunion',
    trigger: 'A Separated child has a non-solid-clear line to leader.position.future and WalkingDistance is below 4.',
    effect: 'leader.packSize is incremented and the child becomes LeaderRelation::Leashed in the same GroupUnity call.',
    radiusOrTimer: ['minion.position.tile.WalkingDistance(leader.position.future) < 4'],
    routines: [],
    expansion: 'diablo',
    refs: [monster('1696-1728')],
  },
  {
    id: 'leader-death-release',
    trigger: 'A unique leader\'s death animation reaches its last frame and M_UpdateRelations sees hasLeashedMinions().',
    effect: 'Every still-Leashed child of that leader changes to None. Numeric leader and copied AI are retained. Separated children are not selected and retain Separated.',
    radiusOrTimer: ['Release occurs at death-animation completion, not when hitPoints first reaches zero.'],
    routines: [],
    expansion: 'diablo',
    refs: [monsterHeader('424-430'), monster('1481-1488'), monster('1498-1526'), monster('4067-4073'), monster('4886-4898')],
  },
  {
    id: 'minion-death-or-detach',
    trigger: 'A Leashed minion finishes its death animation, or a related Scavenger enters Healing below half maximum hit points.',
    effect: 'The leader pack count is decremented. Death leaves the dying object relation untouched; ScavengerAi explicitly changes it to None.',
    radiusOrTimer: [],
    routines: ['Scavenger'],
    expansion: 'diablo',
    refs: [monster('1491-1526'), monster('2202-2213'), monster('4067-4073')],
  },
  {
    id: 'fallen-death-fear',
    trigger: 'Any monster starts death and MonsterDeath calls M_FallenFear at the death tile.',
    effect: 'Each living MonsterAIID::Fallen in the square is assigned Retreat, a run counter, and a direction away from the death position. The dead monster need not be Fallen or an explicit pack member.',
    radiusOrTimer: ['fearArea = Rectangle { position, 4 }', 'runDistance = max(8 - monster.data().level, 2)', 'goalVar1 = runDistance', 'goalVar2 = GetDirection(position, monster.position.tile)'],
    routines: ['Fallen'],
    expansion: 'diablo',
    refs: [monster('3996-4030'), monster('4450-4467')],
  },
  {
    id: 'fallen-war-cry-rally',
    trigger: 'FallenAi reaches the last standing-animation frame and FlipCoin(4) succeeds.',
    effect: 'The caller enters SpecialStand and heals; every dMonster occupant whose AI is MonsterAIID::Fallen in the square is assigned Attack with a shared AI-call counter. Snotspill can emit this by delegating to FallenAi, but it does not receive the write because its AI identifier is Snotspill.',
    radiusOrTimer: ['rad = 2 * monster.intelligence + 4', 'goalVar1 = 30 * monster.intelligence + 105', 'heal = 2 * monster.intelligence + 2, capped at maxHitPoints'],
    routines: ['Fallen', 'Snotspill'],
    expansion: 'diablo',
    refs: [monster('2314-2370'), monster('2630-2667')],
  },
  {
    id: 'skeleton-king-summon',
    trigger: 'LeoricAi is active and standing, multiplayer quests are disabled, its summon predicate passes, the front tile is available, capacity remains, and a loaded skeleton type exists.',
    effect: 'SpawnMonster creates one new skeleton at the front tile and the King enters SpecialStand. InitMonster gives the spawn LeaderRelation::None and no leader; it is an independent new attacker, not a leashed minion.',
    radiusOrTimer: ['LineClearMissile(monster.position.tile, monster.enemyPosition)', '(distanceToEnemy >= 3 && v < 4 * monster.intelligence + 35) || v < 6', 'ActiveMonsterCount < MaxMonsters'],
    routines: ['SkeletonKing'],
    expansion: 'diablo',
    refs: [monster('1568-1593'), monster('2374-2429'), monster('3778-3851')],
  },
  {
    id: 'monster-target-selection',
    trigger: 'UpdateEnemy scans ActiveMonsters for player-minion, Golem-target, ranged, proximity, or MFLAG_BERSERK eligibility.',
    effect: 'The selected monster index is stored in enemy, MFLAG_TARGETS_MONSTER is set, and enemyPosition is taken from that monster. This is hostility/targeting, not leader target inheritance.',
    radiusOrTimer: ['Ordinary non-ranged monsters consider a Golem only when dist < 2; ranged ordinary monsters may consider it farther away.', 'MFLAG_BERSERK relaxes the ordinary allegiance filters (Hellfire flag).'],
    routines: ['Golem'],
    expansion: 'diablo',
    refs: [monster('674-748'), monster('3263-3275'), monster('4157-4169')],
  },
  {
    id: 'monster-hit-wake',
    trigger: 'MonsterAttackMonster lands a hit on a target whose activeForTicks is zero.',
    effect: 'The target becomes fully active and remembers the attacker tile in position.last.',
    radiusOrTimer: ['target.activeForTicks = UINT8_MAX'],
    routines: ['Golem'],
    expansion: 'diablo',
    refs: [monster('1110-1141'), monster('1261-1268')],
  },
  {
    id: 'golem-local-wake',
    trigger: 'GolumAi reaches melee range of an inactive monster target.',
    effect: 'The target and every positive dMonster occupant in a square centered on the Golem are set fully active before the Golem starts attacking.',
    radiusOrTimer: ['abs(golem.x - enemy.future.x) < 2 && abs(golem.y - enemy.future.y) < 2', 'mx = golem.x + k - 2 and my = golem.y + j - 2 for j,k in [0,4]', 'activeForTicks = UINT8_MAX'],
    routines: ['Golem'],
    expansion: 'diablo',
    refs: [monster('4157-4196')],
  },
  {
    id: 'monster-target-deleted',
    trigger: 'DeleteMonster removes a monster after its lifecycle has made it invalid.',
    effect: 'Every active monster targeting that monster receives MFLAG_NO_ENEMY; each chooses a replacement only on a later UpdateEnemy call.',
    radiusOrTimer: [],
    routines: [],
    expansion: 'diablo',
    refs: [monster('634-651'), monster('679-748')],
  },
  {
    id: 'diablo-death-wave',
    trigger: 'MonsterDeath starts for MT_DIABLO and calls DiabloDeath.',
    effect: 'When the dying Diablo is active, every active non-Diablo monster is directly put into Death mode and its occupied position is reset; this bypasses the ordinary per-monster MonsterDeath start path and therefore does not call M_FallenFear for each forced death.',
    radiusOrTimer: ['All ActiveMonsters; the guard is monster.type().type == MT_DIABLO || diablo.activeForTicks == 0.'],
    routines: ['Diablo'],
    expansion: 'diablo',
    refs: [monster('875-909'), monster('3996-4030')],
  },
  {
    id: 'hork-demon-summon',
    trigger: 'HorkDemonAi is active and standing at range, its roll passes, a front tile is available, and monster capacity remains.',
    effect: 'The HorkSpawn missile later searches its ending tile and adjacent tiles; when a tile is found it calls SpawnMonster. The spawn initializes with LeaderRelation::None and has no leader.',
    radiusOrTimer: ['distanceToEnemy >= 3 && v < 2 * monster.intelligence + 43', 'HorkSpawn duration = 9', 'FindClosestValidPosition(..., missile.position.tile, 0, 1)'],
    routines: ['HorkDemon'],
    expansion: 'hellfire-flag-only',
    refs: [monster('3009-3064'), missiles('1351-1357'), missiles('3168-3190'), monster('3778-3851')],
  },
  {
    id: 'hellfire-doppelganger-spawn',
    trigger: 'A Hellfire Doppelganger item effect procs while the player damages a non-unique, non-Diablo monster.',
    effect: 'AddDoppelganger chooses an available adjacent tile and SpawnMonster creates the same monster type as an independent LeaderRelation::None monster.',
    radiusOrTimer: ['The source scans all eight adjacent directions and keeps the last available tile.'],
    routines: [],
    expansion: 'hellfire-flag-only',
    refs: [player('610-616'), monster('3854-3866')],
  },
] as const satisfies readonly GroupAiEvent[];

export const GROUP_AI_ROUTINES_DATA = [
  {
    routine: 'all-routines',
    phase: 'common-loop',
    reads: ['leaderRelation', 'leader', 'packSize', 'activeForTicks', 'position.future', 'position.last'],
    writes: ['activeForTicks', 'position.last', 'leaderRelation', 'packSize'],
    eventIds: ['unique-pack-placement', 'leash-separation', 'leash-reunion', 'leader-death-release', 'minion-death-or-detach', 'monster-target-deleted'],
    note: 'ProcessMonsters runs FollowTheLeader before dispatch and GroupUnity after completed mode transitions. DirOK enforces both sides of the leash for every movement helper; the behavior is outside the per-routine Stand decision graphs.',
    refs: [monster('1674-1728'), monster('4257-4330'), monster('4356-4381')],
  },
  {
    routine: 'Scavenger',
    phase: 'routine',
    reads: ['leaderRelation', 'hitPoints', 'maxHitPoints'],
    writes: ['leaderRelation', 'leader.packSize', 'goal'],
    eventIds: ['minion-death-or-detach'],
    note: 'The only routine that directly reads a leader relation: entering Healing detaches from either Leashed or Separated.',
    refs: [monster('2202-2213')],
  },
  {
    routine: 'Fallen',
    phase: 'routine',
    reads: ['nearby dMonster occupants', 'nearby monster.ai', 'nearby monster life state'],
    writes: ['nearby Fallen goal', 'nearby Fallen goalVar1', 'own hitPoints'],
    eventIds: ['fallen-death-fear', 'fallen-war-cry-rally'],
    note: 'Receives global death fear and can rally all nearby Fallen; neither effect requires a leader relation.',
    refs: [monster('2314-2370'), monster('4450-4467')],
  },
  {
    routine: 'Snotspill',
    phase: 'routine',
    reads: ['FallenAi neighborhood scan after quest release'],
    writes: ['nearby MonsterAIID::Fallen goal and goalVar1'],
    eventIds: ['fallen-war-cry-rally'],
    note: 'Delegates to FallenAi and can emit its rally, but M_FallenFear filters on MonsterAIID::Fallen so Snotspill never receives the fear write.',
    refs: [monster('2630-2667'), monster('4450-4467')],
  },
  {
    routine: 'SkeletonKing',
    phase: 'routine',
    reads: ['ActiveMonsterCount', 'loaded skeleton types', 'front-tile availability'],
    writes: ['new independent skeleton monster'],
    eventIds: ['skeleton-king-summon'],
    note: 'Creates a fresh independent monster; it does not add the summon to a leader pack.',
    refs: [monster('1568-1593'), monster('2374-2429')],
  },
  {
    routine: 'Gargoyle',
    phase: 'common-loop',
    reads: ['leader/minion ai', 'MFLAG_ALLOW_SPECIAL', 'leader.mode'],
    writes: ['leader/minion MFLAG_ALLOW_SPECIAL', 'leader/minion mode'],
    eventIds: [],
    note: 'FollowTheLeader and GroupUnity contain Gargoyle-specific bidirectional statue-state synchronization outside GargoyleAi.',
    refs: [monster('1674-1728'), monster('2480-2507')],
  },
  {
    routine: 'Golem',
    phase: 'routine',
    reads: ['ActiveMonsters', 'nearby dMonster occupants', 'target activeForTicks'],
    writes: ['monster-target enemy fields', 'nearby activeForTicks', 'target position.last'],
    eventIds: ['monster-target-selection', 'monster-hit-wake', 'golem-local-wake'],
    note: 'The player minion acquires monster enemies and wakes a local cluster when it closes with an inactive target.',
    refs: [monster('679-748'), monster('1110-1141'), monster('4157-4196')],
  },
  {
    routine: 'Diablo',
    phase: 'death-handler',
    reads: ['ActiveMonsters', 'diablo.activeForTicks'],
    writes: ['every active non-Diablo monster mode and position state'],
    eventIds: ['diablo-death-wave'],
    note: 'The cross-monster action is in DiabloDeath rather than the Stand decision routine.',
    refs: [monster('875-909'), monster('3996-4030')],
  },
  {
    routine: 'HorkDemon',
    phase: 'routine',
    reads: ['ActiveMonsterCount', 'front-tile availability'],
    writes: ['HorkSpawn missile that creates an independent monster'],
    eventIds: ['hork-demon-summon'],
    note: 'Hellfire-only behavior is recorded as flag-only and is not generalized into vanilla descent arithmetic.',
    refs: [monster('3009-3064'), missiles('3168-3190')],
  },
] as const satisfies readonly GroupAiRoutineUse[];

export const GROUP_AI_FINDINGS_DATA = [
  {
    dataset: 'aiRoutinesData',
    status: 'supports',
    finding: 'Its common-pack prose agrees that unique-pack minions get doubled hit points and leader intelligence, while Leashed minions copy leader AI and leader activation minus one. The ledger adds the reverse timer flow, exact transitions, movement constraints, target non-inheritance, and death lifecycle.',
    refs: ['src/lib/catalog/reference/aiRoutinesData.ts:26', monster('349-378'), monster('1674-1728'), monster('4356-4381')],
  },
  {
    dataset: 'aiRoutinesData',
    status: 'supports',
    finding: 'The Fallen, SkeletonKing, Golem, Snotspill, and HorkDemon summaries agree with the corresponding neighborhood/summon behavior; their prose is not a substitute for typed triggers, formulas, and expansion scope.',
    refs: ['src/lib/catalog/reference/aiRoutinesData.ts:145', 'src/lib/catalog/reference/aiRoutinesData.ts:179', 'src/lib/catalog/reference/aiRoutinesData.ts:281-282', 'src/lib/catalog/reference/aiRoutinesData.ts:301', 'src/lib/catalog/reference/aiRoutinesData.ts:380'],
  },
  {
    dataset: 'aiDecisionGraphsData',
    status: 'missing-layer',
    finding: 'The graphs begin at each routine\'s Stand decision. FollowTheLeader runs before dispatch, GroupUnity runs after completed modes, and death/neighborhood events sit outside those graphs; no existing graph entity carried typed group state before data.groupAi attachment.',
    refs: ['src/lib/catalog/reference/aiDecisionGraphs.ts:528-535', 'src/lib/catalog/reference/aiDecisionGraphsData.ts:102-107', monster('4257-4330')],
  },
  {
    dataset: 'packMath',
    status: 'qualifies',
    finding: 'ordinaryPackSizeDistribution groups nearby PlaceGroup outputs into one combat pack, but ordinary PlaceGroup uses no leader and supplies no activation, target, or leash sharing. Simultaneous engagement is therefore a model assumption for ordinary packs, not an engine group law.',
    refs: ['src/lib/catalog/reference/packMath.ts:235-252', monster('308-380'), monster('1674-1728')],
  },
  {
    dataset: 'packMath',
    status: 'qualifies',
    finding: 'requestedUniquePackSize treats the requested unique group as fixed, while PlaceGroup can finish with fewer placed minions after bounded retries/capacity limits. It also collapses UniqueMonsterPack::Independent and ::Leashed despite only Leashed sharing activation and movement constraints.',
    refs: ['src/lib/catalog/reference/packMath.ts:260-262', monsterDataHeader('304-320'), monster('308-380'), monster('3402-3404')],
  },
  {
    dataset: 'packMath',
    status: 'qualifies',
    finding: 'The all-survivor ranged exposure and shared engagement ring are directionally supported for an intact Leashed pack by bidirectional activation and sub-four-tile movement, but contradicted as a universal rule by independent packs, obstruction-driven separation, and per-monster target selection.',
    refs: ['src/lib/catalog/reference/packMath.ts:9-19', 'src/lib/catalog/reference/packMath.ts:265-305', monster('1674-1728'), monster('4278-4317'), monster('4356-4381')],
  },
] as const satisfies readonly GroupAiFinding[];

export const GROUP_AI_PACK_CONSEQUENCES_DATA = [
  {
    rank: 1,
    name: 'Conditional engagement concurrency',
    expectedEffect: 'high',
    modelAssumption: 'packExchange counts every ranged survivor, or every available melee slot, as engaged throughout each alive-count phase.',
    engineEvidence: 'Only intact Leashed packs propagate activation and remain within the leash. Ordinary and Independent packs have no relation, obstructed children become Separated, and targets are selected independently.',
    descentConsequence: 'Applying simultaneous exposure to every generated pack can overstate incoming damage and hit-recovery load; the correction should branch on pack relation and reduce engaged attackers after separation instead of changing per-routine duel rates.',
    refs: ['src/lib/catalog/reference/packMath.ts:265-305', monster('308-380'), monster('1674-1728'), monster('4278-4317')],
  },
  {
    rank: 2,
    name: 'Dynamic summon roster',
    expectedEffect: 'high',
    modelAssumption: 'The pack phase loop starts from one fixed packSize and only decrements alive; it has no arrival transition.',
    engineEvidence: 'SkeletonKing can repeatedly SpawnMonster skeletons during combat, and Hellfire HorkDemon can create an independent monster through HorkSpawn, both subject to live space/capacity.',
    descentConsequence: 'Boss encounters can take longer and deal more damage than a fixed initial roster predicts; model summons as capacity/space-gated arrivals, with HorkDemon excluded or separately flagged for vanilla runs.',
    refs: ['src/lib/catalog/reference/packMath.ts:292-307', monster('2374-2429'), monster('3009-3064'), missiles('3168-3190')],
  },
  {
    rank: 3,
    name: 'Fallen casualty morale',
    expectedEffect: 'medium',
    modelAssumption: 'Each surviving attacker preserves the same duel-derived availability as pack members die.',
    engineEvidence: 'Every nearby death forces living Fallen into Retreat for max(8-level,2) attempts, while a later war cry can set nearby Fallen to Attack for 30*intelligence+105 AI calls.',
    descentConsequence: 'The constant-attacker phase model overstates pressure immediately after kills and misses later rally bursts; Fallen packs need a casualty-triggered temporary availability state before their ordinary phase rate resumes.',
    refs: ['src/lib/catalog/reference/packMath.ts:292-307', monster('2314-2370'), monster('3996-4030'), monster('4450-4467')],
  },
] as const satisfies readonly GroupAiPackConsequence[];
