/** Engine-derived Diablo I object behaviours. No objdat.tsv row values are stored here. */
import type { ObjectSpecData, ShrineEffectData } from '@/lib/catalog/reference/objectSpecs';

const source = (...lines: number[]): string[] =>
  lines.map((line) => `.reference/devilutionX/Source/objects.cpp:${line}`);

const noDrops = 'None.';
const noTrap = 'Not armed as a trap trigger and does not fire a trap.';

export const OBJECT_SPECS_DATA = [
  {
    kind: 'ambient-light',
    objects: ['OBJ_L1LIGHT', 'OBJ_SKFIRE', 'OBJ_CANDLE1', 'OBJ_CANDLE2', 'OBJ_TORCHL', 'OBJ_TORCHR', 'OBJ_TORCHL2', 'OBJ_TORCHR2', 'OBJ_BOOKCANDLE', 'OBJ_STORYCANDLE', 'OBJ_L5CANDLE'],
    operate: 'Not player-operated. While a player is near, the object maintains its configured light radius; distant lights are removed.',
    drops: noDrops, trap: noTrap, once: false,
    refs: source(1245, 1469, 4198),
  },
  {
    kind: 'burning-cross', objects: ['OBJ_BCROSS', 'OBJ_TBCROSS'],
    operate: 'Not player-operated. It maintains local light and repeatedly deals fire damage to the local hero on the damaging adjacent tile.',
    drops: noDrops, trap: noTrap, once: false,
    refs: source(1642, 4258),
  },
  {
    kind: 'door',
    objects: ['OBJ_L1LDOOR', 'OBJ_L1RDOOR', 'OBJ_L2LDOOR', 'OBJ_L2RDOOR', 'OBJ_L3LDOOR', 'OBJ_L3RDOOR', 'OBJ_L5LDOOR', 'OBJ_L5RDOOR'],
    operate: 'Toggles between open and closed, updates collision, dungeon tiles and vision; a blocked doorway refuses to close.',
    drops: noDrops,
    trap: 'Can be selected as a wall-trap trigger. Opening it disarms the trigger and lets the linked wall trap fire once.',
    once: false,
    refs: source(1049, 1760, 4138, 4377),
  },
  {
    kind: 'lever', objects: ['OBJ_LEVER', 'OBJ_SWITCHSKL', 'OBJ_L5LEVER'],
    operate: 'Single use. Disables selection, advances the lever frame and changes its linked map area; grouped and quest levers defer the map change until their condition is met.',
    drops: noDrops,
    trap: 'Can be selected as a wall-trap trigger. Operating it disarms the trigger and lets the linked wall trap fire once.',
    once: true,
    refs: source(1782, 1822, 4138, 4393),
  },
  {
    kind: 'chest', objects: ['OBJ_CHEST1', 'OBJ_CHEST2', 'OBJ_CHEST3', 'OBJ_TCHEST1', 'OBJ_TCHEST2', 'OBJ_TCHEST3'],
    operate: 'Opens once, disables selection and replays its stored seed to create its rolled contents. A Thaumaturgic shrine can make opened chests usable again.',
    drops: 'Creates the stored tier count of useful or ordinary random items; set-level chests use fixed size-tier counts. A non-set chest can roll zero drops.',
    trap: 'Ordinary chests may gain a linked one-shot wall trap. A trapped-chest variant instead fires one rolled chest missile at the opener and then clears its trap flag.',
    once: true,
    refs: source(529, 915, 2018, 2487),
  },
  {
    kind: 'crucifix', objects: ['OBJ_CRUX1', 'OBJ_CRUX2', 'OBJ_CRUX3'],
    operate: 'Breaks from a qualifying attack, becomes unselectable and changes the linked map only after every crucifix in its group is broken.',
    drops: noDrops, trap: noTrap, once: true,
    refs: source(3417, 3438, 4690),
  },
  {
    kind: 'set-book', objects: ['OBJ_BOOK2L'],
    operate: 'Single use. In its quest map it can teleport the hero or complete the Chamber of Bone reward, then disables selection and advances its frame.',
    drops: noDrops, trap: noTrap, once: true,
    refs: source(1842, 4398),
  },
  {
    kind: 'chamber-book', objects: ['OBJ_BOOK2R'],
    operate: 'Reveals the linked map area, activates the Chamber of Bone quest when needed and presents the class-specific quest text. It remains readable.',
    drops: noDrops, trap: noTrap, once: false,
    refs: source(1969, 4402),
  },
  {
    kind: 'sarcophagus', objects: ['OBJ_SARC', 'OBJ_L5SARC'],
    operate: 'Opens once and starts its animation. Its stored outcome can create one random item, release a pre-spawned skeleton, or do neither.',
    drops: 'Creates one ordinary random item only for the low stored outcome; other outcomes release a skeleton or yield nothing.',
    trap: 'Can be selected as a wall-trap trigger. Opening it disarms the trigger and lets the linked wall trap fire once.',
    once: true,
    refs: source(1198, 2188, 4138, 4413),
  },
  {
    kind: 'flame-trap', objects: ['OBJ_FLAMEHOLE'],
    operate: 'Not directly operated. Detects actors across its five-tile line, activates every flame vent in the group and deals repeated fire damage while active.',
    drops: noDrops,
    trap: 'It is the firing trap: a grouped flame-wall hazard controlled by proximity and its linked lever.',
    once: false,
    refs: source(1213, 1574, 4247),
  },
  {
    kind: 'flame-trap-lever', objects: ['OBJ_FLAMELVR'],
    operate: 'Reusable toggle. Alternately disables or enables every matching flame-trap line and updates its own frame.',
    drops: noDrops,
    trap: 'Controls a grouped flame trap; it does not fire a projectile itself.',
    once: false,
    refs: source(2160, 4417),
  },
  {
    kind: 'wall-trap', objects: ['OBJ_TRAPL', 'OBJ_TRAPR'],
    operate: 'Not directly operated. After its linked object is opened or used, it fires once toward a nearby hero or otherwise toward the trigger.',
    drops: noDrops,
    trap: 'Fires one depth-selected arrow, fire bolt or lightning projectile and then remains spent.',
    once: true,
    refs: source(1227, 4138, 4176),
  },
  {
    kind: 'barrel', objects: ['OBJ_BARREL', 'OBJ_POD', 'OBJ_URN'],
    operate: 'Breaks immediately from a qualifying hit, loses collision and selection, and resolves its stored outcome.',
    drops: 'The low stored outcome creates one useful or ordinary random item; the high outcome releases a pre-spawned skeleton; all other outcomes drop nothing.',
    trap: 'Cannot be armed as a trigger. Its stored skeleton outcome is a container surprise, not a projectile trap.',
    once: true,
    refs: source(1280, 3461, 4695),
  },
  {
    kind: 'explosive-container', objects: ['OBJ_BARRELEX', 'OBJ_PODEX', 'OBJ_URNEX'],
    operate: 'Breaks immediately, damages actors in the surrounding three-by-three area and recursively detonates adjacent explosive containers.',
    drops: noDrops,
    trap: 'The explosion is intrinsic, not an armed trigger; it uses fire damage and can chain to adjacent explosive containers.',
    once: true,
    refs: source(1280, 3461, 4695),
  },
  {
    kind: 'shrine', objects: ['OBJ_SHRINEL', 'OBJ_SHRINER'],
    operate: 'Single use. Applies the effect selected when the shrine was placed, disables selection and starts its activation animation.',
    drops: 'Only effects that explicitly create items do so; the 26-effect vanilla table states those cases.',
    trap: noTrap, once: true,
    refs: source(1297, 2250, 2989, 4426),
  },
  {
    kind: 'book-stand', objects: ['OBJ_SKELBOOK', 'OBJ_BOOKSTAND'],
    operate: 'Opens once, disables selection and creates a seeded book-or-scroll result.',
    drops: 'Creates exactly one miscellaneous item: a book on the uncommon branch, otherwise a scroll.',
    trap: noTrap, once: true,
    refs: source(3110, 4430),
  },
  {
    kind: 'bookcase', objects: ['OBJ_BOOKCASEL', 'OBJ_BOOKCASER'],
    operate: 'Opens once, disables selection and creates a seeded book; opening a nearby quest bookcase can also turn Zhar hostile.',
    drops: 'Creates exactly one spell book using the current dungeon item-generation context.',
    trap: noTrap, once: true,
    refs: source(3128, 4434),
  },
  {
    kind: 'corpse-container', objects: ['OBJ_DECAP'],
    operate: 'Single use. Disables selection and creates one seeded ordinary random item.',
    drops: 'Creates exactly one ordinary random item using the current dungeon item-generation context.',
    trap: noTrap, once: true,
    refs: source(3157, 4438),
  },
  {
    kind: 'armour-rack', objects: ['OBJ_ARMORSTAND', 'OBJ_WARARMOR'],
    operate: 'Single use. Disables selection, advances its frame and creates armour chosen by dungeon depth.',
    drops: 'Creates one light armour item through depth 5, medium armour at depths 6–9, and heavy armour from depth 10 onward; quality eligibility varies by band.',
    trap: noTrap, once: true,
    refs: source(3169, 4441),
  },
  {
    kind: 'random-shrine', objects: ['OBJ_GOATSHRINE', 'OBJ_CAULDRON'],
    operate: 'Single use. Chooses an eligible shrine effect from its stored seed at activation and then applies that effect.',
    drops: 'Depends on the selected shrine effect; only explicitly item-creating effects produce items.',
    trap: noTrap, once: true,
    refs: source(3191, 3205, 3214, 4445),
  },
  {
    kind: 'restoration-fountain', objects: ['OBJ_BLOODFTN', 'OBJ_PURIFYINGFTN'],
    operate: 'Repeatable. Restores one whole life or mana per interaction, clamped at maximum, and remains selectable.',
    drops: noDrops, trap: noTrap, once: false,
    refs: source(3224, 4451),
  },
  {
    kind: 'murky-fountain', objects: ['OBJ_MURKYFTN'],
    operate: 'Single use. Disables selection and creates the timed infravision effect for the activating hero.',
    drops: noDrops, trap: noTrap, once: true,
    refs: source(3224, 3262, 4451),
  },
  {
    kind: 'tears-fountain', objects: ['OBJ_TEARFTN'],
    operate: 'Single use. Disables selection and permanently moves one base-stat point from one seeded attribute to a different seeded attribute.',
    drops: noDrops, trap: noTrap, once: true,
    refs: source(3224, 3280, 4451),
  },
  {
    kind: 'magic-circle', objects: ['OBJ_MCIRCLE1', 'OBJ_MCIRCLE2'],
    operate: 'Not clicked. Tracks whether a hero stands on it; the completed central quest circle reveals its linked area and teleports that hero.',
    drops: noDrops, trap: noTrap, once: false,
    refs: source(1492, 4254),
  },
  {
    kind: 'story-book', objects: ['OBJ_STORYBOOK', 'OBJ_L5BOOKS'],
    operate: 'Reusable while no other quest text is open. Plays its stored narration; crypt books also advance the expansion quest or a three-book sequence.',
    drops: noDrops, trap: noTrap, once: false,
    refs: source(3352, 3374, 4457),
  },
  {
    kind: 'quest-book', objects: ['OBJ_BLINDBOOK', 'OBJ_BLOODBOOK', 'OBJ_STEELTOME'],
    operate: 'Presents quest text and performs its one-time quest/map transition when the relevant quest phase has not yet advanced; it remains readable afterward.',
    drops: 'The Blind book creates its fixed unique reward and the Blood book creates its fixed quest stone; the Steel Tome creates no item.',
    trap: noTrap, once: false,
    refs: source(1924, 4420),
  },
  {
    kind: 'pedestal', objects: ['OBJ_PEDESTAL'],
    operate: 'Consumes one quest stone per use. Three placements progressively open the set piece; the final placement creates the fixed reward and disables selection.',
    drops: 'The first two placements relocate fixed quest stones; the third creates the fixed unique armour reward.',
    trap: noTrap, once: false,
    refs: source(2207, 4462),
  },
  {
    kind: 'weapon-rack', objects: ['OBJ_WARWEAP', 'OBJ_WEAPONRACK'],
    operate: 'Single use. Disables selection, advances its frame and creates a seeded weapon class.',
    drops: 'Creates one sword, axe, bow or mace. Cathedral racks use the ordinary quality branch; deeper racks use the quality-eligible branch.',
    trap: noTrap, once: true,
    refs: source(3324, 4466),
  },
  {
    kind: 'mushroom-patch', objects: ['OBJ_MUSHPATCH'],
    operate: 'Usable only during the active mushroom quest. Then it opens once, creates the quest mushroom and advances the quest phase.',
    drops: 'Creates exactly one fixed quest mushroom.',
    trap: noTrap, once: true,
    refs: source(2073, 4470),
  },
  {
    kind: 'quest-stand', objects: ['OBJ_LAZSTAND'],
    operate: 'Single use while no quest text is open. Disables selection and creates Lazarus’s fixed quest staff nearby.',
    drops: 'Creates exactly one fixed quest staff.',
    trap: noTrap, once: true,
    refs: source(3397, 4473),
  },
  {
    kind: 'slain-hero', objects: ['OBJ_SLAINHERO'],
    operate: 'Single use. Disables selection, speaks the memorial line and creates a seeded reward chosen by the activating hero’s class.',
    drops: 'Creates one class-specific magic armour, weapon or Lightning spell book.',
    trap: noTrap, once: true,
    refs: source(2133, 4477),
  },
  {
    kind: 'sign-chest', objects: ['OBJ_SIGNCHEST'],
    operate: 'Usable only at the required banner-quest phase. Then it opens once and creates the fixed banner.',
    drops: 'Creates exactly one fixed quest banner.',
    trap: noTrap, once: true,
    refs: source(2104, 4480),
  },
  {
    kind: 'quest-altar-scenery', objects: ['OBJ_STAND', 'OBJ_ANGEL', 'OBJ_ALTBOY'],
    operate: 'No player-operation case. These are quest/set-piece scenery rather than active altars or pedestals.',
    drops: noDrops, trap: noTrap, once: false,
    refs: source(4377),
  },
  {
    kind: 'inert-scenery',
    objects: ['OBJ_CANDLEO', 'OBJ_BANNERL', 'OBJ_BANNERM', 'OBJ_BANNERR', 'OBJ_SKPILE', 'OBJ_SKSTICK1', 'OBJ_SKSTICK2', 'OBJ_SKSTICK3', 'OBJ_SKSTICK4', 'OBJ_SKSTICK5', 'OBJ_NUDEW2R', 'OBJ_TNUDEM1', 'OBJ_TNUDEM2', 'OBJ_TNUDEM3', 'OBJ_TNUDEM4', 'OBJ_TNUDEW1', 'OBJ_TNUDEW2', 'OBJ_TNUDEW3', 'OBJ_TORTURE1', 'OBJ_TORTURE2', 'OBJ_TORTURE3', 'OBJ_TORTURE4', 'OBJ_TORTURE5', 'OBJ_WATER', 'OBJ_BOOKLVR', 'OBJ_BOOKSHELF', 'OBJ_WEAPRACK', 'OBJ_ARMORSTANDN', 'OBJ_WEAPONRACKN', 'OBJ_BOOKSHELFR'],
    operate: 'No player-operation or break dispatch; the object is scenery or an inactive visual variant.',
    drops: noDrops, trap: noTrap, once: false,
    refs: source(4377),
  },
] satisfies readonly ObjectSpecData[];

export const SHRINE_EFFECTS_DATA = [
  { shrine: 'Mysterious', effect: 'Subtracts one base point from every attribute, then adds six to one seeded random attribute.', duration: 'permanent', refs: source(2250) },
  { shrine: 'Hidden', effect: 'Adds ten current and maximum durability to eligible equipped items, then subtracts twenty from one seeded eligible item, with a floor of one.', duration: 'permanent', refs: source(2282) },
  { shrine: 'Gloomy', effect: 'Lowers maximum damage on every weapon by one without crossing minimum damage, and adds two armour class to armour and shields.', duration: 'permanent', refs: source(2329) },
  { shrine: 'Weird', effect: 'Adds one maximum damage to carried weapons and to equipped non-shield weapons.', duration: 'permanent', refs: source(2363) },
  { shrine: 'Magical', effect: 'Creates Mana Shield for the activating hero; the shield lasts until mana or another engine removal condition ends it.', duration: 'timed', refs: source(2392) },
  { shrine: 'Stone', effect: 'Refills every carried staff to its maximum charges.', duration: 'instant', refs: source(2410) },
  { shrine: 'Religious', effect: 'Repairs every carried item to maximum durability.', duration: 'instant', refs: source(2427) },
  { shrine: 'Enchanted', effect: 'If more than one spell is learned, raises every eligible learned spell except one seeded spell, which loses one level.', duration: 'permanent', refs: source(2439) },
  { shrine: 'Thaumaturgic', effect: 'Re-enables every opened chest on the level, assigns each a new seed and restores its closed frame.', duration: 'instant', refs: source(2487) },
  { shrine: 'Fascinating', effect: 'Learns or raises Firebolt by up to two levels, then removes one tenth of base maximum mana from maximum and current mana.', duration: 'permanent', refs: source(2504) },
  { shrine: 'Cryptic', effect: 'Casts Nova from the hero and immediately refills mana.', duration: 'instant', refs: source(2546) },
  { shrine: 'Magical', effect: 'The second vanilla selection slot applies the same Mana Shield effect as the other Magical shrine slot.', duration: 'timed', refs: source(2392, 3016) },
  { shrine: 'Eldritch', effect: 'Converts carried healing and mana potions into matching rejuvenation potions while preserving item seeds.', duration: 'instant', refs: source(2569) },
  { shrine: 'Eerie', effect: 'Adds two base Magic.', duration: 'permanent', refs: source(2602) },
  { shrine: 'Divine', effect: 'Fully restores life and mana and creates two full potions; before depth four they are one healing and one mana potion, otherwise rejuvenation.', duration: 'instant', refs: source(2621) },
  { shrine: 'Holy', effect: 'Creates a Phasing relocation for the activating hero.', duration: 'timed', refs: source(2644) },
  { shrine: 'Sacred', effect: 'Learns or raises Charged Bolt by up to two levels, then removes one tenth of base maximum mana from maximum and current mana.', duration: 'permanent', refs: source(2504, 3050) },
  { shrine: 'Spiritual', effect: 'Fills every empty inventory grid cell with a depth-scaled gold stack.', duration: 'instant', refs: source(2654) },
  { shrine: 'Spooky', effect: 'In multiplayer, heals every other local hero to full life and mana; the activator receives only the shrine message.', duration: 'instant', refs: source(2673) },
  { shrine: 'Abandoned', effect: 'Adds two base Dexterity.', duration: 'permanent', refs: source(2692) },
  { shrine: 'Creepy', effect: 'Adds two base Strength.', duration: 'permanent', refs: source(2705) },
  { shrine: 'Quiet', effect: 'Adds two base Vitality.', duration: 'permanent', refs: source(2718) },
  { shrine: 'Secluded', effect: 'Marks every macro-cell in the current dungeon explored on the automap.', duration: 'instant', refs: source(2731) },
  { shrine: 'Ornate', effect: 'Learns or raises Holy Bolt by up to two levels, then removes one tenth of base maximum mana from maximum and current mana.', duration: 'permanent', refs: source(2504, 3071) },
  { shrine: 'Glimmering', effect: 'Identifies every carried magical item that is not already identified.', duration: 'instant', refs: source(2743) },
  { shrine: 'Tainted', effect: 'In multiplayer, every other local hero gains one point in one seeded attribute and loses one point in each of the other three.', duration: 'permanent', refs: source(2760) },
] satisfies readonly ShrineEffectData[];
