/** Engine-derived Diablo I quest data; see questSpecs.ts for its learning-only lifetime. */
import type { QuestId, QuestSpec } from '@/lib/catalog/reference/questSpecs';

const source = (path: string) => `https://github.com/diasurgical/devilutionX/blob/4138a82/Source/${path}`;
const refs = (...paths: string[]) => paths.map(source);

export const D1_QUEST_SPECS: Record<QuestId, QuestSpec> = {
  'd1-Q_ROCK': {
    giver: { kind: 'towner', id: 'TOWN_SMITH' },
    startTrigger: { kind: 'talk-towner', condition: 'TOWN_SMITH activates and logs QUEST_INIT after the configured floor visit; IDI_ROCK pickup can activate it hidden.' },
    stages: [
      { id: 'selected', state: 'QUEST_INIT; _qvar1=0; _qvar2=0; _qlog=false', advancesWhen: 'TOWN_SMITH briefs the player or IDI_ROCK is picked up.' },
      { id: 'active-hidden', state: 'QUEST_ACTIVE; _qvar2=0; _qlog=false', advancesWhen: 'TOWN_SMITH sets _qvar2=1 and _qlog=true.' },
      { id: 'active-briefed', state: 'QUEST_ACTIVE; _qvar2=1; _qlog=true', advancesWhen: 'TOWN_SMITH removes IDI_ROCK.' },
      { id: 'complete', state: 'QUEST_DONE; _qvar2=1', advancesWhen: 'UITEM_INFRARING is spawned.' },
    ],
    completion: 'TOWN_SMITH removes IDI_ROCK while _qvar2=1.',
    failure: 'No failed transition; early IDI_ROCK pickup remains recoverable.',
    rewards: [{ kind: 'unique-item', what: 'UITEM_INFRARING' }], setLevel: 'SL_NONE',
    lines: [{ stage: 'briefing', line: 'TEXT_INFRA5', speaker: 'TOWN_SMITH' }, { stage: 'hand-in', line: 'TEXT_INFRA7', speaker: 'TOWN_SMITH' }],
    refs: refs('towners.cpp:292', 'inv.cpp:1024'),
  },
  'd1-Q_MUSHROOM': {
    giver: { kind: 'towner', id: 'TOWN_WITCH' },
    startTrigger: { kind: 'talk-towner', condition: 'TOWN_WITCH removes IDI_FUNGALTM while QUEST_INIT and sets QS_TOMEGIVEN.' },
    stages: [
      { id: 'tome-unspawned', state: 'QUEST_INIT; _qvar1=QS_INIT; _qvar2=0; _qlog=false', advancesWhen: 'The configured floor is synchronized.' },
      { id: 'tome-spawned', state: 'QUEST_INIT; _qvar1=QS_TOMESPAWNED', advancesWhen: 'TOWN_WITCH removes IDI_FUNGALTM.' },
      { id: 'tome-given', state: 'QUEST_ACTIVE; _qvar1=QS_TOMEGIVEN; _qlog=true', advancesWhen: 'OBJ_MUSHPATCH is operated.' },
      { id: 'mushroom-spawned', state: 'QUEST_ACTIVE; _qvar1=QS_MUSHSPAWNED', advancesWhen: 'IDI_MUSHROOM is picked up.' },
      { id: 'mushroom-picked', state: 'QUEST_ACTIVE; _qvar1=QS_MUSHPICKED', advancesWhen: 'TOWN_WITCH removes IDI_MUSHROOM.' },
      { id: 'mushroom-given', state: 'QUEST_ACTIVE; _qvar1=QS_MUSHGIVEN', advancesWhen: 'An eligible drop becomes IDI_BRAIN.' },
      { id: 'brain-spawned', state: 'QUEST_ACTIVE; _qvar1=QS_BRAINSPAWNED', advancesWhen: 'TOWN_HEALER removes IDI_BRAIN.' },
      { id: 'brain-given', state: 'QUEST_ACTIVE; _qvar1=QS_BRAINGIVEN', advancesWhen: 'TOWN_WITCH detects IDI_SPECELIX.' },
      { id: 'complete', state: 'QUEST_DONE; IDI_SPECELIX retained', advancesWhen: 'IDI_SPECELIX becomes usable.' },
    ],
    completion: 'TOWN_WITCH is spoken to while IDI_SPECELIX is carried.',
    failure: 'No failed transition; IDI_SPECELIX is unusable before QUEST_DONE.',
    rewards: [{ kind: 'item-class', what: 'IDI_SPECELIX' }, { kind: 'stat-change', what: 'IDI_SPECELIX scripted attribute increase' }], setLevel: 'SL_NONE',
    lines: [
      { stage: 'tome hand-in', line: 'TEXT_MUSH8', speaker: 'TOWN_WITCH' }, { stage: 'awaiting mushroom', line: 'TEXT_MUSH9', speaker: 'TOWN_WITCH' },
      { stage: 'mushroom hand-in', line: 'TEXT_MUSH10', speaker: 'TOWN_WITCH' }, { stage: 'brain noticed', line: 'TEXT_MUSH11', speaker: 'TOWN_WITCH' },
      { stage: 'brain hand-in', line: 'TEXT_MUSH4', speaker: 'TOWN_HEALER' }, { stage: 'completion', line: 'TEXT_MUSH12', speaker: 'TOWN_WITCH' },
      { stage: 'dynamic topic after mushroom', line: 'TEXT_MUSH3', speaker: 'TOWN_HEALER' },
    ],
    refs: refs('quests.cpp:449', 'towners.cpp:341', 'objects.cpp:2073', 'items.cpp:3422', 'items.cpp:4338', 'items.cpp:4800'),
  },
  'd1-Q_GARBUD': {
    giver: { kind: 'monster', id: 'UniqueMonsterType::Garbud' },
    startTrigger: { kind: 'talk-monster', condition: 'Speak to UniqueMonsterType::Garbud while the active line is TEXT_GARBUD1.' },
    stages: [
      { id: 'selected', state: 'QUEST_INIT; _qvar1=QS_GHARBAD_INIT; _qlog=false', advancesWhen: 'TEXT_GARBUD1 starts.' },
      { id: 'promised', state: 'QUEST_ACTIVE; _qvar1=QS_GHARBAD_INIT; _qlog=true', advancesWhen: 'Garbud leaves visibility after TEXT_GARBUD1.' },
      { id: 'first-item-ready', state: 'QUEST_ACTIVE; _qvar1=QS_GHARBAD_FIRST_ITEM_READY', advancesWhen: 'TEXT_GARBUD2 spawns deterministic random loot.' },
      { id: 'first-item-spawned', state: 'QUEST_ACTIVE; _qvar1=QS_GHARBAD_FIRST_ITEM_SPAWNED', advancesWhen: 'Garbud leaves visibility after TEXT_GARBUD2.' },
      { id: 'second-item-nearly-done', state: 'QUEST_ACTIVE; _qvar1=QS_GHARBAD_SECOND_ITEM_NEARLY_DONE', advancesWhen: 'TEXT_GARBUD3 finishes and Garbud leaves visibility.' },
      { id: 'second-item-ready', state: 'QUEST_ACTIVE; _qvar1=QS_GHARBAD_SECOND_ITEM_READY', advancesWhen: 'TEXT_GARBUD4 finishes.' },
      { id: 'attacking', state: 'QUEST_ACTIVE; _qvar1=QS_GHARBAD_ATTACKING; dialogue cleared', advancesWhen: 'Garbud is killed.' },
      { id: 'complete', state: 'QUEST_DONE', advancesWhen: 'The kill dispatcher completes the quest.' },
    ],
    completion: 'UniqueMonsterType::Garbud is killed during the hostile phase.',
    failure: 'No failed transition; dialogue protection remains until hostility.',
    rewards: [{ kind: 'item-class', what: 'deterministic random monster item during TEXT_GARBUD2' }, { kind: 'item-class', what: 'ItemType::Mace on death' }], setLevel: 'SL_NONE',
    lines: [
      { stage: 'first talk', line: 'TEXT_GARBUD1', speaker: 'UniqueMonsterType::Garbud' },
      { stage: 'first reward', line: 'TEXT_GARBUD2', speaker: 'UniqueMonsterType::Garbud' },
      { stage: 'waiting', line: 'TEXT_GARBUD3', speaker: 'UniqueMonsterType::Garbud' },
      { stage: 'hostility', line: 'TEXT_GARBUD4', speaker: 'UniqueMonsterType::Garbud' },
    ],
    refs: refs('monster.cpp:247', 'monster.cpp:917', 'monster.cpp:2578', 'monster.cpp:4789', 'monster.cpp:4962'),
  },
  'd1-Q_ZHAR': {
    giver: { kind: 'monster', id: 'UniqueMonsterType::Zhar' },
    startTrigger: { kind: 'talk-monster', condition: 'Speak to UniqueMonsterType::Zhar in the required library theme while the active line is TEXT_ZHAR1.' },
    stages: [
      { id: 'selected', state: 'QUEST_INIT; _qvar1=QS_ZHAR_INIT; _qlog=false', advancesWhen: 'The library exists and TEXT_ZHAR1 starts.' },
      { id: 'item-spawned', state: 'QUEST_ACTIVE; _qvar1=QS_ZHAR_ITEM_SPAWNED; _qlog=true', advancesWhen: 'A deterministic spellbook spawns and Zhar leaves visibility.' },
      { id: 'angry', state: 'QUEST_ACTIVE; _qvar1=QS_ZHAR_ANGRY', advancesWhen: 'TEXT_ZHAR2 finishes.' },
      { id: 'attacking', state: 'QUEST_ACTIVE; _qvar1=QS_ZHAR_ATTACKING; dialogue cleared', advancesWhen: 'Zhar is killed.' },
      { id: 'complete', state: 'QUEST_DONE', advancesWhen: 'The kill dispatcher completes the quest.' },
    ],
    completion: 'UniqueMonsterType::Zhar is killed after hostility.',
    failure: 'No accepted-quest failure; missing placement only makes the unstarted quest QUEST_NOTAVAIL.',
    rewards: [{ kind: 'item-class', what: 'deterministic ItemType::Misc IMISC_BOOK' }], setLevel: 'SL_NONE',
    lines: [{ stage: 'first talk', line: 'TEXT_ZHAR1', speaker: 'UniqueMonsterType::Zhar' }, { stage: 'hostility', line: 'TEXT_ZHAR2', speaker: 'UniqueMonsterType::Zhar' }],
    refs: refs('monster.cpp:251', 'monster.cpp:571', 'monster.cpp:2786', 'monster.cpp:4774'),
  },
  'd1-Q_VEIL': {
    giver: { kind: 'monster', id: 'UniqueMonsterType::Lachdan' },
    startTrigger: { kind: 'talk-monster', condition: 'Speak to UniqueMonsterType::Lachdan while the active line is TEXT_VEIL9.' },
    stages: [
      { id: 'selected', state: 'QUEST_INIT; _qvar1=QS_VEIL_INIT; _qvar2=QS_VEIL_INIT; _qlog=false', advancesWhen: 'TEXT_VEIL9 starts.' },
      { id: 'active', state: 'QUEST_ACTIVE; _qvar1=0; _qlog=true', advancesWhen: 'The configured floor spawns IDI_GLDNELIX.' },
      { id: 'early-return', state: 'QUEST_ACTIVE; _qvar2=QS_VEIL_EARLY_RETURN', advancesWhen: 'Lachdan leaves visibility and selects TEXT_VEIL10.' },
      { id: 'elixir-spawned', state: 'QUEST_ACTIVE; _qvar1=1', advancesWhen: 'The player returns with IDI_GLDNELIX.' },
      { id: 'item-spawned', state: 'QUEST_ACTIVE; _qvar1=1; _qvar2=QS_VEIL_ITEM_SPAWNED', advancesWhen: 'IDI_GLDNELIX is removed, UITEM_STEELVEIL spawns, and TEXT_VEIL11 finishes.' },
      { id: 'complete', state: 'QUEST_DONE; Lachdan removed', advancesWhen: 'The scripted final speech completes.' },
    ],
    completion: 'TEXT_VEIL11 finishes after the IDI_GLDNELIX hand-in.',
    failure: 'No failed transition; dialogue protection and scripted removal cover the speaker.',
    rewards: [{ kind: 'unique-item', what: 'UITEM_STEELVEIL' }], setLevel: 'SL_NONE',
    lines: [{ stage: 'first talk', line: 'TEXT_VEIL9', speaker: 'UniqueMonsterType::Lachdan' }, { stage: 'early return', line: 'TEXT_VEIL10', speaker: 'UniqueMonsterType::Lachdan' }, { stage: 'hand-in', line: 'TEXT_VEIL11', speaker: 'UniqueMonsterType::Lachdan' }],
    refs: refs('quests.cpp:465', 'monster.cpp:1451', 'monster.cpp:2953', 'monster.cpp:4761'),
  },
  'd1-Q_DIABLO': {
    giver: { kind: 'none' },
    startTrigger: { kind: 'kill-monster', condition: 'Killing UniqueMonsterType::Lazarus changes Q_DIABLO from QUEST_INIT to QUEST_ACTIVE.' },
    stages: [
      { id: 'locked', state: 'QUEST_INIT; _qlog=false', advancesWhen: 'UniqueMonsterType::Lazarus dies.' },
      { id: 'active-hidden', state: 'QUEST_ACTIVE; _qlog=false', advancesWhen: 'TOWN_STORY sets the journal flag or progression continues.' },
      { id: 'active-logged', state: 'QUEST_ACTIVE; _qlog=true; _qmsg=TEXT_VILE3', advancesWhen: 'Diablo dies.' },
      { id: 'complete', state: 'QUEST_DONE', advancesWhen: 'The ending sequence begins and kill difficulty is recorded.' },
    ],
    completion: 'DiabloDeath marks Q_DIABLO QUEST_DONE.',
    failure: 'No failed state or alternate terminal.', rewards: [], setLevel: 'SL_NONE',
    lines: [{ stage: 'journal reveal', line: 'TEXT_VILE3', speaker: 'TOWN_STORY' }],
    refs: refs('quests.cpp:255', 'monster.cpp:875', 'towners.cpp:477'),
  },
  'd1-Q_BUTCHER': {
    giver: { kind: 'towner', id: 'TOWN_DEADGUY' },
    startTrigger: { kind: 'talk-towner', condition: 'Speak to TOWN_DEADGUY while Q_BUTCHER is not QUEST_DONE; MT_CLEAVER may already exist.' },
    stages: [
      { id: 'selected', state: 'QUEST_INIT; _qvar1=0; _qlog=false', advancesWhen: 'TOWN_DEADGUY is spoken to or MT_CLEAVER is killed.' },
      { id: 'active', state: 'QUEST_ACTIVE; _qvar1=1; _qlog=true; _qmsg=TEXT_BUTCH9', advancesWhen: 'MT_CLEAVER is killed.' },
      { id: 'complete', state: 'QUEST_DONE', advancesWhen: 'TOWN_DEADGUY is removed.' },
    ],
    completion: 'Death of MT_CLEAVER marks Q_BUTCHER QUEST_DONE.',
    failure: 'No failed transition; killing MT_CLEAVER before briefing completes the quest.',
    rewards: [{ kind: 'unique-item', what: 'UITEM_CLEAVER special treasure' }], setLevel: 'SL_NONE',
    lines: [{ stage: 'briefing', line: 'TEXT_BUTCH9', speaker: 'TOWN_DEADGUY' }],
    refs: refs('towners.cpp:191', 'towners.cpp:273', 'quests.cpp:241', 'tables/monstdat.cpp:299'),
  },
  'd1-Q_LTBANNER': {
    giver: { kind: 'towner', id: 'TOWN_TAVERN' },
    startTrigger: { kind: 'talk-towner', condition: 'TOWN_TAVERN starts the primary path after the configured floor visit; SnotSpill and TEXT_BANNER10 provide the alternate path.' },
    stages: [
      { id: 'selected', state: 'QUEST_INIT; _qvar1=1; _qvar2=0; _qlog=false', advancesWhen: 'TOWN_TAVERN briefs the player or SnotSpill speaks.' },
      { id: 'ogden-briefed', state: 'QUEST_ACTIVE; _qvar1=1; _qvar2=1; _qlog=true', advancesWhen: 'TEXT_BANNER10 opens the route and sets _qvar1=2.' },
      { id: 'sign-accessible', state: 'QUEST_ACTIVE; _qvar1=2', advancesWhen: 'OBJ_SIGNCHEST spawns IDI_BANNER for either hand-in.' },
      { id: 'ogden-complete', state: 'QUEST_DONE; _qvar1=3', advancesWhen: 'TOWN_TAVERN removes IDI_BANNER and spawns UITEM_HARCREST.' },
      { id: 'snotspill-complete', state: 'QUEST_DONE; _qvar1=2 then _qvar1=3', advancesWhen: 'SnotSpill removes IDI_BANNER and TEXT_BANNER12 opens the room and hostility.' },
    ],
    completion: 'TOWN_TAVERN or SnotSpill removes IDI_BANNER.',
    failure: 'The SnotSpill hand-in is alternate completion, not failure.',
    rewards: [{ kind: 'unique-item', what: 'TOWN_TAVERN branch UITEM_HARCREST' }, { kind: 'map-unlock', what: 'SnotSpill branch room opening and hostility' }], setLevel: 'SL_NONE',
    lines: [
      { stage: 'briefing', line: 'TEXT_BANNER2', speaker: 'TOWN_TAVERN' }, { stage: 'hand-in', line: 'TEXT_BANNER3', speaker: 'TOWN_TAVERN' },
      { stage: 'alternate offer', line: 'TEXT_BANNER10', speaker: 'UniqueMonsterType::SnotSpill' }, { stage: 'alternate reminder', line: 'TEXT_BANNER11', speaker: 'UniqueMonsterType::SnotSpill' },
      { stage: 'alternate hand-in', line: 'TEXT_BANNER12', speaker: 'UniqueMonsterType::SnotSpill' },
    ],
    refs: refs('towners.cpp:243', 'objects.cpp:2104', 'monster.cpp:1434', 'monster.cpp:2630', 'monster.cpp:4752'),
  },
  'd1-Q_BLIND': {
    giver: { kind: 'object', id: 'OBJ_BLINDBOOK' },
    startTrigger: { kind: 'read-book', condition: 'Operate OBJ_BLINDBOOK while _qvar1=0.' },
    stages: [
      { id: 'selected', state: 'QUEST_INIT; _qvar1=0; _qvar2=0; _qlog=false', advancesWhen: 'OBJ_BLINDBOOK is operated.' },
      { id: 'active-reward-spawned', state: 'QUEST_ACTIVE; _qvar1=1; _qlog=true', advancesWhen: 'The map opens, UITEM_OPTAMULET spawns, and the item is picked up.' },
      { id: 'complete', state: 'QUEST_DONE', advancesWhen: 'CheckQuestItem completes the quest.' },
    ],
    completion: 'CheckQuestItem marks QUEST_DONE when UITEM_OPTAMULET is picked up.',
    failure: 'No failed transition; the one-shot book spawns the completion item.',
    rewards: [{ kind: 'unique-item', what: 'UITEM_OPTAMULET' }], setLevel: 'SL_NONE',
    lines: ['TEXT_BLINDING', 'TEXT_RBLINDING', 'TEXT_MBLINDING', 'TEXT_HBLINDING'].map((line) => ({ stage: 'book read', line, speaker: 'Hero class variant' })),
    refs: refs('objects.cpp:1924', 'objects.cpp:3857', 'inv.cpp:997'),
  },
  'd1-Q_BLOOD': {
    giver: { kind: 'object', id: 'OBJ_BLOODBOOK' },
    startTrigger: { kind: 'read-book', condition: 'Operate OBJ_BLOODBOOK while _qvar1=0.' },
    stages: [
      { id: 'selected', state: 'QUEST_INIT; _qvar1=0; _qvar2=0; _qlog=false; pedestal _oVar6=0', advancesWhen: 'OBJ_BLOODBOOK is operated.' },
      { id: 'active', state: 'QUEST_ACTIVE; _qvar1=1; _qlog=true; IDI_BLDSTONE spawned', advancesWhen: 'IDI_BLDSTONE is inserted.' },
      { id: 'stone-one', state: 'QUEST_ACTIVE; pedestal _oVar6=1', advancesWhen: 'The first area opens and another IDI_BLDSTONE is inserted.' },
      { id: 'stone-two', state: 'QUEST_ACTIVE; pedestal _oVar6=2', advancesWhen: 'The second area opens and another IDI_BLDSTONE is inserted.' },
      { id: 'reward-spawned', state: 'QUEST_ACTIVE; pedestal _oVar6=3; UITEM_ARMOFVAL spawned', advancesWhen: 'UITEM_ARMOFVAL is picked up.' },
      { id: 'complete', state: 'QUEST_DONE', advancesWhen: 'CheckQuestItem completes the quest.' },
    ],
    completion: 'CheckQuestItem marks QUEST_DONE when UITEM_ARMOFVAL is picked up.',
    failure: 'No failed transition; pedestal _oVar6 retains insertion progress.',
    rewards: [{ kind: 'unique-item', what: 'UITEM_ARMOFVAL' }], setLevel: 'SL_NONE',
    lines: ['TEXT_BLOODY', 'TEXT_RBLOODY', 'TEXT_MBLOODY', 'TEXT_HBLOODY'].map((line) => ({ stage: 'book read', line, speaker: 'Hero class variant' })),
    refs: refs('objects.cpp:1936', 'objects.cpp:2207', 'inv.cpp:1034'),
  },
  'd1-Q_ANVIL': {
    giver: { kind: 'towner', id: 'TOWN_SMITH' },
    startTrigger: { kind: 'talk-towner', condition: 'TOWN_SMITH activates and logs QUEST_INIT after the configured floor visit; IDI_ANVIL pickup can activate it hidden.' },
    stages: [
      { id: 'selected', state: 'QUEST_INIT; _qvar1=0; _qvar2=0; _qlog=false', advancesWhen: 'TOWN_SMITH briefs the player or IDI_ANVIL is picked up.' },
      { id: 'active-hidden', state: 'QUEST_ACTIVE; _qvar2=0; _qlog=false', advancesWhen: 'TOWN_SMITH sets _qvar2=1 and _qlog=true.' },
      { id: 'active-briefed', state: 'QUEST_ACTIVE; _qvar2=1; _qlog=true', advancesWhen: 'TOWN_SMITH removes IDI_ANVIL.' },
      { id: 'complete', state: 'QUEST_DONE; _qvar2=1', advancesWhen: 'UITEM_GRISWOLD is spawned.' },
    ],
    completion: 'TOWN_SMITH removes IDI_ANVIL while _qvar2=1.',
    failure: 'No failed transition; early IDI_ANVIL pickup remains recoverable.',
    rewards: [{ kind: 'unique-item', what: 'UITEM_GRISWOLD' }], setLevel: 'SL_NONE',
    lines: [{ stage: 'briefing', line: 'TEXT_ANVIL5', speaker: 'TOWN_SMITH' }, { stage: 'hand-in', line: 'TEXT_ANVIL7', speaker: 'TOWN_SMITH' }],
    refs: refs('towners.cpp:316', 'inv.cpp:1010', 'items.cpp:2451'),
  },
  'd1-Q_WARLORD': {
    giver: { kind: 'object', id: 'OBJ_STEELTOME' },
    startTrigger: { kind: 'read-book', condition: 'Operate OBJ_STEELTOME while _qvar1=QS_WARLORD_INIT.' },
    stages: [
      { id: 'selected', state: 'QUEST_INIT; _qvar1=QS_WARLORD_INIT; _qlog=false', advancesWhen: 'OBJ_STEELTOME is operated.' },
      { id: 'tome-read', state: 'QUEST_ACTIVE; _qvar1=QS_WARLORD_STEELTOME_READ; _qlog=true', advancesWhen: 'The armory opens and UniqueMonsterType::WarlordOfBlood becomes visible.' },
      { id: 'talking', state: 'QUEST_ACTIVE; _qvar1=QS_WARLORD_TALKING', advancesWhen: 'TEXT_WARLRD9 finishes.' },
      { id: 'attacking', state: 'QUEST_ACTIVE; _qvar1=QS_WARLORD_ATTACKING; dialogue cleared', advancesWhen: 'UniqueMonsterType::WarlordOfBlood is killed.' },
      { id: 'complete', state: 'QUEST_DONE', advancesWhen: 'The kill dispatcher completes the quest.' },
    ],
    completion: 'Death of UniqueMonsterType::WarlordOfBlood marks QUEST_DONE.',
    failure: 'No failed transition; dialogue protection remains until combat.',
    rewards: [{ kind: 'item-class', what: 'OBJ_WARARMOR generates ItemType::HeavyArmor' }, { kind: 'item-class', what: 'OBJ_WARWEAP generates Sword, Axe, Bow, or Mace' }], setLevel: 'SL_NONE',
    lines: [
      ...['TEXT_BLOODWAR', 'TEXT_RBLOODWAR', 'TEXT_MBLOODWAR', 'TEXT_HBLOODWAR'].map((line) => ({ stage: 'tome read', line, speaker: 'Hero class variant' })),
      { stage: 'confrontation', line: 'TEXT_WARLRD9', speaker: 'UniqueMonsterType::WarlordOfBlood' },
    ],
    refs: refs('objects.cpp:1944', 'objects.cpp:3169', 'objects.cpp:3324', 'monster.cpp:1458', 'monster.cpp:282', 'monster.cpp:2984'),
  },
  'd1-Q_SKELKING': {
    giver: { kind: 'towner', id: 'TOWN_TAVERN' },
    startTrigger: { kind: 'talk-towner', condition: 'TOWN_TAVERN activates and logs the quest after a configured floor visit; SL_SKELKING entry can activate it hidden.' },
    stages: [
      { id: 'selected', state: 'QUEST_INIT; _qvar1=0; _qvar2=0; _qlog=false', advancesWhen: 'TOWN_TAVERN briefs the player or SL_SKELKING loads.' },
      { id: 'active-from-ogden', state: 'QUEST_ACTIVE; _qvar1=1; _qvar2=1; _qlog=true', advancesWhen: 'MT_SKING is killed.' },
      { id: 'active-from-entry', state: 'QUEST_ACTIVE; _qvar1=1; _qvar2=0; _qlog=false', advancesWhen: 'MT_SKING is killed or TOWN_TAVERN is spoken to.' },
      { id: 'complete', state: 'QUEST_DONE', advancesWhen: 'TOWN_TAVERN supplies the epilogue when _qvar2=1.' },
      { id: 'epilogue', state: 'QUEST_DONE; _qvar1=2; _qvar2=2', advancesWhen: 'The epilogue is terminal.' },
    ],
    completion: 'Death of MT_SKING marks QUEST_DONE.',
    failure: 'No failed transition; SL_SKELKING entry activates an unbriefed quest.',
    rewards: [{ kind: 'unique-item', what: 'UITEM_SKCROWN special treasure' }], setLevel: 'SL_SKELKING',
    lines: [{ stage: 'briefing', line: 'TEXT_KING2', speaker: 'TOWN_TAVERN' }, { stage: 'epilogue', line: 'TEXT_KING4', speaker: 'TOWN_TAVERN' }],
    refs: refs('towners.cpp:219', 'levels/setmaps.cpp:115', 'quests.cpp:234', 'quests.cpp:354', 'tables/monstdat.cpp:305'),
  },
  'd1-Q_PWATER': {
    giver: { kind: 'towner', id: 'TOWN_HEALER' },
    startTrigger: { kind: 'talk-towner', condition: 'TOWN_HEALER activates after a configured floor visit; SL_POISONWATER entry can activate it hidden.' },
    stages: [
      { id: 'selected', state: 'QUEST_INIT; _qvar1=0; _qvar2=0; _qlog=false', advancesWhen: 'TOWN_HEALER briefs the player or SL_POISONWATER loads.' },
      { id: 'active-hidden', state: 'QUEST_ACTIVE; _qlog=false', advancesWhen: 'TOWN_HEALER logs the discovered cave or the cave is cleansed.' },
      { id: 'active-logged', state: 'QUEST_ACTIVE; _qlog=true; _qmsg=TEXT_POISON3', advancesWhen: 'ActiveMonsterCount in SL_POISONWATER becomes exactly 4.' },
      { id: 'complete-unrewarded', state: 'QUEST_DONE; _qlog=true; _qvar1!=2', advancesWhen: 'TOWN_HEALER is spoken to.' },
      { id: 'complete-rewarded', state: 'QUEST_DONE; _qvar1=2', advancesWhen: 'UITEM_TRING is spawned.' },
    ],
    completion: 'The SL_POISONWATER survivor check observes ActiveMonsterCount equal to 4.',
    failure: 'No failed transition; reward collection follows completion.',
    rewards: [{ kind: 'unique-item', what: 'UITEM_TRING after completion' }], setLevel: 'SL_POISONWATER',
    lines: [{ stage: 'briefing', line: 'TEXT_POISON3', speaker: 'TOWN_HEALER' }, { stage: 'reward', line: 'TEXT_POISON5', speaker: 'TOWN_HEALER' }],
    refs: refs('towners.cpp:413', 'levels/setmaps.cpp:138', 'quests.cpp:175', 'quests.cpp:326'),
  },
  'd1-Q_SCHAMB': {
    giver: { kind: 'object', id: 'OBJ_BOOK2R' },
    startTrigger: { kind: 'read-book', condition: 'Operate the interactable OBJ_BOOK2R while QUEST_INIT.' },
    stages: [
      { id: 'selected', state: 'QUEST_INIT; _qvar1=0; _qvar2=0; _qlog=false', advancesWhen: 'OBJ_BOOK2R is operated.' },
      { id: 'active', state: 'QUEST_ACTIVE; _qvar1=0; _qvar2=0; _qlog=true', advancesWhen: 'The final book in SL_BONECHAMB is operated.' },
      { id: 'complete', state: 'QUEST_DONE', advancesWhen: 'SpellID::Guardian is increased when within MaxSpellLevel.' },
    ],
    completion: 'Operate the final book inside SL_BONECHAMB.',
    failure: 'No failed transition; exceeding MaxSpellLevel only suppresses the reward.',
    rewards: [{ kind: 'spell-level', what: 'SpellID::Guardian increment within MaxSpellLevel' }], setLevel: 'SL_BONECHAMB',
    lines: ['TEXT_BONER', 'TEXT_RBONER', 'TEXT_MBONER', 'TEXT_HBONER'].map((line) => ({ stage: 'entrance book', line, speaker: 'Hero class variant' })),
    refs: refs('objects.cpp:1881', 'objects.cpp:1969', 'levels/drlg_quests.cpp:38'),
  },
  'd1-Q_BETRAYER': {
    giver: { kind: 'towner', id: 'TOWN_STORY' },
    startTrigger: { kind: 'talk-towner', condition: 'TOWN_STORY removes IDI_LAZSTAFF while QUEST_INIT; multiplayer progression activates the quest near its configured floor.' },
    stages: [
      { id: 'selected', state: 'QUEST_INIT; _qvar1=0; _qvar2=0; _qlog=false', advancesWhen: 'TOWN_STORY removes IDI_LAZSTAFF.' },
      { id: 'staff-given', state: 'QUEST_ACTIVE; _qvar1=2; _qvar2=0; _qlog=true', advancesWhen: 'The portal check creates the SL_VILEBETRAYER entry portal.' },
      { id: 'portal-open', state: 'QUEST_ACTIVE; _qvar1=3; _qvar2=1', advancesWhen: 'SL_VILEBETRAYER loads and changes _qvar2.' },
      { id: 'inner-gate', state: 'QUEST_ACTIVE; _qvar1=4; _qvar2=3', advancesWhen: 'The scripted books and circles open the inner area.' },
      { id: 'greeting', state: 'QUEST_ACTIVE; _qvar1=5', advancesWhen: 'TEXT_VILE13 finishes.' },
      { id: 'combat', state: 'QUEST_ACTIVE; _qvar1=6; Lazarus dialogue cleared', advancesWhen: 'UniqueMonsterType::Lazarus is killed.' },
      { id: 'complete-exit-requested', state: 'QUEST_DONE; _qvar1=7; _qvar2=4; Q_DIABLO=QUEST_ACTIVE', advancesWhen: 'The set-level exit portal is created.' },
      { id: 'epilogue', state: 'QUEST_DONE; _qvar1=8; Q_DIABLO._qlog=true', advancesWhen: 'TOWN_STORY supplies the epilogue.' },
    ],
    completion: 'Death of UniqueMonsterType::Lazarus marks QUEST_DONE and activates Q_DIABLO.',
    failure: 'No failed transition; dialogue protection remains until combat.',
    rewards: [{ kind: 'map-unlock', what: 'SL_VILEBETRAYER exit, onward access, and Q_DIABLO activation' }], setLevel: 'SL_VILEBETRAYER',
    lines: [{ stage: 'staff hand-in', line: 'TEXT_VILE1', speaker: 'TOWN_STORY' }, { stage: 'greeting', line: 'TEXT_VILE13', speaker: 'UniqueMonsterType::Lazarus' }, { stage: 'epilogue', line: 'TEXT_VILE3', speaker: 'TOWN_STORY' }],
    refs: refs('towners.cpp:457', 'objects.cpp:1492', 'objects.cpp:1842', 'quests.cpp:142', 'quests.cpp:255', 'monster.cpp:2879', 'levels/setmaps.cpp:145'),
  },
};
