/** Engine-derived Diablo I actor states. Values are transcribed from the pinned Source, not a data table. */
import type { StatusSpecData } from '@/lib/catalog/reference/statusSpecs';

type SourceReference = `.reference/devilutionX/Source/${string}`;

const pinned = (reference: SourceReference): string =>
  `https://github.com/diasurgical/devilutionX/blob/4138a82/Source/${reference.slice('.reference/devilutionX/Source/'.length)}`;
const refs = (...references: SourceReference[]) => references.map(pinned);

export const STATUS_SPECS_DATA = [
  {
    id: 'd1-stone-curse-petrification', name: 'Stone Curse petrification', appliesTo: 'monster',
    source: 'SpellID::StoneCurse / MissileID::StoneCurse',
    duration: '16 × min(spellLevel + 6, 15) game ticks',
    stacking: 'None; casting on a petrified target is rejected.',
    effect: "Saves the monster's current mode in the controlling missile, changes its mode to Petrified, freezes animation and AI, and makes subsequent attack rolls against it succeed when otherwise hittable. Golem, Diablo, Na-Krul, fading, and charging targets are ineligible.",
    removal: 'Expiry restores the saved mode and clears the petrified animation flag. Death produces the stone-shatter path. Removing the caster\'s missiles restores the saved mode early.',
    hellfire: false,
    lawBody: 'Stone Curse petrification, derived from the engine: an eligible monster enters Petrified mode for 16 × min(spell level + 6, 15) ticks while a missile remembers its prior mode. Recasting does not stack. Golem, Diablo, Na-Krul, fading, and charging monsters cannot be selected; expiry restores the saved mode, while death shatters the statue.',
    refs: refs('.reference/devilutionX/Source/missiles.cpp:2363', '.reference/devilutionX/Source/missiles.cpp:2399', '.reference/devilutionX/Source/missiles.cpp:2412', '.reference/devilutionX/Source/missiles.cpp:3698', '.reference/devilutionX/Source/player.cpp:2888'),
  },
  {
    id: 'd1-fire-wall-contact-damage', name: 'Fire Wall contact damage', appliesTo: 'both',
    source: 'SpellID::FireWall / MissileID::FireWall; traps and scripted fire walls use the same missile',
    duration: '16 × (10 × (spellLevel + 1 when spellLevel > 0, otherwise 10) + current dungeon level for monster/trap sources) ticks per segment',
    stacking: 'Independent missiles; overlapping segments make independent collision checks. No actor-side stack exists.',
    effect: 'Each live wall segment calls missile collision every game tick and applies its fire hit to an eligible actor occupying the tile. It stores no burning flag, remaining damage, or duration on the actor.',
    removal: 'The segment deletes itself when its missile duration reaches zero; leaving the tile merely stops further collision checks.', hellfire: false,
    lawBody: 'Fire Wall contact damage, derived from the engine: each wall segment is a timed tile missile that reruns collision damage every tick. An actor is damaged only through current tile contact; no Burning field, actor timer, periodic-effect record, or cleanse path is created. Overlapping segments remain independent hazards rather than status stacks.',
    refs: refs('.reference/devilutionX/Source/missiles.cpp:1961', '.reference/devilutionX/Source/missiles.cpp:3065'),
  },
  {
    id: 'd1-inferno-contact-damage', name: 'Inferno contact damage', appliesTo: 'both',
    source: 'SpellID::Inferno / MissileID::InfernoControl and MissileID::Inferno',
    duration: 'Three generated flame segments last 20, 25, and 30 game ticks respectively.',
    stacking: 'Independent flame missiles; no actor-side stack or refresh.',
    effect: 'The control missile advances for at most three tiles and creates one flame missile per tile. Each flame checks collision and deals its fixed-point hit each game tick while an eligible actor occupies that tile.',
    removal: 'Each flame deletes itself at zero duration; moving away ends exposure immediately.', hellfire: false,
    lawBody: 'Inferno contact damage, derived from the engine: its controller lays at most three flame missiles whose lifetimes are 20, 25, and 30 ticks. Each missile reruns collision damage on its tile. The target acquires no burning state or independent duration, so leaving the flame ends exposure and overlapping flames act independently.',
    refs: refs('.reference/devilutionX/Source/missiles.cpp:2672', '.reference/devilutionX/Source/missiles.cpp:3940', '.reference/devilutionX/Source/missiles.cpp:3964'),
  },
  {
    id: 'd1-acid-puddle-contact-damage', name: 'Acid Puddle contact damage', appliesTo: 'hero',
    source: 'MissileID::AcidPuddle created by a monster acid projectile',
    duration: '40 × (monster intelligence + 1) + R(15) damaging ticks, where R(15) is 0–14, followed by its ending animation',
    stacking: 'Independent puddle missiles; no hero-side stack.',
    effect: 'The puddle reruns acid collision damage on its tile every game tick and preserves its own countdown even after a hit. It does not set a poison, acid, or damage-over-time field on the hero.',
    removal: 'The damaging countdown reaches zero, then the puddle changes to its ending animation and is deleted; leaving the tile stops damage.', hellfire: false,
    lawBody: 'Acid Puddle contact damage, derived from the engine: the monster-created puddle owns a 40 × (intelligence + 1) + R(15) tick lifetime and checks its tile every tick. It is persistent terrain, not poison or an attached damage-over-time state; moving off the tile stops damage, and overlapping puddles remain separate.',
    refs: refs('.reference/devilutionX/Source/missiles.cpp:2355', '.reference/devilutionX/Source/missiles.cpp:3048'),
  },
  {
    id: 'd1-knockback', name: 'Knockback', appliesTo: 'both',
    source: 'ItemSpecialEffect::Knockback on player melee/arrows; MFLAG_KNOCKBACK on monsters',
    duration: 'Instant one-tile displacement; any resulting hit recovery has its own animation lifetime.',
    stacking: 'None; every qualifying hit attempts one displacement.',
    effect: 'Player knockback moves a non-petrified monster one tile away when the destination is legal, then starts monster hit recovery. Monster knockback forces hero hit recovery when needed and moves the hero one tile in the attack direction when legal.',
    removal: 'No persistent knockback state exists. Displacement is complete immediately; hit recovery ends separately with its animation.', hellfire: false,
    lawBody: "Knockback, derived from the engine: it is an immediate one-tile move attempted on a qualifying hit, not a timed status. Illegal movement cancels the displacement, and petrified monsters cannot be moved. A successful monster displacement starts its hit animation; a monster's knockback attack similarly moves the hero and may force hero recovery.",
    refs: refs('.reference/devilutionX/Source/player.cpp:695', '.reference/devilutionX/Source/missiles.cpp:340', '.reference/devilutionX/Source/monster.cpp:1245', '.reference/devilutionX/Source/monster.cpp:3950'),
  },
  {
    id: 'd1-monster-hit-recovery', name: 'Monster hit recovery', appliesTo: 'monster',
    source: 'M_StartHit / StartMonsterGotHit after a hard hit or knockback',
    duration: 'GotHit animation frame count × its animation rate in game ticks, subject to same-tick animation scheduling',
    stacking: 'No stack; another qualifying hit restarts the mode and animation. Golems do not enter this mode.',
    effect: 'A hard hit is damage/64 at least difficulty-adjusted monster level + 3; Sneak, Stalker, Unseen, and Illusion Weaver always qualify. The monster enters HitRecovery and cannot run its normal AI until the animation finishes. Petrified monsters do not enter it.',
    removal: 'The final GotHit animation frame calls M_StartStand. Death or petrification supersedes normal recovery.', hellfire: false,
    lawBody: 'Monster hit recovery, derived from the engine: a hard hit changes a non-Golem, non-petrified monster to HitRecovery for its data-defined GotHit animation. Damage/64 must reach adjusted level + 3, except four sneaking types always qualify. Completion returns it to Stand; a new qualifying hit restarts the animation rather than adding a stack.',
    refs: refs('.reference/devilutionX/Source/monster.cpp:661', '.reference/devilutionX/Source/monster.cpp:986', '.reference/devilutionX/Source/monster.cpp:1470', '.reference/devilutionX/Source/monster.cpp:3963'),
  },
  {
    id: 'd1-hero-hit-recovery', name: 'Hero hit recovery', appliesTo: 'hero',
    source: 'StartPlrHit after damage or a forced impact',
    duration: 'recoveryFrames − skippedFrames game ticks at one tick per frame; skippedFrames is 0, 1, 2, or 3 from the best recovery item flag',
    stacking: 'No stack; a new forced recovery call replaces/restarts the player mode and animation.',
    effect: 'A normal hero enters PM_GOTHIT when damage/64 reaches character level; Barbarian requires level + floor(level/4). A forced hit bypasses the threshold. Fast, Faster, and Fastest Hit Recovery skip one, two, and three animation frames.',
    removal: 'The last recovery frame returns the hero to standing and clears temporary action variables; death supersedes it.', hellfire: false,
    lawBody: 'Hero hit recovery, derived from the engine: sufficient or forced damage changes the hero to PM_GOTHIT for the recovery animation at one tick per frame. Fast, Faster, and Fastest recovery skip one, two, or three frames. The final frame returns to Stand; this is an action mode, not a dispellable crowd-control instance.',
    refs: refs('.reference/devilutionX/Source/player.cpp:1031', '.reference/devilutionX/Source/player.cpp:1819', '.reference/devilutionX/Source/player.cpp:2639'),
  },
  {
    id: 'd1-monster-retreat-goal', name: 'Monster retreat and fleeing', appliesTo: 'monster',
    source: 'MonsterGoal::Retreat assigned by individual AI routines and M_FallenFear',
    duration: 'AI-specific; no universal tick duration. Fallen fear uses max(8 − base monster level, 2) retreat decisions before normalization.',
    stacking: 'Assignments overwrite the existing goal and goal variables; there is no stack.',
    effect: 'Retreat is an AI goal interpreted separately by Fallen, bats, scavengers, sneaks, counselors, and other routines. Direction, decision counters, distance checks, healing, and fade behavior differ by AI; it is not a shared fear debuff.',
    removal: 'The owning AI changes the goal back to Normal after its counter, distance, movement, or healing condition is met.', hellfire: false,
    lawBody: 'Monster retreat and fleeing, derived from the engine: Retreat is an AI goal, not a generic fear status. Each AI supplies its own movement and exit rules. Fallen fear writes a direction and a decision counter of max(8 − base level, 2); other monsters retreat because of health, distance, or prior actions and clear the goal under their own conditions.',
    refs: refs('.reference/devilutionX/Source/monster.h:121', '.reference/devilutionX/Source/monster.cpp:2314', '.reference/devilutionX/Source/monster.cpp:2432', '.reference/devilutionX/Source/monster.cpp:2724', '.reference/devilutionX/Source/monster.cpp:4450'),
  },
  {
    id: 'd1-golem-monster-target', name: 'Golem monster targeting', appliesTo: 'monster',
    source: 'MFLAG_TARGETS_MONSTER, enemy index, and enemyPosition selected by UpdateEnemy for a player minion',
    duration: 'Until target reselection, invalidation, death, or Golem death; no timer.',
    stacking: 'Single target; reselection overwrites the enemy index and position.',
    effect: 'The state belongs to the Golem, not its victim. MFLAG_TARGETS_MONSTER makes enemy refer to a monster; Golem AI faces, paths to, activates, and attacks that monster. Player minions exclude one another as targets.',
    removal: 'UpdateEnemy may replace the target. Target deletion marks monster-targeting attackers MFLAG_NO_ENEMY; Golem deletion or level transition ends the state.', hellfire: false,
    lawBody: 'Golem monster targeting, derived from the engine: the Golem stores one enemy index plus MFLAG_TARGETS_MONSTER; no mark is placed on the victim. Its AI paths to and attacks that selected monster, while target deletion sets No Enemy and later selection may overwrite the index. This is persistent AI targeting, not a taunt or status stack.',
    refs: refs('.reference/devilutionX/Source/monster.cpp:679', '.reference/devilutionX/Source/monster.cpp:706', '.reference/devilutionX/Source/monster.cpp:4157'),
  },
  {
    id: 'd1-monster-inherent-immunity', name: 'Monster inherent immunity', appliesTo: 'monster',
    source: 'monstdat resistance/resistanceHell columns and hard-coded missile eligibility rules',
    duration: 'Monster lifetime; resistance set changes when the monster is initialized for Hell difficulty.',
    stacking: 'Bit flags combine; they are not timed stacks.',
    effect: 'IMMUNE_MAGIC, IMMUNE_FIRE, IMMUNE_LIGHTNING, and IMMUNE_ACID reject matching missile damage before hit resolution. Holy Bolt has class/type eligibility rules. Stone Curse separately rejects Golem, Diablo, and Na-Krul. The immunity function contains no Diablo-specific Apocalypse branch.',
    removal: 'Not dispellable. Only different source data, difficulty initialization, or monster replacement changes it.', hellfire: false,
    lawBody: 'Monster inherent immunity, derived from the engine: elemental immunity is a lifetime resistance bit check performed before missile hit resolution, with separate Holy Bolt and Stone Curse eligibility rules. Diablo is explicitly unpetrifiable, but the immunity function has no Apocalypse-specific Diablo case; Apocalypse uses the ordinary missile immunity path.',
    refs: refs('.reference/devilutionX/Source/monster.cpp:235', '.reference/devilutionX/Source/monster.cpp:278', '.reference/devilutionX/Source/monster.cpp:4934', '.reference/devilutionX/Source/missiles.cpp:2378', '.reference/devilutionX/Source/tables/monstdat.cpp:396'),
  },
  {
    id: 'd1-apocalypse-impact-not-status', name: 'Apocalypse impact', appliesTo: 'monster',
    source: 'SpellID::Apocalypse / MissileID::Apocalypse and MissileID::ApocalypseBoom',
    duration: 'The controller starts at 255 ticks but deletes after scanning its bounded area; each boom lasts its animation and checks until its first hit or expiry.',
    stacking: 'Independent casts and boom missiles; no actor-side stack.',
    effect: 'The controller finds each non-minion monster in its area and creates a boom. Diablo is not skipped. Each boom uses ordinary missile collision and monster immunity; no Apocalypse-marked, burning, or delayed actor state is created.',
    removal: 'The controller deletes after its scan and each boom deletes after its animation. There is no actor state to remove.', hellfire: false,
    lawBody: "Apocalypse impact, derived from the engine: the spell scans nearby tiles and creates one ordinary impact missile for each non-minion monster. Diablo is not specially skipped, and each impact follows normal collision and immunity checks. The impact's animation is transient missile state; it never grants an Apocalypse status to the monster.",
    refs: refs('.reference/devilutionX/Source/missiles.cpp:2657', '.reference/devilutionX/Source/missiles.cpp:3726', '.reference/devilutionX/Source/missiles.cpp:3853'),
  },
  {
    id: 'd1-mana-shield', name: 'Mana Shield', appliesTo: 'hero',
    source: 'SpellID::ManaShield; Magical shrine invokes MissileID::ManaShield',
    duration: 'Until mana is exhausted, No Mana becomes equipped, a level change occurs, or the shield is explicitly removed.',
    stacking: 'None; casting while pManaShield is true fizzles.',
    effect: 'pManaShield diverts positive damage to mana. At learned levels 1–7, damage is first reduced using denominator 24 − 3 × level; any portion exceeding available mana is converted back before reaching life. A zero learned level still permits the shrine-created shield without the reduction bonus.',
    removal: 'Zero mana, insufficient mana after absorption, No Mana equipment, network removal, or InitLevelChange clears pManaShield.', hellfire: false,
    lawBody: 'Mana Shield, derived from the engine: one player boolean redirects positive damage to mana until mana fails, No Mana is equipped, removal is synchronized, or the level changes. Recasting while active fizzles. Learned levels up to seven reduce converted damage through the engine denominator; there is no duration, stack count, or general dispel interface.',
    refs: refs('.reference/devilutionX/Source/missiles.cpp:2161', '.reference/devilutionX/Source/missiles.cpp:4202', '.reference/devilutionX/Source/player.cpp:1738', '.reference/devilutionX/Source/player.cpp:2825', '.reference/devilutionX/Source/objects.cpp:2392'),
  },
  {
    id: 'd1-infravision', name: 'Infravision', appliesTo: 'hero',
    source: 'SpellID::Infravision / MissileID::Infravision; Murky Pool invokes the same missile',
    duration: 'S(spellLevel) ticks, where S(0)=1584 and S(n+1)=S(n)+floor(S(n)/8).',
    stacking: 'Separate casts create independent timers; effective vision is true while any timer is processed. Durations are not merged.',
    effect: "Each live missile sets the source player's _pInfraFlag after the per-tick player validation clears it. Rendering uses that flag to reveal otherwise dark actors and floor treatment; no monster is marked.",
    removal: 'After the last missile expires, the next player validation tick clears _pInfraFlag. Level missile cleanup also ends it.', hellfire: false,
    lawBody: 'Infravision, derived from the engine: a source-owned missile lasts S(level) ticks, with S(0)=1584 and each level adding one eighth of the current value. Player validation clears the flag every tick and live missiles set it again, so separate casts act as parallel timers rather than stacks. The flag disappears after the final timer expires.',
    refs: refs('.reference/devilutionX/Source/missiles.cpp:2559', '.reference/devilutionX/Source/missiles.cpp:3842', '.reference/devilutionX/Source/player.cpp:1415', '.reference/devilutionX/Source/objects.cpp:3262', '.reference/devilutionX/Source/engine/render/scrollrt.cpp:396'),
  },
  {
    id: 'd1-teleport-phasing-relocation', name: 'Teleport and Phasing relocation', appliesTo: 'hero',
    source: 'SpellID::Teleport, SpellID::Phasing, and Holy shrine Phasing',
    duration: 'The relocation missile lasts 2 ticks; position changes on its first processing tick. No effect persists on the hero.',
    stacking: 'None.',
    effect: 'The missile finds a legal destination, clears the old occupancy and transparency state, writes tile/future/old positions, updates light and vision, and centers the local view. Phasing chooses a random legal distant tile; Teleport searches near the requested tile.',
    removal: 'The two-tick missile deletes itself. There is no phasing, invulnerability, or teleport status to cleanse.', hellfire: false,
    lawBody: 'Teleport and Phasing relocation, derived from the engine: both use a two-tick missile to perform one immediate position rewrite and then delete it. They grant no lingering phasing, untargetability, or invulnerability flag. The Holy shrine invokes the same Phasing relocation path, so these are movement events rather than statuses.',
    refs: refs('.reference/devilutionX/Source/missiles.cpp:1829', '.reference/devilutionX/Source/missiles.cpp:1931', '.reference/devilutionX/Source/missiles.cpp:3661', '.reference/devilutionX/Source/objects.cpp:2644'),
  },
  {
    id: 'd1-etherealize-dead-hook', name: 'Etherealize engine hook', appliesTo: 'hero',
    source: 'SpellID::Etherealize, MissileID::Etherealize, and SpellFlag::Etherealize',
    duration: 'A loaded/set flag would last until InitMissiles clears it; the spell path does not set the flag or create a timer.',
    stacking: 'None; no implemented application exists.',
    effect: 'Combat predicates would reject monster melee, player melee, and arrow hits while SpellFlag::Etherealize is set. The pinned Source has checks and a flag definition but no assignment that activates it; the Etherealize missile has no add/process implementation.',
    removal: 'InitMissiles clears the flag. Ordinary casting supplies no active state to remove.', hellfire: false,
    lawBody: 'Etherealize engine hook, derived from the engine: combat code would ignore melee and arrow hits while SpellFlag::Etherealize is set, but no Source path sets that flag and its missile has no add or process behavior. InitMissiles clears any loaded flag. It is therefore a dormant engine hook, not a reachable timed vanilla status.',
    refs: refs('.reference/devilutionX/Source/player.h:147', '.reference/devilutionX/Source/player.cpp:708', '.reference/devilutionX/Source/monster.cpp:1174', '.reference/devilutionX/Source/missiles.cpp:374', '.reference/devilutionX/Source/missiles.cpp:1209', '.reference/devilutionX/Source/tables/spelldat.h:134'),
  },
  {
    id: 'd1-invisibility-unused', name: 'Invisibility', appliesTo: 'hero',
    source: 'SpellID::Invisibility / unused MissileID::Invisibility',
    duration: 'None; no implemented state or timer.', stacking: 'None.',
    effect: 'The identifiers and unused missile slot exist, but there is no add function, process function, player flag, targeting check, or rendering check that makes the hero invisible.',
    removal: 'Not applicable because no state is applied.', hellfire: false,
    lawBody: 'Invisibility, derived from the engine: the spell and an explicitly unused missile identifier exist, but no player field, add routine, process routine, targeting predicate, or rendering predicate implements invisibility. Casting data cannot produce a persistent invisible state in the pinned engine.',
    refs: refs('.reference/devilutionX/Source/tables/spelldat.h:51', '.reference/devilutionX/Source/tables/spelldat.h:132', '.reference/devilutionX/Source/missiles.cpp:914'),
  },
  {
    id: 'd1-rage-two-phase-hook', name: 'Rage two-phase engine state', appliesTo: 'hero',
    source: 'SpellID::Rage / MissileID::Rage, historically the Blood Boil slot',
    duration: 'Active for 245 + 2 × characterLevel ticks, then cooldown for the same duration.',
    stacking: 'None; application fizzles during either phase.',
    effect: 'Active adds 2×level Strength, floor(1.5×level) Dexterity, and 2×level Vitality. Cooldown applies the same penalties and subtracts level from each resistance. On cooldown expiry the hero takes 6×level life damage but is kept at at least 1 HP. The engine path exists, but ordinary pinned-content provisioning is not established by Source alone.',
    removal: 'The missile changes Active to Cooldown at first expiry, then clears Cooldown, deletes itself, recalculates items, and applies the nonlethal final damage.', hellfire: false,
    lawBody: 'Rage two-phase engine state, derived from the engine: its missile grants level-scaled attributes for 245 + 2 × level ticks, then applies equal attribute penalties and −level resistances for the same time. Recasting during either phase fizzles; final expiry clears the flags and deals nonlethal life damage. This is an engine hook, not confirmed reachable vanilla content.',
    refs: refs('.reference/devilutionX/Source/missiles.cpp:2588', '.reference/devilutionX/Source/missiles.cpp:3909', '.reference/devilutionX/Source/items.cpp:2515', '.reference/devilutionX/Source/items.cpp:2605', '.reference/devilutionX/Source/tables/spelldat.h:54'),
  },
  {
    id: 'd1-monster-attribute-drain', name: 'Permanent monster attribute drain', appliesTo: 'hero',
    source: 'monstdat reducePlayerStrength, reducePlayerMagic, reducePlayerDexterity, and reducePlayerVitality columns',
    duration: 'Permanent base-character mutation.', stacking: 'Cumulative on every successful, unblocked melee hit, clamped at zero.',
    effect: 'After melee hit and block checks succeed, each nonzero monster column is subtracted through ModifyPlrStr/Mag/Dex/Vit. These functions change both current and base attributes; Magic and Vitality also recalculate base resources according to class coefficients.',
    removal: 'No cleanse or automatic restoration. Later permanent gains can offset the loss; otherwise it remains in character state.', hellfire: false,
    lawBody: "Permanent monster attribute drain, derived from the engine: after a successful unblocked melee hit, each configured reducePlayer Strength, Magic, Dexterity, or Vitality column subtracts from the hero's base statistic. Repeated hits accumulate down to zero. The change is saved character data, not a timed debuff, and no cleanse restores it.",
    refs: refs('.reference/devilutionX/Source/tables/monstdat.cpp:388', '.reference/devilutionX/Source/monster.cpp:1174', '.reference/devilutionX/Source/monster.cpp:3885', '.reference/devilutionX/Source/player.cpp:3306'),
  },
  {
    id: 'd1-monster-max-resource-drain', name: 'Permanent monster maximum-resource drain', appliesTo: 'hero',
    source: 'monstdat reducePlayerMaxHP and reducePlayerMaxMana columns', duration: 'Permanent base-character mutation.',
    stacking: 'Cumulative per successful, unblocked melee hit; maximum life floors at 1 HP and maximum mana at 0.',
    effect: 'The configured whole-point amount is converted to fixed-point units and removed from current and base maxima. Current life/mana and their base values are clamped down to the new maxima. The code prevents reducing base maximum life below 1 HP or mana below zero.',
    removal: 'No cleanse or automatic restoration; only another permanent character mutation or external correction can offset it.', hellfire: false,
    lawBody: 'Permanent monster maximum-resource drain, derived from the engine: a successful unblocked melee hit can subtract configured whole points from base maximum life or mana, clamping life to at least 1 and mana to at least 0 and lowering current resources when necessary. Hits accumulate permanently; the engine creates no timed curse or removal action.',
    refs: refs('.reference/devilutionX/Source/tables/monstdat.cpp:392', '.reference/devilutionX/Source/monster.cpp:3902'),
  },
  {
    id: 'd1-instant-potion-restoration', name: 'Potion restoration', appliesTo: 'hero',
    source: 'IMISC_HEAL, IMISC_FULLHEAL, IMISC_MANA, IMISC_FULLMANA, IMISC_REJUV, and IMISC_FULLREJUV',
    duration: 'Instant.', stacking: 'None; each consumed item performs another immediate mutation.',
    effect: 'Partial life or mana restores floor(max/8)+R(floor(max/4)) whole-resource basis, with class multipliers, then clamps current and base values to their maxima. Full potions set the resource to maximum. Rejuvenation invokes both life and mana operations. No Mana prevents partial mana restoration.',
    removal: 'Not applicable; the resource change is immediate and later spending or damage changes it normally.', hellfire: false,
    lawBody: 'Potion restoration, derived from the engine: healing, mana, and rejuvenation potions immediately mutate current resources and create no timer or buff. Partial potions use a maximum-resource random formula plus class multipliers; full potions set the resource to maximum. Repeated drinks are separate instant operations, not status stacks.',
    refs: refs('.reference/devilutionX/Source/items.cpp:4206', '.reference/devilutionX/Source/player.cpp:1744'),
  },
  {
    id: 'd1-elixir-attribute-gain', name: 'Elixir attribute gain', appliesTo: 'hero',
    source: 'IMISC_ELIXSTR, IMISC_ELIXMAG, IMISC_ELIXDEX, IMISC_ELIXVIT; IMISC_SPECELIX in Hellfire',
    duration: 'Permanent base-character mutation.', stacking: 'Cumulative, subject to each class attribute cap.',
    effect: 'A normal elixir adds one point to its named base attribute through ModifyPlr*. The Hellfire special elixir adds three to all four. Hellfire Magic and Vitality elixirs additionally fill mana or life, respectively; those fills are instant.',
    removal: 'No cleanse or automatic expiry; permanent drains or other base-stat mutations may later offset it.', hellfire: false,
    lawBody: "Elixir attribute gain, derived from the engine: each ordinary elixir permanently adds one capped base-stat point; the Hellfire special elixir adds three to all four. These are saved character mutations, not timed potion buffs. Hellfire's extra full-mana or full-life restoration is immediate and does not alter that lifetime.",
    refs: refs('.reference/devilutionX/Source/items.cpp:4235', '.reference/devilutionX/Source/items.cpp:4338', '.reference/devilutionX/Source/player.cpp:3306'),
  },
  {
    id: 'd1-shrine-base-stat-mutations', name: 'Vanilla shrine base-stat mutations', appliesTo: 'hero',
    source: 'Mysterious, Eerie, Abandoned, Creepy, Quiet, and multiplayer Tainted shrines',
    duration: 'Permanent base-character mutation.', stacking: 'Repeated shrine results accumulate, subject to class caps and zero floors.',
    effect: 'Mysterious subtracts one from every base stat and adds six to one random stat. Eerie adds two Magic; Abandoned two Dexterity; Creepy two Strength; Quiet two Vitality. Tainted affects other multiplayer heroes with +1 to one random stat and −1 to each other stat.',
    removal: 'No expiry or cleanse; later permanent stat changes can offset the values.', hellfire: false,
    lawBody: 'Vanilla shrine base-stat mutations, derived from the engine: Mysterious applies net +5 to one random stat and −1 to the other three; Eerie, Abandoned, Creepy, and Quiet permanently add two to one named stat. Multiplayer Tainted applies +1 to one random stat and −1 to the other three on other heroes. None creates a timed shrine buff.',
    refs: refs('.reference/devilutionX/Source/objects.cpp:2250', '.reference/devilutionX/Source/objects.cpp:2602', '.reference/devilutionX/Source/objects.cpp:2692', '.reference/devilutionX/Source/objects.cpp:2760'),
  },
  {
    id: 'd1-shrine-spell-mana-mutations', name: 'Vanilla shrine spell and mana mutations', appliesTo: 'hero',
    source: 'Enchanted, Fascinating, Sacred, and Ornate shrines', duration: 'Permanent character mutation.',
    stacking: 'Repeated uses mutate levels and base mana again; spell levels are capped.',
    effect: 'Enchanted raises every eligible learned spell except one randomly selected learned spell, which loses one level. Fascinating, Sacred, and Ornate learn and add up to two levels to Firebolt, Charged Bolt, or Holy Bolt respectively, then subtract floor(current base maximum mana/10) from base/current maximum and current mana.',
    removal: 'No expiry or cleanse; later books, shrines, or permanent resource changes can offset the mutation.', hellfire: false,
    lawBody: 'Vanilla shrine spell and mana mutations, derived from the engine: Enchanted permanently raises eligible learned spells while lowering one random learned spell. Fascinating, Sacred, and Ornate permanently add up to two levels to one fixed spell and remove one tenth of current base maximum mana. These changes accumulate as character data, not timed effects.',
    refs: refs('.reference/devilutionX/Source/objects.cpp:2439', '.reference/devilutionX/Source/objects.cpp:2504', '.reference/devilutionX/Source/objects.cpp:3032'),
  },
  {
    id: 'd1-shrine-item-mutations', name: 'Vanilla shrine item mutations', appliesTo: 'hero',
    source: 'Hidden, Gloomy, Weird, Stone, Religious, Eldritch, and Glimmering shrines',
    duration: 'Instant operation whose result persists on item records until consumed, worn down, or replaced.',
    stacking: 'Repeated permanent item mutations can accumulate where bounds permit; refills and identification do not stack.',
    effect: 'Hidden redistributes equipped maximum durability; Gloomy lowers weapon maximum damage and raises armour AC; Weird raises weapon maximum damage. Stone refills staff charges, Religious repairs durability, Eldritch converts carried life/mana potions to rejuvenation, and Glimmering identifies carried magical items.',
    removal: 'No status removal. Subsequent item use, damage, repair, sale, deletion, or another item mutation changes the stored item fields.', hellfire: false,
    lawBody: 'Vanilla shrine item mutations, derived from the engine: Hidden, Gloomy, and Weird permanently rewrite durability, armour, or weapon fields; Stone and Religious refill charges or durability; Eldritch converts potions; Glimmering identifies items. Their routines change item records immediately and grant no hero status, duration, or cleanse target.',
    refs: refs('.reference/devilutionX/Source/objects.cpp:2282', '.reference/devilutionX/Source/objects.cpp:2329', '.reference/devilutionX/Source/objects.cpp:2363', '.reference/devilutionX/Source/objects.cpp:2410', '.reference/devilutionX/Source/objects.cpp:2569', '.reference/devilutionX/Source/objects.cpp:2743'),
  },
  {
    id: 'd1-secluded-shrine-map-reveal', name: 'Secluded shrine map reveal', appliesTo: 'hero', source: 'Secluded shrine',
    duration: "For the current generated dungeon's automap state; no tick timer.",
    stacking: 'Idempotent reveal writes; repeated use adds no second effect.',
    effect: 'Marks every dungeon macro-cell explored with the shrine exploration marker. This is map-knowledge state, not an actor statistic or combat modifier.',
    removal: 'Cleared when that automap state is reinitialized or replaced; there is no gameplay dispel.', hellfire: false,
    lawBody: 'Secluded shrine map reveal, derived from the engine: the shrine marks every macro-cell explored in the current automap state. It has no countdown, magnitude, actor flag, or stacking rule beyond idempotent reveal writes. A later map-state reset removes the knowledge; combat cleanse cannot target it.',
    refs: refs('.reference/devilutionX/Source/objects.cpp:2731'),
  },
  {
    id: 'd1-fountain-instant-restoration', name: 'Blood Fountain and Purifying Spring restoration', appliesTo: 'hero',
    source: 'OBJ_BLOODFTN and OBJ_PURIFYINGFTN', duration: 'Instant per interaction.',
    stacking: 'Repeatable one-point mutations until the resource reaches its maximum.',
    effect: 'Blood Fountain adds one fixed-point whole HP to current/base life; Purifying Spring adds one whole mana to current/base mana. Each clamps at the corresponding maximum. Neither creates a timed regeneration state.',
    removal: 'Not applicable; later damage or spending changes the restored resource.', hellfire: false,
    lawBody: 'Blood Fountain and Purifying Spring restoration, derived from the engine: each interaction immediately adds one life or one mana and clamps at maximum. The fountains are repeatable resource sources; they do not attach regeneration, a fountain buff, or a timer to the hero.',
    refs: refs('.reference/devilutionX/Source/objects.cpp:3224'),
  },
  {
    id: 'd1-fountain-of-tears-stat-swap', name: 'Fountain of Tears stat swap', appliesTo: 'hero', source: 'OBJ_TEARFTN',
    duration: 'Permanent base-character mutation.', stacking: 'Each fountain is single-use; distinct fountains can accumulate subject to stat floors and caps.',
    effect: 'A deterministic choice from the fountain seed selects two different attributes, subtracting one base point from one and adding one base point to the other through ModifyPlr*.',
    removal: 'No expiry or cleanse; later permanent stat mutations can offset it.', hellfire: false,
    lawBody: 'Fountain of Tears stat swap, derived from the engine: one seed-selected base attribute loses one point and a different attribute gains one. The fountain becomes unusable after activation. This is a permanent character mutation, not a timed blessing or curse, and only later base-stat changes can offset it.',
    refs: refs('.reference/devilutionX/Source/objects.cpp:3280'),
  },
  {
    id: 'd1-equipped-cursed-modifiers', name: 'Equipped cursed numeric modifiers', appliesTo: 'hero',
    source: 'Vanilla item powers IPL_TOHIT_CURSE, IPL_DAMP_CURSE, IPL_TOHIT_DAMP_CURSE, IPL_ACP_CURSE, IPL_AC_CURSE, attribute curses, IPL_GETHIT_CURSE, IPL_LIFE_CURSE, IPL_MANA_CURSE, IPL_DUR_CURSE, and IPL_LIGHT_CURSE',
    duration: 'While an identified, stat-usable item is equipped; durability and base-item rewrites persist on the item itself.',
    stacking: 'Numeric modifiers from usable equipped items add together; final attributes, resources, light, and resistances use their own clamps.',
    effect: 'The powers lower hit chance, damage, armour, attributes, maximum life/mana, durability, or light radius, or increase damage taken. CalcPlrItemVals rebuilds the aggregate from equipped items instead of maintaining timed curse instances.',
    removal: 'Unequip, lose identification/usability, destroy, or replace the item and recalculate equipment. Item-record mutations remain until separately repaired or changed.', hellfire: false,
    lawBody: 'Equipped cursed numeric modifiers, derived from the engine: identified usable equipment contributes negative fields to a fresh aggregate calculation for hit, damage, armour, attributes, damage taken, life, mana, light, and related values. Multiple items add numerically. Unequipping removes their aggregate contribution; no timed curse or cleanse record exists.',
    refs: refs('.reference/devilutionX/Source/items.cpp:701', '.reference/devilutionX/Source/items.cpp:784', '.reference/devilutionX/Source/items.cpp:820', '.reference/devilutionX/Source/items.cpp:2792'),
  },
  {
    id: 'd1-equipped-no-mana', name: 'No Mana equipment effect', appliesTo: 'hero',
    source: 'Item power IPL_NOMANA / ItemSpecialEffect::NoMana', duration: 'While an identified, stat-usable source item is equipped.',
    stacking: 'Boolean OR across equipment; additional sources add no magnitude.',
    effect: 'Spell checks fail, partial mana restoration and Magic-based mana gains are suppressed, Mana Shield cannot absorb damage, and an active shield is removed. The flag does not itself create a timed drain.',
    removal: 'Unequip or invalidate every source item and recalculate equipment.', hellfire: false,
    lawBody: 'No Mana equipment effect, derived from the engine: a boolean equipment flag prevents spell casting and several mana gains, bypasses Mana Shield absorption, and causes an active shield to be removed. Multiple sources only OR the flag. Equipment recalculation clears it when the last usable source is unequipped; there is no duration or cleanse.',
    refs: refs('.reference/devilutionX/Source/items.cpp:892', '.reference/devilutionX/Source/spells.cpp:185', '.reference/devilutionX/Source/player.cpp:1764', '.reference/devilutionX/Source/player.cpp:3025'),
  },
  {
    id: 'd1-equipped-zero-resistance', name: 'Zero Resistance equipment effect', appliesTo: 'hero',
    source: 'Item power IPL_ALLRESZERO / ItemSpecialEffect::ZeroResistance', duration: 'While an identified, stat-usable source item is equipped.',
    stacking: 'Boolean OR; multiple sources do not reduce below zero.',
    effect: 'After equipment and class resistance contributions are collected, the flag resets magic, fire, and lightning resistance to zero before final clamping.',
    removal: 'Unequip or invalidate every source item and recalculate equipment.', hellfire: false,
    lawBody: 'Zero Resistance equipment effect, derived from the engine: one equipment flag resets magic, fire, and lightning resistance totals to zero after other contributions are gathered. Further sources add no magnitude. Removing the last usable source and recalculating equipment restores the ordinary totals; the effect has no timer or dispel.',
    refs: refs('.reference/devilutionX/Source/items.cpp:905', '.reference/devilutionX/Source/items.cpp:2605'),
  },
  {
    id: 'd1-equipped-drain-life', name: 'Drain Life equipment effect', appliesTo: 'hero',
    source: 'Item power IPL_DRAINLIFE / ItemSpecialEffect::DrainLife', duration: 'While an identified, stat-usable source item is equipped and the hero is outside town.',
    stacking: 'Boolean OR; multiple sources do not increase the tick damage.',
    effect: 'Every ProcessPlayers tick outside town calls physical player damage with 4 fixed-point units, equal to 1/16 HP. It is equipment-driven periodic damage rather than an applied ailment and can kill the hero.',
    removal: 'Unequip or invalidate every source item, recalculate equipment, or enter town.', hellfire: false,
    lawBody: 'Drain Life equipment effect, derived from the engine: while its equipment flag is present outside town, ProcessPlayers deals 4 fixed-point units—1/16 HP—every game tick. Multiple items only OR one flag, so damage does not stack. Unequipping the last source or entering town stops it; no actor-side DoT instance exists.',
    refs: refs('.reference/devilutionX/Source/items.cpp:966', '.reference/devilutionX/Source/player.cpp:3025'),
  },
  {
    id: 'd1-reflect-charges', name: 'Reflect charges', appliesTo: 'hero', source: 'Hellfire SpellID::Reflect / MissileID::Reflect',
    duration: 'Until all charges are consumed or a level change clears them; no tick timer.',
    stacking: 'Adds (spellLevel when nonzero, otherwise 2) × characterLevel charges, unless the addition would reach or exceed uint16 overflow, in which case nothing is added.',
    effect: 'A successful monster melee hit consumes one charge, including a hit that is blocked. It deals 20–30% of the rolled incoming physical damage back to the monster; on an unblocked hit, that reflected amount is also subtracted from incoming damage.',
    removal: 'Each triggering melee hit removes one charge. Zero charges or InitLevelChange clears the state.', hellfire: true,
    lawBody: 'Reflect charges, derived from the engine: Hellfire stores a persistent charge counter rather than a duration. Casting adds a level-scaled number unless that would overflow. Each successful monster melee hit or block consumes one charge and returns 20–30% of rolled damage; unblocked damage is reduced by the same amount. Level change clears all charges.',
    refs: refs('.reference/devilutionX/Source/missiles.cpp:1283', '.reference/devilutionX/Source/monster.cpp:1144', '.reference/devilutionX/Source/monster.cpp:1204', '.reference/devilutionX/Source/player.cpp:364', '.reference/devilutionX/Source/tables/spelldat.h:69'),
  },
  {
    id: 'd1-search-automap', name: 'Search automap effect', appliesTo: 'hero', source: 'Hellfire SpellID::Search / MissileID::Search',
    duration: '2 × characterLevel + 10 × spellLevel + 245 game ticks for a player source.',
    stacking: 'Extend; recasting adds the new duration to an existing same-source Search missile when integer overflow would not occur.',
    effect: 'Sets the local AutoMapShowItems presentation flag while its source-owned missile exists. It does not mark individual items or grant an actor attribute.',
    removal: 'Missile expiry clears the flag and plays the end sound; missile cleanup on level transition also ends it.', hellfire: true,
    lawBody: 'Search automap effect, derived from the engine: Hellfire uses a source-owned missile lasting 2 × character level + 10 × spell level + 245 ticks to enable the local show-items flag. Recasting extends the existing timer rather than adding a second effect. Expiry clears the flag; no item or hero receives a generic status record.',
    refs: refs('.reference/devilutionX/Source/missiles.cpp:1700', '.reference/devilutionX/Source/missiles.cpp:3271', '.reference/devilutionX/Source/tables/spelldat.h:69'),
  },
  {
    id: 'd1-berserk-monster-conversion', name: 'Berserk monster conversion', appliesTo: 'monster', source: 'Hellfire SpellID::Berserk / MissileID::Berserk',
    duration: 'Until the converted monster dies or is deleted; no timer or reversal path.', stacking: 'None; an already Berserk target is ineligible.',
    effect: 'An eligible nonunique, non-Diablo, non-minion monster without magic immunity gains MFLAG_BERSERK and MFLAG_GOLEM, independently scales ordinary and special damage by a random 120–129% plus spell level, gains a light, and participates in monster-versus-monster targeting/collision rules.',
    removal: 'Monster deletion removes its light; death/deletion ends the converted actor. The engine does not restore its old flags or damage.', hellfire: true,
    lawBody: "Berserk monster conversion, derived from the engine: Hellfire permanently adds Berserk and Golem flags to one eligible ordinary monster, increases all four damage bounds, adds a light, and changes monster-targeting relationships. Reapplication is rejected. There is no duration or restoration snapshot; only the monster's death or deletion ends it.",
    refs: refs('.reference/devilutionX/Source/missiles.cpp:1300', '.reference/devilutionX/Source/monster.cpp:634', '.reference/devilutionX/Source/monster.cpp:679', '.reference/devilutionX/Source/tables/spelldat.h:69'),
  },
  {
    id: 'd1-lightning-wall-contact-damage', name: 'Lightning Wall contact damage', appliesTo: 'both', source: 'Hellfire SpellID::LightningWall / MissileID::LightningWall',
    duration: '255 × (spellLevel + 1) game ticks per missile unless terrain ends its path.', stacking: 'Independent missiles; no actor-side stack or refresh.',
    effect: 'The live missile checks collision each tick. A hit restores the pre-collision remaining duration rather than deleting the wall, allowing repeated contact hits. No shocked, stunned, or lightning damage-over-time field is attached to an actor.',
    removal: 'The missile deletes when duration reaches zero without being restored by a hit, or when its path is otherwise terminated.', hellfire: true,
    lawBody: 'Lightning Wall contact damage, derived from the engine: Hellfire gives each wall missile 255 × (spell level + 1) ticks and reruns collision checks; a hit preserves the remaining lifetime. Targets receive no shock, stun, or periodic-effect record. Overlapping wall missiles remain independent terrain hazards rather than stacks.',
    refs: refs('.reference/devilutionX/Source/missiles.cpp:1587', '.reference/devilutionX/Source/missiles.cpp:3211', '.reference/devilutionX/Source/tables/spelldat.h:69'),
  },
  {
    id: 'd1-hellfire-detrimental-item-powers', name: 'Hellfire detrimental item powers', appliesTo: 'hero',
    source: 'IPL_FIRERES_CURSE, IPL_LIGHTRES_CURSE, IPL_MAGICRES_CURSE, IPL_DECAY, and IPL_PERIL',
    duration: "Resistance and Peril contributions last while equipped; Decay permanently mutates the weapon on qualifying weapon-damage calls.",
    stacking: 'Resistance penalties add; equipment flags OR. Each Decay call subtracts another five percentage-damage points.',
    effect: 'The three resistance curses subtract from their resistance totals before the 0–75 clamp. Peril makes a successful melee hit deal twice its eventual monster damage while applying the pre-class weapon roll plus damage-taken modifier to the hero, with a 1 HP floor. Decay subtracts five damage percent and unequips the weapon at −100 or lower.',
    removal: "Unequipping removes aggregate resistance/Peril flags. Decay's item mutation remains; reaching its threshold forcibly unequips the weapon.", hellfire: true,
    lawBody: 'Hellfire detrimental item powers, derived from the engine: resistance curses contribute negative equipped totals; Peril doubles successful melee damage while hurting the hero without killing them; Decay permanently removes five weapon-damage percentage points on each weapon-damage call and unequips at −100. These are equipment fields and item mutations, not timed curses.',
    refs: refs('.reference/devilutionX/Source/items.cpp:989', '.reference/devilutionX/Source/items.cpp:998', '.reference/devilutionX/Source/player.cpp:444', '.reference/devilutionX/Source/player.cpp:629', '.reference/devilutionX/Source/tables/itemdat.h:586'),
  },
  {
    id: 'd1-hellfire-shrine-persistent-mutations', name: 'Hellfire shrine persistent mutations', appliesTo: 'hero',
    source: "Oily, Glowing, Solar, and Murphy's shrines", duration: "Permanent character or item mutation; Oily's accompanying Fire Wall has its own missile lifetime.",
    stacking: 'Permanent stat changes accumulate within caps; item/resource mutations apply per shrine use.',
    effect: "Oily permanently grants two class-selected stat points and launches a Fire Wall. Glowing grants up to five Magic based on experience and reduces experience. Solar permanently adds two to a stat selected by local time. Murphy's halves one eligible equipped item's current durability or removes one third of gold if none is changed.",
    removal: 'No expiry or cleanse; later stat, experience, gold, durability, or item changes may offset the stored mutation.', hellfire: true,
    lawBody: "Hellfire shrine persistent mutations, derived from the engine: Oily, Glowing, and Solar permanently rewrite base attributes, with Oily separately spawning a Fire Wall; Murphy's rewrites item durability or gold. These are immediate character, item, or resource mutations. Their results do not occupy a timed shrine-status slot.",
    refs: refs('.reference/devilutionX/Source/objects.cpp:92', '.reference/devilutionX/Source/objects.cpp:1302', '.reference/devilutionX/Source/objects.cpp:2794', '.reference/devilutionX/Source/objects.cpp:2841', '.reference/devilutionX/Source/objects.cpp:2938', '.reference/devilutionX/Source/objects.cpp:2965'),
  },
] as const satisfies readonly StatusSpecData[];

export const STATUS_OVERVIEW = {
  lawBody: 'Diablo I status overview, derived from the engine: there is no generic status, damage-over-time, crowd-control, dispel, or stack container. Player booleans and counters, monster modes, goals and flags, equipment recomputation, and timed missiles each own their rules. Fire Wall, Inferno, Acid Puddle, and Lightning Wall rerun tile collision; they do not attach ailments. No shared global actor-status state exists.',
  refs: refs('.reference/devilutionX/Source/player.h:147', '.reference/devilutionX/Source/player.h:335', '.reference/devilutionX/Source/monster.h:76', '.reference/devilutionX/Source/monster.h:121', '.reference/devilutionX/Source/missiles.h:118', '.reference/devilutionX/Source/items.cpp:2792'),
} as const;
